### PR TITLE
Fix debug patients lock-up Operating Theatre room

### LINKED ISSUE #2862: [Bug] Operating Theatre - Debug patients lock-up room
### Describe the issue

After changes to the operating theatre a debug patient can get stuck after entering the room, standing idle on a tile in room.

Surgeons will continue to prepare for operation, then get locked to the Operating Table due to the interruptible state. This can't be broken by sending the patient home; or trying to edit the room.

### Steps to Reproduce

1. Load the 0.68.0 test save

2.  Spawn a debug patient with an operating theatre disease. (Kidney Beans or Spare Ribs)

3. Left click on surgeons and use the pickup tool to move them to the operating theatre (not right click).
4. Right click inside the room to tell the debug patient to use the room.
5. Observe patient gets stuck, and surgeons also get stuck.

### Expected Behaviour

In 0.68.0 release the debug patient can utilise the room. Then they encounter a different bug of not being cured/killed (unrelated to this issue)

### Save Game

Save game attached to report: No

### CorsixTH Version

Trunk

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
(Debug patient's action queue -- ignore it says male vs the image below)
Clicked on:
humanoid - class: Standard Male Patient
Warmth: 0.327   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.204  Toilet_Need: 0.062   Health: 0.848   Service Quality: 0.000
Actions: [idle, walk - going to 68:61   must_happen, use_screen - surgeon_screen   must_happen, walk - going to 65:65   must_happen, idle   must_happen, walk - going to 68:61   must_happen, use_screen - surgeon_screen   must_happen]
```

### Additional Information

Image

### PR DESCRIPTION
**Pull request by ARGAMX**
*Fixes #2862*

**Describe what the proposed change does**
- Looks like bedug patients have another actions queue state when joining the OP. So this change will handle both regular and debug patients.

### CODE REVIEW

File: CorsixTH/Lua/rooms/operating_theatre.lua [hunk 1]
```diff
@@ -239,7 +239,7 @@ function OperatingTheatreRoom:commandEnteringPatient(patient)
 
   local screen, sx, sy = self.world:findObjectNear(patient, "surgeon_screen")
   -- Patient walk to surgeon screen
-  patient:queueAction(WalkAction(sx, sy)
+  patient:setNextAction(WalkAction(sx, sy)
```
Comment (lewri) [inline CorsixTH/Lua/rooms/operating_theatre.lua:242]: Interesting how small that fix was!
