### PR TITLE
Better error handling for non-existent languages

### LINKED ISSUE #2978: [Bug] Unknown language error handling fails
### Describe the issue

When run game and click on ,,single scenario'', nothing happens. But iwhen I click on anything else after that, it's freeze. Button animation is there but nothign happens. When I click on Exit, the mouse cursor sticks on the Menu and I can move with all the menu. But I can't quit the game, start new game etc.
EDIT: I can't pla custom campaign also..
When I didn't click on Single Scenario and started new gane, it worked.
I tried to reinstal, then I tried to instal older version and this problem was still there.

A year later I played the ame with no problem. Today the game told that I need new actualisation. I dind't know how to make only the actualization withnout instalung new gane, so I downloaded new game and replaced and than after seing problems also uninstaled the old one.

### Steps to Reproduce

1. It happens when I instaled it.

2. 

3.

### Expected Behaviour

open Single scenario, choose and play. Or open and can go back.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

0.69.1 and 0.69.0

### Operating System

Win 10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
------------------------- CorsixTH configuration file -------------------------
-- Lines starting with two dashes (like this one) are ignored.
-- Text settings should have their values between double square braces, e.g.
--  setting = [[value]]
-- Number settings should not have anything around their value,
-- e.g. setting = 42
-- If you wish to go back to the default settings for everything, you can delete
-- this text file and it will be re-created when you play the game.
--
-------------------------------- SETTINGS MENU --------------------------------
-- These settings can also be changed from within the game in the settings menu
-------------------------------------------------------------------------------
-- Screen size. Must be at least 640x480. Larger sizes will require better
-- hardware in order to maintain a playable framerate. The fullscreen setting
-- can be true or false, and the game will run windowed if not fullscreen.
--
fullscreen = false

width = 1680
height = 1050

-------------------------------------------------------------------------------
-- Language to use for ingame text. Between the square braces should be one of:
--  Brazilian Portuguese  / pt_br / br
--  Chinese (simplified)  / zh(s) / chi(s)
--  Chinese (traditional) / zh(t) / chi(t)
--  Czech                 / cs / cze
--  Danish                / da / dk
--  Dutch                 / Nederlands / nl / dut / nld
--  English               / en / eng
--  Finnish               / Suomi / fi / fin
--  French                / fr / fre / fra
--  German                / de / ger / deu
--  Hungarian             / hu / hun
--  Italian               / it / ita
--  Japanese              / ja / jp
--  Korean                / kor / ko
--  Norwegian             / nb / nob
--  Polish                / pl / pol
--  Portuguese            / pt / por
--  Russian               / ru / rus
--  Spanish               / es / spa
--  Swedish               / sv / swe
--  Ukrainian             / uk / ukr
--
language = [[ e tina]]

-------------------------------------------------------------------------------
-- Audio global on/off switch.
-- Note that audio will also be disabled if CorsixTH was compiled without
-- the SDL_mixer library.
--
audio = true

------------------------------ CUSTOM GAME MENU -------------------------------
-- These settings can also be changed from the opening menu screen
-- in the custom games or new game menus
-------------------------------------------------------------------------------
-- Free Build or Sandbox mode
-- You cannot win or lose custom made maps if this is set to true.
-- You also don't have to worry about money.
-- This setting does not apply to any of the campaign maps.
--
free_build_mode = false

--------------------------------- OPTIONS MENU --------------------------------
--These settings can also be changed from within the game from the options menu
-------------------------------------------------------------------------------
-- Sounds: By default enabled and set at level 0.5
--
play_sounds = true
sound_volume = 0.5

-------------------------------------------------------------------------------
-- Announcements: By default set at level 0.5
--
play_announcements = true
announcement_volume = 0.5

-------------------------------------------------------------------------------
-- Background music: By default enabled and set at level 0.5
--
play_music = true
music_volume = 0.5

-------------------------------------------------------------------------------
-- Edge scrolling: By default enabled (prevent_edge_scrolling = false).
--
prevent_edge_scrolling = false

-------------------------------------------------------------------------------
-- Capture mouse: By default enabled (capture mouse = true).
--
capture_mouse = true

-------------------------------------------------------------------------------
-- Right Mouse Scrolling: By default, it is disabled (right_mouse_scrolling = false).
-- This means that the default scrolling method is pressing the middle mouse button.
-- Please note this an Experimental Feature and may interfere with other right mouse
-- operations. Report bugs for this on Github Issue 2469.
--
right_mouse_scrolling = false

-------------------------------------------------------------------------------
-- Adviser on/off: If you set this to true the adviser will no longer
-- pop up.
--
adviser_disabled = false

-------------------------------------------------------------------------------
-- Scrolling Momentum.
-- Determines the amount of momentum when scrolling the map with the mouse.
-- This should be a value between 0 and 1 where 0 is no momentum
--
scrolling_momentum = 0.8

-------------------------------------------------------------------------------
-- Top menu clock is by default is always on
-- setting to true will give you a twentyfour hours display
-- change to false if you want AM / PM time displayed.
--
twentyfour_hour_clock = true

-------------------------------------------------------------------------------
-- Automatically check for updates.
-- If set to true, CorsixTH will automatically check for and alert you to newer
-- versions on startup.
--
check_for_updates = true

-------------------------------------------------------------------------------
-- Warmth Colors display settings.
-- This specifies which display method is set for warmth colours by default.
-- Possible values: 1 (Red), 2 (Blue Green Red) and 3 (Yellow Orange Red).
--
warmth_colors_display_default = 1

------------------------------ CUSTOMISE SETTINGS -----------------------------
-- These settings can also be changed from the Customise Menu

-------------------------------------------------------------------------------
-- Wage increase request settings.
-- If set to true when wage increase requests expire automatically grant them
-- otherwise let the staff member quit.
--
grant_wage_increase = false

-------------------------------------------------------------------------------
-- Movie global on/off switch.
-- Note that movies will also be disabled if CorsixTH was compiled without the
-- FFMPEG library.
--
movies = true

-- Intro movie: Enabled by default
--
play_intro = true

-- Demo movie (played on idle at main menu): Enabled by default
--
play_demo = true

-------------------------------------------------------------------------------
-- Allow user actions while game is paused
-- In Theme Hospital the player would only be allowed to use the top menu if
-- the game was paused. That is the default setting in CorsixTH too, but by
-- setting this to true everything is allowed while the game is paused.
--
allow_user_actions_while_paused = false

-------------------------------------------------------------------------------
-- VOLUME CONTROL IS OPENING THE DRUG CASEBOOK?

-- If your keyboard volume control opens the Drug Casebook at the same time
-- then change this to true. From then on you will have to use Shift + C to open
-- the Casebook and volume down will not open it.
-- For example for shift + C to open casebook change the setting below to = true
--
volume_opens_casebook = false

-------------------------------------------------------------------------------
-- To allow patients with Alien DNA to visit your hospital other than by an
-- emergency change the settings below. Understand that there are no animations
-- for sitting down, opening or knocking on doors etc.
-- So, like with Theme Hospital to do these things they will appear to change
-- to normal looking and then change back.
--
alien_dna_only_by_emergency = true
alien_dna_must_stand = true
alien_dna_can_knock_on_doors = false

-- To allow female patients with fractured bones, which are by default
-- disabled due to poor animation that skips and jumps a bit
--
disable_fractured_bones_females = true

-------------------------------------------------------------------------------
-- By default the player selects any extra objects they want for each room they
-- build. If you would like the game to remember what you usually add, then
-- change this option to true.
--
enable_avg_contents = false

-------------------------------------------------------------------------------
-- By default destroyed rooms can't be removed. If you would like the game to
-- give you the option of removing a destroyed room change this option to true.
--
remove_destroyed_rooms = false

------------------------------- FOLDER SETTINGS -------------------------------
-- These settings can also be changed from the Folders Menu
-------------------------------------------------------------------------------
-- Theme hospital install folder: original game data files are loaded from this
-- folder. Between the square braces should be the folder which contains the
-- original HOSPITAL.EXE and/or HOSP95.EXE file. This can point to a copy of
-- the Theme Hospital demo, though a full install of the original game is
-- preferred.
--
theme_hospital_install = [=[C:\Program Files (x86)\GOG Galaxy\Games\Theme Hospital]=]

-------------------------------------------------------------------------------
-- Font file setting. Can be changed from main game menu
-- Specify a font file here if you wish to play the game in a language not
-- present in the original game. Examples include Russian, Chinese and Polish.
--
unicode_font = nil -- [[X:\ThemeHospital\font.ttc]]

-------------------------------------------------------------------------------
-- Savegames. By default, the "Saves" directory alongside this config file will
-- be used for storing saved games in. Should this not be suitable, then
-- uncomment the following line, and point it to a directory which exists and
-- is more suitable.
--
savegames = nil -- [[X:\ThemeHospital\Saves]]

-------------------------------------------------------------------------------
-- Levels and Campaigns. By default, the "Levels" and "Campaigns" directory next to
-- this config file will be used for storing new maps / levels / campaigns in. If
-- this is not suitable, then uncomment the following lines, and point it to a directory
-- which exists and is more suitable.
-- Note: Newly created maps in the Map Editor go into the "Levels" folder currently.
--
levels = nil -- [[X:\ThemeHospital\Levels]]
campaigns = nil -- [[X:\ThemeHospital\Campaigns]]

-------------------------------------------------------------------------------
-- Use new graphics. Whether to use the original graphics from Theme Hospital
-- or use new graphics created by the CorsixTH project.
-- Developer use only, otherwise the game will very likely crash in normal use
use_new_graphics = false

-------------------------------------------------------------------------------
-- Graphics folder. All graphics are initially taken from the original
-- Theme Hospital, but the game can also try to find new graphics in the
-- specified folder below. Some graphics are shipped with CorsixTH, and they
-- will be used if you just switch on new graphics. If you however have
-- acquired graphics from somewhere else, then uncomment the following line
-- and point it to the directory which contains the new graphics.
new_graphics_folder = nil -- [[X:\ThemeHospital\Graphics]]

-------------------------------------------------------------------------------
-- Screenshots. By default, the "Screenshots" directory alongside this config
-- file will be used for saving screenshots. Should this not be suitable, then
-- uncomment the following line, and point it to a directory which exists and
-- is more suitable.
--
screenshots = nil -- [[X:\ThemeHospital\Screenshots]]

-------------------------------------------------------------------------------
-- If you want to listen to non-Theme-Hospital music, then follow these steps:
--  1) Find updated versions of the original tracks (a link to ZR's Remixes can
--     be found on the CorsixTH wiki) or any other music you want to listen to.
--  2) Uncomment the next line and point it to where the music files are.
--  3) If you want to change the names of songs ingame, make a file called
--     "names.txt" and write the file name on one row, followed by the desired
--     ingame name on the next row.
--
audio_music = nil -- [[X:\ThemeHospital\Music]]

-------------------------------------------------------------------------------
-- SoundFont: CorsixTH uses the FluidR3 SoundFont by default for playing MIDI music.
-- Windows users, and other OS versions compiled with the FluidSynth software
-- synthesiser can specify their own SoundFont file below (.sf2 or .sf3).
-- Mac(OS) Source Ports build users, and OS versions compiled with TiMidity
-- won't see any effect from this option. See our Wiki for alternative options.
--
soundfont = nil -- [[X:\ThemeHospital\FluidR3.sf3]]

------------------------------- SPECIAL SETTINGS ------------------------------
-- These settings can only be changed here
-------------------------------------------------------------------------------
-- Audio playback settings.
-- These can be commented out to use the default values from the game binary.
-- Note: On some platforms, these settings may not effect MIDI playback - only
-- sound effects and music audio. If you are experiencing poor audio playback,
-- then try doubling the buffer size.
--
audio_frequency = 22050
audio_channels = 2
audio_buffer_size = 2048

-------------------------------------------------------------------------------
-- Debug settings.
-- If set to true more detailed information will be printed in the terminal
-- and a debug menu will be visible.
--
debug = false

-- Experimental setting for falling patients. (debug only!)
-- CorsixTH does not yet have reliable handling for falling actions and enabling it
-- could cause dropped action queues or undesired bugs. You should leave this setting
-- off unless you're developing with it
--
debug_falling = false

-- If set to true, the FPS, Lua memory usage, and entity count will be shown
-- in the dynamic information bar. Note that setting this to true also turns
-- off the FPS limiter, causing much higher CPU utilisation, but resulting in
-- more useful FPS values, as they are not artificially capped.
--
track_fps = false

-------------------------------------------------------------------------------
-- Zoom Speed: By default this is set at 80
-- Any number value between 10 and 1000, 10 is very slow and 1000 is very fast!
--
zoom_speed = 80

-------------------------------------------------------------------------------
-- Scroll Speeds: The speed of scrolling with and without shift being held.
-- Any number value between 1 and 10, 1 is very slow and 10 is fast!
--
scroll_speed = 2
shift_scroll_speed = 4

-------------------------------------------------------------------------------
-- Room information dialogs: Information about new rooms, important for
-- additional rooms in later levels. Affects campaign only.
--
room_information_dialogs = true

-------------------------------------------------------------------------------
-- If true, parts of the hospital can be made inaccessible by blocking the path
-- with rooms or objects. If false, all parts of the hospital must be kept
-- accessible, the game will disallow any attempt to blocking the path.
--
allow_blocking_off_areas = false

-------------------------------------------------------------------------------
-- Direct Zoom: Avoid rendering to an intermediate texture when zooming.
-- Improves performance and reliability on some hardware.
--
direct_zoom = nil

-------------------------------------------------------------------------------
-- Replacing Machines: By default, you will see a new machines initial strength
-- before purchasing it. If you don't want this change the value to false.
--
new_machine_extra_info = true

-------------------------------------------------------------------------------
-- By default your username will be your name in the game. You can change it in
-- the New Game menu or between the brace brackets below like [[NAME]].
-- Note: space is limited in the game, so don't enter a name that is too long!
--
player_name = [=[stulz]=]
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2978*

**Describe what the proposed change does**
- Adds helper function to check player's specified language exists
- Returns language to English and shows error message on main menu (fixes crash at end of movie and elsewhere). 
- Tell the player the language value they originally set and where to go to fix (as there are now two error types).
- Also includes some refactor to accommodate new handling
- Doc, as usual.

One quirk is that as part of `App:fixConfig()` we force lowercase the language on launch. However, we still try to convert back to lowercase in other places (mostly) unnecessarily. My use of capitalised `[[English]]` on App.lua line 516 probably needs changing if there's a future PR to clean things up.

image

image

### CODE REVIEW

File: CorsixTH/Lua/app.lua [hunk 1]
```diff
@@ -506,21 +504,41 @@ function App:initScreenshotsDir()
...
+    self.config.language = language
+    self:saveConfig()
+    success = false
+  end
+
+  local exists = self.strings:checkLanguageExists(language)
+  if not exists then
+    -- Not existent language, revert to English.
+    err = "The game language set in the configuration file: " .. language ..
+          " was not valid. It has been reverted to English. Please select your" ..
```
Comment (ARGAMX) [inline CorsixTH/Lua/app.lua]: Just a nits:
As we have already know from this issue, there may be some unreadable garbage in place of the variable from the config.
And this garbage text may contain spaces and when reading it, it is not clear where the name of the thing is ends...
It probably cool to wrap the inserted variables in any quotation marks or signs.

`The game language set in the configuration file ' e tina' was not valid.`
`The game language set in the configuration file < e tina> was not valid.`

**Review by ARGAMX — COMMENTED** [review]
Nice fix 👍

**Review by ARGAMX — APPROVED** [review]

File: CorsixTH/Lua/app.lua (hunk 1 above)
Comment (lewri) [reply CorsixTH/Lua/app.lua]: It used to be `'`, so it was my own choice to prefer colons (should've inserted a new line probably and put more time rewriting). Inequality signs aren't supported by the TH Font so we can't use those.

I'll add the quotation back in soon.

Comment (lewri) [inline CorsixTH/Lua/app.lua]:
```suggestion
    err = "The game language set in the configuration file '" .. language ..
          "' was not valid. It has been reverted to English. Please select your" ..
```

File: CorsixTH/Lua/app.lua [hunk 2]
```diff
@@ -506,21 +504,41 @@ function App:initScreenshotsDir()
...
     self.gfx.language_font = font
   else
-    -- Otherwise revert to english.
-    self.gfx.language_font = self.strings:getFont("english")
-    language = "english"
-    self.config.language = "english"
-    success = false
+    -- Font unavailable, revert to English.
+    err = "The game language has been reverted to English because the desired" ..
+          " language: " .. language .. " could not be loaded. Please make sure" ..
```
Comment (lewri) [inline CorsixTH/Lua/app.lua]:
```suggestion
          " language '" .. language .. "' could not be loaded. Please make sure" ..
```

**Review by tobylane — APPROVED** [review]

File: CorsixTH/Lua/app.lua [hunk 3]
```diff
@@ -506,21 +504,41 @@ function App:initScreenshotsDir()
...
+--! Initialises the application's language based on the player's choice.
+--!return success (boolean) Whether the chosen language was initialised
+--!return err (string) What to report back to the player on failure
 function App:initLanguage()
   -- Make sure that we can actually show the desired language.
-  -- If we can't, then the player probably didn't specify a font file
-  -- in the config file properly.
-  local success = true
+  -- If we can't, work out the most common issue and reset to English.
+  local success, err = true, ""
```
Comment (TheCycoONE) [inline CorsixTH/Lua/app.lua]: nil is conventional if there is no error.

Comment (lewri) [reply CorsixTH/Lua/app.lua]:
```suggestion
  local success, err = true, nil
```
