### PR TITLE
Fix tick_rate remapping

### LINKED ISSUE #2788: [Bug] isCurrentSpeed world.lua crash
### Describe the issue

Problem in `isCurrentSpeed` in `world.lua`

Most savegames loads ok, but this one fails. Not sure why.

0.68 works ok but current master give crash.

### Steps to Reproduce

1. **DOWNLOAD** save game attached to this ticket.
2. Put it to your **Saves** folder.
3. Run game and load that savegame.
4. Observe game error on load attempt.
5. Press "Continue game" in main menu.
6. Observe that game loaded but eventually crash after load.

### Save Game

[isCurrentSpeed_crash.sav.zip](https://github.com/user-attachments/files/19040075/isCurrentSpeed_crash.sav.zip)

### CorsixTH Version

7fa317c trunk master

### Operating System

MacOS Sonoma 14.5

### Gamelog.txt

```yaml
Error in keydown handler: 
attempt to get length of a nil value
stack traceback:
	[C]: in function 'unpack'
	...Corsix.Lab.app/Contents/MacOS/../Resources/Lua/world.lua:735: in method 'isCurrentSpeed'
	...Corsix.Lab.app/Contents/MacOS/../Resources/Lua/world.lua:752: in method 'setSpeed'
	...nt/Corsix.Lab.app/Contents/MacOS/../Resources/Lua/ui.lua:1033: in method 'removeWindow'
	...orsix.Lab.app/Contents/MacOS/../Resources/Lua/window.lua:125: in field 'close'
	...ntents/MacOS/../Resources/Lua/dialogs/confirm_dialog.lua:109: in method 'close'
	...nt/Corsix.Lab.app/Contents/MacOS/../Resources/Lua/ui.lua:1010: in method 'addWindow'
	...rsix.Lab.app/Contents/MacOS/../Resources/Lua/game_ui.lua:1320: in method 'quit'
	...Contents/MacOS/../Resources/Lua/dialogs/bottom_panel.lua:171: in field 'callback'
	...nt/Corsix.Lab.app/Contents/MacOS/../Resources/Lua/ui.lua:737: in field 'onKeyDown'
	...rsix.Lab.app/Contents/MacOS/../Resources/Lua/game_ui.lua:351: in function <...rsix.Lab.app/Contents/MacOS/../Resources/Lua/game_ui.lua:350>
	(...tail calls...)
	...t/Corsix.Lab.app/Contents/MacOS/../Resources/Lua/app.lua:1148: in function <...t/Corsix.Lab.app/Contents/MacOS/../Resources/Lua/app.lua:1143>
```

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2788*

**Describe what the proposed change does**
- Attempting to update speed normally from a change in the tick rate table causes `self.prev_speed` to be set to `nil`
- Instead, tick rates are directly assigned for this afterload only
- Failsafe also altered, so the game is briefly set to pause rates, then normal speed is reapplied.
- the `Speed up` tick rate is also now entered for the original `old_tick_rates` table.

In both cases these changes will retain the `self.prev_speed` value.

Only downside is if the game was paused; in the failsafe method it will unpause. But that should be addressed separately e.g. as part of #2254 patches.

### CODE REVIEW

File: CorsixTH/Lua/world.lua [hunk 1]
```diff
@@ -2509,11 +2512,18 @@ function World:afterLoad(old, new)
...
+        self.hours_per_tick = tick_rates[name][1]
+        self.tick_rate = tick_rates[name][2]
+        -- There is also no need to run it afterward either
         break
       end
     end
+    -- No conversion available; reset instead
     if not found_speed then
+      self.hours_per_tick = tick_rates["Pause"][1]
+      self.hours_per_tick = tick_rates["Pause"][2]
```
Comment (TheCycoONE) [inline CorsixTH/Lua/world.lua:2526]: This would appear to be wrong as written.

**Review by lewri — COMMENTED** [review]
Fixed now
