### PR TITLE
Use intermediate screen-sized buffer for direct_zoom

### LINKED ISSUE #1930: [Bug] Significant aliasing in fullscreen with direct_zoom
#### Describe the issue

With direct_zoom enabled, fullscreen mode is noticeably more aliased than without. See screenshots below.

#### Steps to Reproduce
1. Open the game

2. Press alt+enter to enter fullscreen

#### Save Game

N/A

#### Expected Behavior

Expect smooth consistent looking rendering.

#### System Information
**CorsixTH Version:** *0.65*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt

N/A

### Additional Info

Without direct_zoom:
fullscreen-expected

With direct_zoom:
fullscreen

### PR DESCRIPTION
**Pull request by flackr**
*In combination with #1931 this fixes #1930*

**Describe what the proposed change does**
- Initialize and use an intermediate screen sized buffer when in fullscreen.

Note that this still has the advantage over indirect zoom that the buffer will always be screen-sized, rather than growing larger as you zoom out so it should still should fix the original crash issue that direct_zoom fixed with hopefully full parity in render quality.

**Screenshot:**
titlescreen-intermediate-buffer

### CODE REVIEW

File: CorsixTH/Src/th_gfx_sdl.cpp [hunk 1]
```diff
@@ -389,6 +389,12 @@ bool render_target::set_scale_factor(double fScale, scaled_items eWhatToScale) {
     return false;
   } else if (eWhatToScale == scaled_items::all && direct_zoom) {
     global_scale_factor = fScale;
+    if ((SDL_GetWindowFlags(window) & SDL_WINDOW_FULLSCREEN_DESKTOP) ==
```
Comment (TheCycoONE) [inline CorsixTH/Src/th_gfx_sdl.cpp:392]: This function is actually called even more than once a frame, at least 2, maybe 3 times. It's called with a value of 1 before drawing UI elements, and then with a value of the current zoom level before drawing the map. That's why flush_zoom_buffer is called at the beginning of this function and the end of the frame.

**Review by TheCycoONE — COMMENTED** [review]
Do you have an idea why this works? I think I found the same thing years ago (why the fScale == 1 condition is below the zoom instead of above), but I don't recall why.

**Comment by TheCycoONE** [comment]
Haven't tried it yet but I wonder if SDL_WindowGetDisplayMode could be used to determine if the full screen window was running at native resolution.

File: CorsixTH/Src/th_gfx_sdl.cpp (hunk 1 above)
Comment (flackr) [reply CorsixTH/Src/th_gfx_sdl.cpp:392]: > Do you have an idea why this works? I think I found the same thing years ago (why the fScale == 1 condition is below the zoom instead of above), but I don't recall why.

I haven't narrowed down exactly why the quality is so different. My leading guess is that drawing to an intermediate texure gives a pixel perfect rendering which is later upsampled as a whole whereas drawing directly is immediately upsampling each draw call smearing textures across pixels.

Comment (flackr) [reply CorsixTH/Src/th_gfx_sdl.cpp:392]: > This function is actually called even more than once a frame, at least 2, maybe 3 times. It's called with a value of 1 before drawing UI elements, and then with a value of the current zoom level before drawing the map. That's why flush_zoom_buffer is called at the beginning of this function and the end of the frame.

It should be easy to remove the intermediate flush calls and use a single texture with direct_zoom given that the texture is always screen size.

**Review by TheCycoONE — APPROVED** [review]
As discussed in IRC, any optimizations can come later.

**Comment by flackr** [comment]
Note that this should be merged after #1931 , without which the intermediate texture would just use nearest quality when upscaled.
