### PR TITLE
FIX Crash seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')

### LINKED ISSUE #1232: Crash seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
#### Describe the issue
A woman wanted to go to the shrink, I built his office and recruited him but she still didn't go there.
The game crashed with an error message ("Sorry a humanoid just has an empty action queue, which means that he or she didn't know what to do next. Please consult the command window for more detailed information. A dialog with the offending humanoid has been opened. Would you like him/her to leave the hospiral?) and the log below.

#### Save Game
https://drive.google.com/open?id=0B9SUHZiI6ptSc3VzaWh4WmlDaTQ

#### System Information
**CorsixTH Version: 0.60

**Operating System:** Windows 10

**Theme Hospital Version: Origin

#### Gamelog.txt
```
Created game with savegame version 111.

Empty action queue!
Last action: walk
stack traceback:
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:546: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
The humanoid was told to leave the hospital...

Empty action queue!
Last action: walk
stack traceback:
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:546: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
The humanoid was told to leave the hospital...
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 000001C74C2FA4B0) from humanoid (table: 000001C74BA7C2A0).
Warning: Trying to remove nonexistant room remove callback (function: 000001C74CB16E20) from humanoid (table: 000001C74BA7C2A0).
Warning: Trying to remove nonexistant room build callback (function: 000001C74B724DC0) from humanoid (table: 000001C751C0C3B0).
Warning: Trying to remove nonexistant room remove callback (function: 000001C74BD2EF80) from humanoid (table: 000001C751C0C3B0).
Warning: Trying to remove nonexistant room build callback (function: 000001C74BF9B440) from humanoid (table: 000001C74B310860).
Warning: Trying to remove nonexistant room remove callback (function: 000001C7522F1950) from humanoid (table: 000001C74B310860).
Savegame version is 111 (v0.60), originally it was 111 (v0.60)
Warning: Trying to remove nonexistant room build callback (function: 000001485BD44B10) from humanoid (table: 00000148551A5240).
Warning: Trying to remove nonexistant room remove callback (function: 0000014849499F70) from humanoid (table: 00000148551A5240).
Warning: Trying to remove nonexistant room build callback (function: 0000014855453CE0) from humanoid (table: 000001485473E170).
Warning: Trying to remove nonexistant room remove callback (function: 000001485A3A1FB0) from humanoid (table: 000001485473E170).
Warning: Trying to remove nonexistant room build callback (function: 0000014848E51D70) from humanoid (table: 00000148560120F0).
Warning: Trying to remove nonexistant room remove callback (function: 00000148539154A0) from humanoid (table: 00000148560120F0).
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in method 'finishAction'
	D:\Jeux\CorsixTH\Lua\humanoid_actions\walk.lua:152: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...
Warning: Trying to remove nonexistant room build callback (function: 000001485A749080) from humanoid (table: 0000014855AA4530).
Warning: Trying to remove nonexistant room remove callback (function: 000001485B234140) from humanoid (table: 0000014855AA4530).
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in method 'finishAction'
	D:\Jeux\CorsixTH\Lua\humanoid_actions\walk.lua:152: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>
Recovering from error in timer handler...
Error in timer handler: 
D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: attempt to perform arithmetic on a boolean value (local 'this_score')
stack traceback:
	D:\Jeux\CorsixTH\Lua\humanoid_actions\seek_reception.lua:47: in field '?'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:580: in upvalue 'Humanoid_startAction'
	D:\Jeux\CorsixTH\Lua\entities\humanoid.lua:672: in local 'timer_function'
	D:\Jeux\CorsixTH\Lua\entity.lua:219: in method 'tick'
	D:\Jeux\CorsixTH\Lua\world.lua:1075: in method 'onTick'
	D:\Jeux\CorsixTH\Lua\app.lua:1000: in function <D:\Jeux\CorsixTH\Lua\app.lua:997>
	(...tail calls...)
	D:\Jeux\CorsixTH\Lua\app.lua:901: in function <D:\Jeux\CorsixTH\Lua\app.lua:896>

```

### PR DESCRIPTION
**Pull request by nMustaki**
*Fixes #1232*

**Describe what the proposed change does**

Refactor a bit the method `action_seek_reception_start` in `seek_reception.lua` :
- Add a guard to call of `getPathDistance` for boolean return value
- Remove one call to `getPathDistance` and reuse the already computed distance

I've also checked that the rest of the codebase is handling this case.

### CODE REVIEW

**Review by lewri — COMMENTED** [review]
Looks okay. As we're changing code inside a humanoid action we definitely want to make sure we take extra care. May benefit from some extensive testing too of trying to intentionally break the change (as we learnt, build while paused can be one we we miss)

For what I read, the humanoid should idle as suggested by @TheCycoONE in the issue if there isn't a desk found in reach.

Also contributes in part to #826, so that's nice.

**Comment by nMustaki** [comment]
Regarding testing, is it unittests or manual?

File: CorsixTH/Lua/humanoid_actions/seek_reception.lua [hunk 1]
```diff
@@ -78,13 +79,16 @@ local function action_seek_reception_start(action, humanoid)
...
       local y = desk.tile_y + orientation.use_position[2]
-      local this_score = humanoid.world:getPathDistance(humanoid.tile_x, humanoid.tile_y, x, y)
 
-      this_score = this_score + desk:getUsageScore()
-      if not score or this_score < score then
-        -- It is better, or the first one!
-        score = this_score
-        best_desk = desk
+      local distance_from_desk = humanoid.world:getPathDistance(humanoid.tile_x, humanoid.tile_y, x, y)
+      if distance_from_desk ~= false then
```
Comment (Alberth289346) [inline CorsixTH/Lua/humanoid_actions/seek_reception.lua:84]: Just `if distance_from_desk then` (suggested code changes seem to have disappeared). `0` evaluates to `true` in Lua.

**Comment by Alberth289346** [comment]
This is the function that gets returned on import. No idea what that means wrt to updating a running game,

It doesn't seem to be used in callbacks (at least in `seek_reception.lua`) so that's good.

File: CorsixTH/Lua/humanoid_actions/seek_reception.lua (hunk 1 above)
Comment (nMustaki) [reply CorsixTH/Lua/humanoid_actions/seek_reception.lua:84]: The 0 evaluation to true is very weird coming from Python, thanks for the reminder !

```suggestion
      if distance_from_desk then
```

Comment (Alberth289346) [reply CorsixTH/Lua/humanoid_actions/seek_reception.lua]: I agree it's weird at first sight, but in a sense it's cleaner. In Lua `true` and `false` are boolean values, numbers are values exclusively used for computing numeric results.

The reason why `0/1` are often interpreted as boolean comes from original C, which didn't have booleans by itself and instead borrowed the CPU-level notion of it, a single bit that is either `0` or `1`.

While pretty soon everybody wrote
``` C
#define TRUE 1
#define FALSE 0
```
in C to have names for boolean values, the `0/1` idea was still copied to many other languages at first, and then kept when they added proper `true/false` notions for backwards-compatibility.

**Review by Alberth289346 — APPROVED** [review]

**Comment by lewri** [comment]
> Regarding testing, is it unittests or manual?

Manual, so in essence try to break it.

In reality I can't perceive this breaking (but we've said that before!). Otherwise I'm fine with this PR.

**Comment by nMustaki** [comment]
@lewri I couldn't find any way to break it manually

**Comment by lewri** [comment]
> @lewri I couldn't find any way to break it manually

Nice, good enough for me. We can't fix patients already performing the action before this code-change but all future ones will be fixed. Merging.
