### PR TITLE
Change how staff find work

### LINKED ISSUE #1582: Doctors in GPs office don't look for work autonomously
#### Describe the issue
The doctors in GPs office will only answer calls when having dealt with a patient. A call from the call dispatcher can still send them to a room, but if they are idle in a room, they won't answer a call, as they don't meander to look for work themselves within the room.

#### Steps to Reproduce
A contrived example can be replicated by building a single GPs office and one diagnosis room and having one doctor. After a patient is dealt with, they may seek out the diagnosis room. The doctor in the GP office will leave the room (findWorkForStaff is called at the end of GPRoom:dealtWithPatient).

Pick up doctor and place back in GPs Office. The patient goes to diagnostic room, call dispatcher has the call in the queue, and Doctor won't answer the call.

#### Expected Behavior
Doctors in GPs Office, should answer calls if available. Replicating the example above in the original TH and the doctor does answer the call.

Something like the below, in the loop callback in GPRoom:doStaffUseCycle, prevents the loop repeating again and allows the doctor to find work.
```lua
  local gp_loop_callback = --[[persistable:gp_loop_callback]] function()
    desk_use_time = desk_use_time - 1
    if desk_use_time == 0 then
      if humanoid:isIdle() then
        self:findWorkForStaff()
        if not humanoid:isIdle() then
          return
        end
      end
```
The downside of the above is that the doctor might become a candidate, and thus leave the room, affecting the queue assignment, call assignment etc (like behaviour mentioned in #1290). Potentially mitigated by penalising the priority (CallsDispatcher.getPriorityForRoom) for a room by taking into account the doctor will leave the room, probably will result in another call for a doctor.

#### System Information
**CorsixTH Version:** replicated on 0.6 and latest trunk

### LINKED ISSUE #2060: [Bug] Free doctors do not see patients waiting in other rooms
#### Describe the issue
I've just downloaded 0.65 version and I can notice some behavior different from previous versions.
I have patients waiting in General Diagnosis and also for Psychiatric, but neither the surgeons leave the Operating Theatre nor the psychiatrist on the GP's office is going to attend the Psychiatric or General Diagnosis rooms.

There are no patients in the row for Operating Theatre nor GP's offices room and Staff Leave Rooms is enabled.

Why don't they leave the Operating Theatre and GP's office to go to rooms with patients waiting?

#### Steps to Reproduce
1. Load save game attached to this ticket
2. Check conditions described above

#### Save Game
[21-STAGE3.zip](https://github.com/CorsixTH/CorsixTH/files/7230240/21-STAGE3.zip)

#### Expected Behavior
Doctors should leave rooms when there is no patients in the row of that room but there are patients in others.

#### System Information
**CorsixTH Version:** 0.65

**Operating System:** Windows 10 21H1 Version (Compilation 19043.1237)

**Theme Hospital Version:** CD

### PR DESCRIPTION
**Pull request by mugmuggy**
This is a proposal to address these issues. The fix has had some funky behaviour in scenarios where a Dr calls to the room, patient leaves for toilet, before call is completed, then the staff member leaves the room and heads to the next room, where the same thing occurs and ended up returning to the same first room.

There is also a change to prefer wandering staff but not sure how effective that is at the moment to get them, due to the weighting of fatigue beforehand. For when excess staff are employed and they leave staff room after rest and there is no call, they start wandering, but they'll have near 0 fatigue and all else being equal is a distance difference of 10 tiles to have the staff leave the room instead.

*Fixes #1582 
Fixes #2060*

**Describe what the proposed change does**
- Penalise finding work if in a room over a doctor that is wandering
- Move the find work call outside of the dealtWithPatient process

### CODE REVIEW

File: CorsixTH/Lua/room.lua [hunk 1]
```diff
@@ -202,20 +202,6 @@ function Room:dealtWithPatient(patient)
...
--- sends them away if they're needed somewhere else.
-function Room:findWorkForStaff()
-  -- If the staff member is idle we can send him/her somewhere else
-  for humanoid in pairs(self.humanoids) do
-    -- Don't check handymen
-    if class.is(humanoid, Staff) and humanoid.humanoid_class ~= "Handyman" and humanoid:isIdle() then
-      self.world.dispatcher:answerCall(humanoid)
-    end
-  end
 end
```
Comment (lewri) [inline CorsixTH/Lua/room.lua:205]: I still like he idea of having an immediate find work at the end of the consult. Is there a specific consequence if we left this in with the new code?

I suppose the worst of it is that the staff member takes a day to find new work.

File: CorsixTH/Lua/hospitals/player_hospital.lua [hunk 2]
```diff
@@ -481,6 +481,12 @@ function PlayerHospital:onEndDay()
     end
   end
 
+  for _, staff in ipairs(self.staff) do
+    if staff:isIdle() then
+      self.world.dispatcher:answerCall(staff)
+    end
+  end
+
```
Comment (lewri) [inline CorsixTH/Lua/hospitals/player_hospital.lua:489]: This looks like it is preventing handymen from responding to calls -- I'm guessing they're never considered idle.

I have checked with latest master and this bug isn't present there.

**Review by lewri — CHANGES_REQUESTED** [review]
Handyman issue needs addressing

File: CorsixTH/Lua/room.lua (hunk 1 above)
Comment (lewri) [reply CorsixTH/Lua/room.lua:205]: On reflection I think I prefer the balance you have chosen, so happy to discuss my above comment.

Comment (mugmuggy) [reply CorsixTH/Lua/room.lua:205]: I did toss up leaving it in as well, hence leaving it more as a proposal. The original has decisions and logic processed on part day ticks. I assume so some logic doesn't run every tick but also some more frequently than once per day. This probably sits in one of those in the original.

Comment (lewri) [reply CorsixTH/Lua/room.lua:205]: Actually doesn't this function only get called from GP Office?

**Comment by lewri** [comment]
I would like to see this one make the next release, as it does offer quite a marked improvement to finding work.

File: CorsixTH/Lua/room.lua (hunk 1 above)
Comment (lewri) [reply CorsixTH/Lua/room.lua:205]: As per above. Only GP Office used this function. Maybe that was part of the problem too.

**Comment by lewri** [comment]
> The fix has had some funky behaviour in scenarios where a Dr calls to the room, patient leaves for toilet, before call is completed, then the staff member leaves the room and heads to the next room, where the same thing occurs and ended up returning to the same first room.

Is this significant to occur; or would it have a significant impact on gameplay if it happened?
Also any blocking factor regarding RFC? I'm happy with this as is.

File: CorsixTH/Lua/hospitals/player_hospital.lua [hunk 3]
```diff
@@ -510,6 +510,12 @@ function PlayerHospital:onEndDay()
     end
   end
 
+  for _, staff in ipairs(self.staff) do
+    if staff:isIdle() then
+      self.world.dispatcher:answerCall(staff)
+    end
+  end
```
Comment (lewri) [inline CorsixTH/Lua/hospitals/player_hospital.lua:517]: On reinspecting some code, we do use idle a fair bit for some actions as a wait (I found vaccinate and multi-use object). Would these likely get misinterpreted by this code?

Comment (Alberth289346) [reply CorsixTH/Lua/hospitals/player_hospital.lua:517]: Just judging by the question, it seems to me that `isIdle` is ambiguous. So one step is to decide yes or no on your question and then document it with `isIdle`, possibly also improving the name of the function to better match its use.

Also, you may want to split its use between 2 or more functions with different names, so it becomes easier to get the right function. To assist the programmer, it's likely a good idea to mention the related functions in lua doc and/or put them close together, to improve the chance the right function gets found.

As for the functionality, in the calls dispatcher you added `not staff:getRoom()` as condition, which apparently means "a wandering staff member". While I'd prefer an explicit function for that notion, eg `hasNoWork` or so, that check may possibly be good here?

Comment (Alberth289346) [reply CorsixTH/Lua/hospitals/player_hospital.lua:517]: If you add a new function for the latter, please also add a link to that in the lua doc of `getRoom` to avoid further spreading of the `getRoom` function for this purpose.

Another measure that can be done is to make the `getRoom` private, although that has much larger consequences (it should be called with `self` only), not sure if that is feasible.

Comment (lewri) [reply CorsixTH/Lua/hospitals/player_hospital.lua:517]: `isIdle` is actually quite a hefty function to determine a true idle state now that I got round to reading it. It is definitely much more than the mere `IdleAction` I thought it was. It's documented inside nicely enough in the function, not for doc though.

**Review by lewri — APPROVED** [review]
@mugmuggy I finally got round to testing this. I'm happy enough with this as is to suggest merge. If you're able to sanity check the patch still looks compatible let me know and will schedule to merge :)

NB: A different issue but later on, these calls should probably be able to finish use on a desk early (e.g. Dr and Nurse will continue through a use desk action even though they picked up a call).

**Comment by ARGAMX** [comment]
I'd like to merge this.

I found another issue related to this problem - "Wandering Doctor Not Answering Calls".
But this PR resolves the problem.

File: CorsixTH/Lua/room.lua (hunk 1 above)
Comment (lewri) [reply CorsixTH/Lua/room.lua:219]: Actually those comments were wrong. All rooms called this.

**Comment by lewri** [comment]
I'm tempted to keep the existing workfinding function for rooms ontop of this new function. I can't remember now if in TH staff responded immediately to calls after a patient was dealt with; or if there was a wait cycle.

**Comment by lewri** [comment]
There is another glitch in this change. If the patient is about to enter (pops from queue) and the day changes, the staff member will look for work and answer a new call.

**Comment by lewri** [comment]
Changes:
- Refactored two early returns in `staff:isIdle`
- Refactored the room checks for `staff:isIdle` into its own function in `Room:isRoomInDemand`
- Adds additional checks to said new function to ascertain if a room is staff member is truly no longer required in room

File: CorsixTH/Lua/room.lua [hunk 4]
```diff
@@ -722,6 +722,20 @@ function Room:roomFinished()
   self:calculateHappinessFactor()
 end
 
+--! Check if a room is actively required by patients
+--! A room is deemed in demand should any patient be in a state of using, or
+--! wanting to use the room.
+--!return (boolean) true if the room is currently needed
+function Room:isRoomInDemand()
+  local door = self.door
+  if self:getPatientCount() > 0 and not self:getPatient():isLeaving() then
```
Comment (TheCycoONE) [inline CorsixTH/Lua/room.lua:731]: I think this is wrong for the ward if patient-centered > 1.

Comment (lewri) [reply CorsixTH/Lua/room.lua:731]: Good point. Likely this was broken before. Will also check the changes that let the nurse leave ward before fixing but I don't think they included being able to find new work.

Comment (Alberth289346) [reply CorsixTH/Lua/room.lua:731]: I closed this by accident

**Comment by lewri** [comment]
Added handling for ward. I think this is done now.

**Comment by lewri** [comment]
Okay, ready.

File: CorsixTH/Lua/rooms/gp.lua [hunk 5]
```diff
@@ -161,8 +161,6 @@ function GPRoom:dealtWithPatient(patient)
   if self.staff_member then
     self:setStaffMembersAttribute("dealing_with_patient", false)
   end
-  -- Maybe the staff member can go somewhere else
-  self:findWorkForStaff()
```
Comment (ARGAMX) [inline CorsixTH/Lua/rooms/gp.lua:165]: This was annoying call. 
I like we are removing it from here. 👍 
Consultants are constantly leaving out of GPs because of this.
This is a significant change making me want this PR. 👍

File: CorsixTH/Lua/room.lua [hunk 6]
```diff
@@ -736,6 +738,24 @@ function Room:roomFinished()
...
 
+--! Check if a room is actively required by patients
+--! A room is deemed in demand should any patient be in a state of using, or
+--! wanting to use the room.
+--!return (boolean) true if the room is currently needed
+function Room:isRoomInDemand()
+  local door = self.door
+
+  if self:getPatientCount() > 0 then
+    -- All patients must be leaving who are inside the room
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/room.lua:749]: The comment on this line technically is outlining the process based on the function comment `Check if a room is actively required by patients`. You got me scratching my head over this one, probably because it's clear to me but seemingly not clear enough to someone else (nobody is being asked to leave). 

Your suggestion feels a bit bloated for what the code block it refers to is.

Alternatives:
`If a patient is still using a room, then it is still required`. 
`A room is still needed if a patient is using it`.

Other form of comment alternatives I've seen before in this code
`If a patient is still using the room, no need to check any further`.
`Maybe a patient is using the room right now?` <-- I probably prefer this one

File: CorsixTH/Lua/room.lua [hunk 7]
```diff
@@ -736,6 +738,24 @@ function Room:roomFinished()
...
+    for _, patient in ipairs(self:getPatients()) do
+      if not patient:isLeaving() then return true end
+    end
+  end
+  return (door.queue and door.queue:patientSize() > 0) or
+      (door.reserved_for and class.is(door.reserved_for, Patient)) or
+      (door.user and class.is(door.user, Patient) and door.user:getCurrentAction().is_entering)
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/room.lua:756]: Can't think of nice function name (that doesn't sound like it was shoehorned) for it right now or where it should live (room? door? queue? just local?). I'll note it and think about it.

File: CorsixTH/Lua/room.lua (hunk 6 above)
[the remark this answers is not in the document]
Comment (ARGAMX) [reply CorsixTH/Lua/room.lua:749]: > The comment on this line technically is outlining the process based on the function comment `Check if a room is actively required by patients`.
> 

Ah, now I see it.
But it was not obvious, because function comment didn't say anything about leaving the room.

> Alternatives: `If a patient is using the room, then it is still required`. `A room is still needed if a patient is using it`.
> 
> Other form of comment alternatives I've seen before in this code `If a patient is still using the room, no need to check any further`. `Maybe a patient is using the room right now?` <-- I probably prefer this one

Yeah, the both variants is better than current one. 👍

File: CorsixTH/Lua/room.lua (hunk 7 above)
[the remark this answers is not in the document]
Comment (Alberth289346) [reply CorsixTH/Lua/room.lua:756]: `isRoomNeededByPatients` would be my first guess. Since the problem holds for all rooms I am guessing, the `Room` baseclass should be fine.

[the remark this answers is not in the document]
Comment (Alberth289346) [reply CorsixTH/Lua/room.lua:756]: A good comment at line 753 would work too, imho.

[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/room.lua]: Function privatised, it's likely it would be useful in future in other spots

**Review by ARGAMX — APPROVED** [review]
LGTM 

btw 
Force Push sometimes making good things. 

But sometimes I think it brings to lost some context, when you trying to see a diff to commit which is not exist anymore...
