### PR TITLE
Fix Windows home path, add macOS app path to search for game data

### LINKED ISSUE #1857: [Bug] TH Directory finder breaks on first-run setup
#### Describe the issue
Where string ``theme_hospital_install`` is not set (i.e. [[]] ) in config.txt the game will fail to launch. Could be problematic for #1660 
I think this has stemmed from #1687

**Also happens if the folder specified isn't found**
#### Steps to Reproduce
1. Change string above to ``theme_hospital_install = [[]]``

2. Launch

#### Expected Behavior
Don't crash on a nil string.

#### System Information
**CorsixTH Version:** Trunk 153 + Master (current)

(Working in 0.64 release)

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt

```
An error has occurred in CorsixTH:
Lua\app.lua:1250: attempt to concatenate a nil value
stack traceback:
        Lua\app.lua:1250: in method 'checkInstallFolder'
        Lua\app.lua:115: in method 'init'
        CorsixTH.lua:143: in main chunk
        [C]: in ?
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*
image

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #1857 *

**Describe what the proposed change does**
In App:checkInstallFolder
- Use windows variables correctly, without the %
- Use HOMEPATH as Window's HOME
- Add two more paths for macOS based on the app's location, which will be useful when the app is portable

### CODE REVIEW

File: CorsixTH/Lua/app.lua [hunk 1]
```diff
@@ -1263,13 +1263,18 @@ function App:checkInstallFolder()
...
+    local app_parent_dir = debug.getinfo(1).short_src:match("(.*)/Contents/.")
+    local user_dir = os.getenv("HOME") or os.getenv("HOMEPATH") or ""
+    local possible_locations = { user_dir, user_dir .. pathsep ..  "Documents",
       select(1, corsixth.require("config_finder")):match("(.*[/\\])"):sub(1, -2),
+      app_parent_dir, app_parent_dir and app_parent_dir:sub(1,-14),
       "/Applications/Theme Hospital.app/Contents/Resources/game/Theme Hospital.app/" ..
         "Contents/Resources/Theme Hospital.boxer/C.harddisk",
       "/usr/share/games/corsix-th", "/usr/local/share/games/corsix-th",
-      os.getenv("%ProgramFiles%"), os.getenv("%ProgramFiles(x86)%") }
+      os.getenv("ProgramFiles"), os.getenv("ProgramFiles(x86)") }
```
Comment (lewri) [inline CorsixTH/Lua/app.lua:1277]: Thoughts this line could break on a 32 bit Windows system (though iirc we don't support 32-bit now anyway)

Comment (lewri) [reply CorsixTH/Lua/app.lua:1277]: Actually it'd just skip them, ignore this

Comment (TheCycoONE) [reply CorsixTH/Lua/app.lua:1277]: For the record I still build 32bit windows versions. I don't know if anyone uses them...

File: CorsixTH/Lua/app.lua [hunk 2]
```diff
@@ -1263,13 +1263,18 @@ function App:checkInstallFolder()
...
-    -- then macOS GOG bundle, then linux Filesystem Hierarchy Standard, then Windows
-    local possible_locations = { os.getenv( "HOME" ), os.getenv( "HOME" ) .. pathsep ..  "Documents",
+    -- then macOS app and its parent folder, GOG bundle,
+    -- then linux Filesystem Hierarchy Standard, then Windows Program Files
+    -- root_dir is the macOS app base directory named CorsixTH.app
+    local app_parent_dir = debug.getinfo(1).short_src:match("(.*)/Contents/.")
+    local user_dir = os.getenv("HOME") or os.getenv("HOMEPATH") or ""
+    local possible_locations = { user_dir, user_dir .. pathsep ..  "Documents",
       select(1, corsixth.require("config_finder")):match("(.*[/\\])"):sub(1, -2),
+      app_parent_dir, app_parent_dir and app_parent_dir:sub(1,-14),
```
Comment (TheCycoONE) [inline CorsixTH/Lua/app.lua:1273]: 14 is a magic number. Please clarify.

Comment (tobylane) [reply CorsixTH/Lua/app.lua]: Fixed to be more like the comment describes.

**Comment by lewri** [comment]
Looks fine to me

**Comment by TheCycoONE** [comment]
I'm a little surprised people put Theme Hospital inside the CorsixTH app - looks good to me. RDY @tobylane?

**Comment by tobylane** [comment]
It's for distributing the app with the demo files inside. Ready.
