### PR TITLE
Use new drawing layer value for smoke animation

### LINKED ISSUE #3121: [Bug] setTile method exception in smoke animation
### Describe the issue

The `setTile` method in _machine.lua:101_ received 3 arguments when a number is expected as a 4th argument.

```
Lua\entities\machine.lua:101: bad argument #4 to 'setTile' (number expected, got no value)
stack traceback:
        [C]: in method 'setTile'
        Lua\entities\machine.lua:101: in upvalue 'setSmoke'
        Lua\entities\machine.lua:269: in method 'updateSmokeDisplay'
        Lua\entities\machine.lua:150: in method 'machineUsed'
        Lua\humanoid_actions\use_object.lua:391: in local 'timer_function'
        Lua\entity.lua:222: in method 'tick'
        Lua\world.lua:911: in method 'onTick'
        Lua\app.lua:1311: in function <Lua\app.lua:1308>
        (...tail calls...)
        Lua\app.lua:1211: in function <Lua\app.lua:1206>
```

### Steps to Reproduce

1. Plays with broken machines

2. 

3.

### Expected Behaviour

No exception

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions (applies to CorsixTH versions < 0.70.0)

### Save Game

Save game attached to report: Yes/No

### CorsixTH Version

master

### Operating System

*

### Theme Hospital Version

CD

### Gamelog.txt

```yaml

```

### Additional Information

Following the fix about smoke position in PR #3060

From discord server (Lewri & albertfree): 

> Looks like it was just missing the drawing layer:
      local map, x, y = getSmokeTile(self)
      self.smokeInfo:setTile(map, x, y, self:getDrawingLayer())

> Used drawing layers are in utility.lua, lines 221 to 234

[Comment](https://github.com/CorsixTH/CorsixTH/blob/afdec16eb78837ea931f08f30d35d6d9286831a1/CorsixTH/Lua/entity.lua#L361-L370) documentation about `getDrawingLayer` method.

### PR DESCRIPTION
**Pull request by marcassin92**
- *Fixes #3121* 
- Fix z-offset/layer order issue for smoke animation

** What the proposed change does :**
- Create a new dedicated DrawingLayer for smoke animation
  - Use the free value : 6
  - 6 is greater than Entity Drawling layer : smoke is drawn after the machine.
- Use this value in the `setTile` method which expects 4 arguments.

`MachineSmoke` name is used to represent what it is used for. In the machine.lua class`smoke_info` is more than information about smoke but a whole object instance of the animation.

Screenshot from 2025-11-10 14-57-00
Screenshot from 2025-11-10 14-57-16

Screenshot from 2025-11-10 14-58-31
Screenshot from 2025-11-10 14-58-04

Screenshot from 2025-11-10 15-09-57

### CODE REVIEW

File: CorsixTH/Lua/entities/machine.lua [hunk 1]
```diff
@@ -98,7 +98,8 @@ local function setSmoke(self, isSmoking)
       -- Note: Set the location of the smoke to that of the machine
       -- rather than setting the machine to the parent so that the smoke
       -- doesn't get hidden with the machine during use
-      self.smokeInfo:setTile(getSmokeTile(self))
+      local map, x, y = getSmokeTile(self)
+      self.smokeInfo:setTile(map, x, y, self:getSmokeDrawingLayer())
```
Comment (lewri) [inline CorsixTH/Lua/entities/machine.lua:102]: Out of interest, you change the layer to 10 below. Why not just use 10 to start with?
Though I would point out layer 10 means you draw on top of side objects (good); but also floating dollars (not so good).

Though I'm not sure what the `2` does in the lower line.
Edit: The 2 is the variant id of the layer. Smoke is 2

Comment (lewri) [reply CorsixTH/Lua/entities/machine.lua:102]: This is no less different from how it was before anyway.

Comment (marcassin92) [reply CorsixTH/Lua/entities/machine.lua:102]: There was [no change](https://github.com/marcassin92/CorsixTH/blame/fix-smoke-settile-exception/CorsixTH/Lua/entities/machine.lua#L104) of the layer to 10 in this PR or in the [previous](https://github.com/CorsixTH/CorsixTH/pull/3060/files) in the `setLayer` method.
The DrawingLayer used now is the value 6 (greater than entity, lower than dollar sign).
10 to 12 are the 3 level of smoke in the animation configuration, when 2 is the variant id.
These numbers can be observed when opening any smoke animation in the AnimView tool :
image
