### PR TITLE
Fix smoke machine position

### LINKED ISSUE #2872: [Bug] Machines smoke animations position misalign
Image

### Describe the issue

Machine smoke animations is mismatch the actual Machine position.

----

### Expected Behaviour

It should be like in the original Theme Hospital.

----

### Save Game

Inflation smoke animations is mismatch the actual machine position.
v0.69.0
[smoke_misalign_inflation.sav.zip](https://github.com/user-attachments/files/21667736/smoke_misalign_inflation.sav.zip)

Image

Cardio smoke animations is mismatch the actual machine position.
v0.69.0
[smoke_misalign_cardio.sav.zip](https://github.com/user-attachments/files/21667618/smoke_misalign_cardio.sav.zip)

Image

Scanner smoke animations is mismatch the actual machine position.
v0.69.0
[smoke_misalign_hair_restoration.sav.zip](https://github.com/user-attachments/files/21667619/smoke_misalign_hair_restoration.sav.zip)

Image

Hair Restoration smoke animations is mismatch the actual machine position.
v0.69.0
[smoke_misalign_scanner.sav.zip](https://github.com/user-attachments/files/21667629/smoke_misalign_scanner.sav.zip)

Image

Slicer
[room_crashed_doc_in_grab_surg.sav.zip](https://github.com/user-attachments/files/17475797/room_crashed_doc_in_grab_surg.sav.zip)

Image

----

### CorsixTH Version

v.0.68.0, v.0.69.1

### PR DESCRIPTION
**Pull request by marcassin92**
xray mp4

*Fixes #2872*

- Select the best animation for each machines
- Store the smoke animation position into `object.orientations` of each machine definition
- Apply the object translation to the smoke position, and mirror if necessary the animation

Note : 
- The smoke position isn't part of the footprint definition because some machine ( operating_table ) doesn't have a `(0, 0)` tile.
- An improvment could be to store the `x` and `y` offset/translation instead of applying it to `smoke_position` in _entities/object.lua_, and remove the `smoke_position` for every machines.
- Seeing that some animations are not nice from the Original game, maybe we can choose another better ( if possible ) ?
  - 3 machines (operating, blood, hair) use the same `3472` animation, when `3444` and `3452` arn't used.

Question for reviewers : 
- What's the rule about backward compatibility for saves ? should we try as possible to be non breaking ?
=> In the `getSmokeTile` function, `self.object_type` is used to get the smoke position but it can be found in `self.smoke_offset` (stored in the constructor), i did that (temporarily) to make it work for machines without this info ( ex: from an save without this fix ).

### CODE REVIEW

**Comment by marcassin92** [comment]
Here are some 3 layers smoke animation from the Theme Hospital game for ref :
Note :
- Blood machine & Hair remover have strange animations
- small cliping/hiding issue with the operating table
- DNA fixer doesnt have strength, neither repair capabilities in the origin game. I didn't see any smoke after several earthquakes

hair_restorer mp4
blood mp4
cardio mp4
operating mp4
remov mp4
xray mp4
scanner mp4
slicer mp4
inflator mp4
shower mp4
ultrascan mp4
electrolyzer mp4
Jelly Moudler : See [comment](https://github.com/CorsixTH/CorsixTH/pull/3060#issuecomment-3369081490)

**Comment by Alberth289346** [comment]
Looks good !   Thanks for the animations.

**Comment by marcassin92** [comment]
Preview of current fix so far : 
Cliping/hiding issue with : 
- inflator
- hait restorer
- ultrascan
- blood machine

corsixth mp4

File: CorsixTH/Lua/entities/machine.lua [hunk 1]
```diff
@@ -74,24 +76,38 @@ function Machine:isMachine()
...
+--! Return Tile position for smoke animation
+--!return (map, int, int)
+local function getSmokeTile(self)
+  local map, _, _ = self.th:getTile()
+  local x, y = self.tile_x, self.tile_y
+
+  if self.object_type.orientations[self.direction].smoke_position then
+    x = x + self.object_type.orientations[self.direction].smoke_position[1] -- todo : replace by self.smoke_offset
+    y = y + self.object_type.orientations[self.direction].smoke_position[2]
+  end
```
Comment (ARGAMX) [inline CorsixTH/Lua/entities/machine.lua]:
```suggestion
  local smoke_position = self.object_type.orientations[self.direction].smoke_position

  if smoke_position then
    x = x + smoke_position[1] -- todo : replace by self.smoke_offset
    y = y + smoke_position[2]
  end
```

Perhaps it will be nicer this way?

File: CorsixTH/Lua/objects/machines/dna_fixer.lua [hunk 2]
```diff
@@ -30,7 +30,6 @@ object.build_preview_animation = 5070
 object.default_strength = 7
 object.crashed_animation = 3376 -- TODO correct?
 object.show_in_town_map = true
-object.smoke_animation = 3428 -- TODO
```
Comment (ARGAMX) [inline CorsixTH/Lua/objects/machines/dna_fixer.lua]: > remove smoke animation for dna fixer. Add possible anim for jelly

Why we can't use smoke animation for DNA fixer?

Comment (marcassin92) [reply CorsixTH/Lua/objects/machines/dna_fixer.lua]: I'm not able to select the DNA fixer for repair in TH original game, neither it has a smoke animation after several earth quakes. ( That's what i observed, i may be wrong)
Is that a bug from the original Game ? Or is it a choice that this machine never breaks ?

Note :  There are 14 machines for 13 animations

**Comment by ARGAMX** [comment]
Jelly Moudler

Original TH:

[Screen Recording 2025-10-05 at 16.23.44.webm](https://github.com/user-attachments/assets/2cc5d24f-3ed6-4031-94e4-f8359cdd09de)

This PR:

Screenshot 2025-10-05 at 17 01 17

Still slightly offset.

**Comment by ARGAMX** [comment]
Blood Machine

Original TH:

[Screen Recording 2025-10-05 at 16.27.24.webm](https://github.com/user-attachments/assets/8ca2fd88-1101-4ffc-8cd2-27d646ce26ac)

This PR:

Screenshot 2025-10-05 at 16 48 53

Although it looks strange, it is consistent with the original. ✅

Maybe we should try to position it better, not as in original? Is this possible?

**Comment by ARGAMX** [comment]
Hair restorer

same strange as Blood Machine

Original TH:

[Screen Recording 2025-10-05 at 16.33.57.webm](https://github.com/user-attachments/assets/def1f918-d1a9-49a8-bf3e-061c1cf6edc9)

This PR:

Screenshot 2025-10-05 at 17 01 23

Although it looks strange, it is consistent with the original. ✅

I support the idea to make it better ( if possible )

**Comment by ARGAMX** [comment]
> Question for reviewers :
> 
> * What's the rule about backward compatibility for saves ? should we try as possible to be non breaking ?
>   => In the `getSmokeTile` function, `self.object_type` is used to get the smoke position but it can be found in `self.smoke_offset` (stored in the constructor), i did that (temporarily) to make it work for machines without this info ( ex: from an save without this fix ).

Related to backward compatibility: 
I believe that saves from previous version should be loadable and playble.
If machine was smoking in old save, than it should smoke with this PR.
It is OK if smoke will be misaligned in old save with this PR.

**Comment by marcassin92** [comment]
Thanks for the Jelly reference. I was able to set the good animation
image

File: CorsixTH/Lua/objects/machines/dna_fixer.lua (hunk 2 above)
Comment (ARGAMX) [reply CorsixTH/Lua/objects/machines/dna_fixer.lua]: > I'm not able to select the DNA fixer for repair in TH original game, neither it has a smoke animation after several earth quakes. ( That's what i observed, i may be wrong) Is that a bug from the original Game ? Or is it a choice that this machine never breaks ?
> 
> Note : There are 14 machines for 13 animations

Yes, the situation here is confusing.

In original TH DNA fixer don't have any functionality of wear and tear.
Thus In original TH DNA fixer is indestructible.

Is this a bug or why did they do this?..
I think they rushed this disease for some reason and didn't fully implement it. 
And in the end, they didn't have an animation for repairing this machine.
That's probably why they couldn't come up with anything more than making it indestructible. That way, there's no need to repair it, and no animation is needed.

But for some reason, CorsixTH didn't do the same.
I don't know why.
Someone decided to make the machine destructible.
Although there's no animation for it being repaired.
So you might notice in CTH that the handyman simply walks up to DNA fixer, it's instantly repaired, and he leaves.
Looks like a bug. But so far there has been no decision on how to do this better.

So, ever since CorsixTH decided to stand out and not follow original TH in this, we still need smoke for DNA Fixer. It's unclear what type of smoke, but we need it.

File: CorsixTH/Lua/entities/machine.lua (hunk 1 above)
Comment (marcassin92) [reply CorsixTH/Lua/entities/machine.lua]: Totally agree. I was waiting an answer for the saves related question to clear that part.
I applied the change you suggest + removed the TODO comment.

**Comment by lewri** [comment]
Fwiw, I'm not overly fussed if the smoke is a little off from the original. It's only a graphical effect to warn the player and as long as it's appropriately there I think we're good enough.

**Comment by marcassin92** [comment]
Animation 3460 is a little better for both machines (Not sure if the cliping/hiding issue is related to the choice of animation)
 
blood3460 mp4
Screenshot from 2025-10-05 16-33-23
It's just a small change. Tell me if you have preferences.

**Comment by ARGAMX** [comment]
> Animation 3460 is a little better for both machines (Not sure if the cliping/hiding issue is related to the choice of animation)
> 
> [ ](https://private-user-images.githubusercontent.com/1659596/497559310-ea0354bb-e3b5-4a1b-844d-fd1b7046c8e4.gif?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NTk2NzYwMzYsIm5iZiI6MTc1OTY3NTczNiwicGF0aCI6Ii8xNjU5NTk2LzQ5NzU1OTMxMC1lYTAzNTRiYi1lM2I1LTRhMWItODQ0ZC1mZDFiNzA0NmM4ZTQuZ2lmP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MTAwNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTEwMDVUMTQ0ODU2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZDFkZTkzNWEwYjliMDA0YTViZmEwZDNkZTc5NjdlYzllNTk4NjViYWVhNjZkNThiMWJkZGU1Yjg2ZGU4YjBlOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.v8PQTfib1daZU-s9P7JWrrVix4pBT4RzTlk-AMh6Gt0) Screenshot from 2025-10-05 16-33-23 It's just a small change. Tell me if you have preferences.

I like this with Hair restorer 👍

File: CorsixTH/Lua/objects/machines/dna_fixer.lua (hunk 2 above)
Comment (marcassin92) [reply CorsixTH/Lua/objects/machines/dna_fixer.lua]: 3444 seems quite ok but has the cliping issue on one direction ( like a lot of others anim on this machine )
image
Screenshot from 2025-10-05 17-05-05

Comment (ARGAMX) [reply CorsixTH/Lua/objects/machines/dna_fixer.lua]: > 3444 seems quite ok but has the cliping issue on one direction ( like a lot of others anim on this machine ) image Screenshot from 2025-10-05 17-05-05

Nice. I think it fits. 👍

**Comment by ARGAMX** [comment]
> Animation 3460 is a little better for both machines (Not sure if the cliping/hiding issue is related to the choice of animation)
> 
> blood3460 mp4  It's just a small change. Tell me if you have preferences.

This Blood machine smoke is also probably better than how it now. 👍

**Review by ARGAMX — APPROVED** [review]

**Comment by TheCycoONE** [comment]
Thanks @marcassin92!
