### PR TITLE
[RDY] Fullscreen Hotkey updates options button

### LINKED ISSUE #1955: [Bug] Fullscreen hotkey breaks settings toggle
#### Describe the issue
When using Alt+Enter to switch between fullscreen and windowed -- the Fullscreen setting won't update if the settings menu is open. As a result the button starts operating in reverse and the clicked/unclicked doesn't match up anymore.

Found while looking at #1637

#### Steps to Reproduce
1. Open settings menu

2. Press Alt+Enter to toggle fullscreen.

3. Button doesn't update -- pressing the Fullscreen button in settings then causes the behaviour to flip (thinks it is on when it's now in windowed mode)

#### Expected Behavior
Toggle the button correctly.

#### System Information
**CorsixTH Version:** 0.65 beta-2

**Operating System:** Windows 10

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
image

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #1955*

**Describe what the proposed change does**
- When using the fullscreen hotkey, the fullscreen button will now update if the Options menu was option.
- The solution feels a little janky, but happy to accept other ideas.

### CODE REVIEW

File: CorsixTH/Lua/dialogs/resizables/options.lua [hunk 1]
```diff
@@ -292,15 +292,20 @@ function UIOptions:selectResolution(number)
   end
 end
 
-function UIOptions:buttonFullscreen(checked)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/resizables/options.lua:295]: Just to note, ``checked`` was never used as far as I can see in the function.

File: CorsixTH/Lua/ui.lua [hunk 2]
```diff
@@ -720,6 +723,11 @@ function UI:toggleFullscreen()
     -- Save new setting in config
     self.app.config.fullscreen = self.app.fullscreen
     self.app:saveConfig()
+    -- If options window is open, make sure the button updates on hotkey
+    if not from_uioptions and self:getWindow(UIOptions) then
```
Comment (lewri) [inline CorsixTH/Lua/ui.lua:727]: The second param of the if is more a safeguard, but happy to remove it if not needed.

Comment (TheCycoONE) [reply CorsixTH/Lua/ui.lua:727]: This is a bit of a violation again, you shouldn't care where a function was called from generally.

window:updateFSButtonOnHotkey() should be in the appropriate caller instead.
