### PR TITLE
Spaces and newlines in the language files

### LINKED ISSUE #1240: game hang on first level
#### Describe the issue
0.5 works for me. 0.6 game hang on first level. After i built the first general room and employed a new doctor, and place that doctor on the floor, then game hang. tried 0.6c1 and c2, all not works

#### Steps to Reproduce
After i built the first general room and employed a new doctor, and place that doctor on the floor, then game hang. tried 0.60, 0.6c1 and c2, all not works

### PR DESCRIPTION
**Pull request by tobylane**
The combined strings for level introductions were missing spaces between sentences, and the demo and first level missing some new lines.

Fixes #1240.

### CODE REVIEW

File: CorsixTH/Lua/languages/french.lua [hunk 1]
```diff
@@ -1088,11 +1088,11 @@ tooltip.cheats_window = {
 -- Introduction Texts
 introduction_texts = {
   demo =
-    "Bienvenue dans l'hôpital de démonstration !" ..
-    "Malheureusement, la version démo ne contient que ce niveau. Malgré tout, il y a assez à faire ici pour vous occuper un moment !" ..
-    "Vous allez rencontrer différentes maladies qui nécessitent des salles pour les soigner. De temps en temps, des urgences peuvent se produire. Et vous aurez besoin d'une salle de recherche pour trouver des nouvelles salles." ..
-    "Votre but est de gagner 100,000$, de faire monter la valeur de votre hôpital à 70,000$ et d'obtenir une réputation de 700, tout en ayant soigné au moins 75% de vos patients." ..
-    "Veillez à ce que votre réputation ne tombe pas en dessous de 300 et de ne pas tuer plus de 40% de vos patients, ou vous perdrez." ..
+    "Bienvenue dans l'hôpital de démonstration!// " ..
```
Comment (wolfy1339) [inline CorsixTH/Lua/languages/french.lua]: Why are you removing the space before the punctuation here?

Comment (TheCycoONE) [reply CorsixTH/Lua/languages/french.lua]: He's probably unfamiliar with french punctuation and assumed it was a mistake. But yes the French put a space before and after almost all punctuation marks (notably excluding . and ,)

Comment (tobylane) [reply CorsixTH/Lua/languages/french.lua]: TIL, corrected.
