### PR TITLE
Prevent staff grab spamming

### LINKED ISSUE #2632: [Bug] Spamming grab of occupied employe causes unexpected behaviour.
### Describe the issue

Spamming grab of occupied employe causes unexpected behaviour.

For example, after promotion to Consultant while standing up from desk on Doctor details-view press grab button several times causes bugs.

Screenshot 2024-09-24 at 22 09 17

Load '**after**' save and observe how H. WRIGHTLET (Training room) and G. WARBURY (Research room) unexpectedly and for no reason leaving they rooms. 'staff leave rooms setting' is disabled. There is no any calls.

This is the consequence of Spamming grab of occupied employe.

### Steps to Reproduce

Characters:
7 H. WRIGHTLET - **Lector**
21 G. WARBURY - **Researcher**

1. *Load '**before**' save game attached to this ticket* 
2. Observe how **Lector** is teaching **Researcher** in Training room.
3. Soon **Researcher** becoms Consultant.
4. At the speed 1 while **Researcher** standing up from desk, open **Researcher**  Doctor details-view.
5. Press Grab button several times. (if press 1 time then bug not reproduce)
6. **Researcher** will not be grabbed instantly. There some delay as he occupied. Wait until he will finish standing up from desk.
7. Put **Researcher** in Research room.
8. Observe that 'Multiple grabbing bug' happen - you put **Researcher** but he had got grabbed again. Put him in another place in Research room.
9. Set game speed to 4 and Observe how **Lector** unexpectedly and for no reason leaving Training room and **Researcher** unexpectedly and for no reason leaving Research room. 

### Expected Behaviour

1. Spamming grab of occupied employe should not be possible.
2. Doctors should not leaves they rooms unexpectedly and for no reason.

### Save Game

[researcher_leaves_room_unexpectedly_after.sav.zip](https://github.com/user-attachments/files/17119491/researcher_leaves_room_unexpectedly_after.sav.zip)

[researcher_leaves_room_unexpectedly_before.sav.zip](https://github.com/user-attachments/files/17119694/researcher_leaves_room_unexpectedly_before.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

### PR DESCRIPTION
**Pull request by ARGAMX**
*Fixes #2632 #2651*

**Describe what the proposed change does**
- PickupAction can be setNextAction only once.

### CODE REVIEW

**Comment by ARGAMX** [comment]
Fixes #2651

**Comment by TheCycoONE** [comment]
LGTM

File: CorsixTH/Lua/dialogs/staff_dialog.lua [hunk 1]
```diff
@@ -109,7 +109,7 @@ function UIStaff:UIStaff(ui, staff)
       self:addColourPanel(32, 141, 171, 39, 85, 202, 219)  -- Hides Skills
     end
     self:addPanel(307, 106, 226):makeButton(0, 0, 50, 50, 308, self.fireStaff):setTooltip(_S.tooltip.staff_window.sack)
-    self:addPanel(309, 164, 226):makeButton(0, 0, 37, 50, 310, self.placeStaff):setTooltip(_S.tooltip.staff_window.pick_up)
+    self:addPanel(309, 164, 226):makeButton(0, 0, 37, 50, 310, self.pickupStaff):setTooltip(_S.tooltip.staff_window.pick_up)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/staff_dialog.lua:112]: As the button is being amended outside of draw, it may be safe to include an afterload to close the window.

Comment (ARGAMX) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: > As the button is being amended outside of draw, it may be safe to include an afterload to close the window.

this is related to backward compatibility? 
for case to load the game with already drawn window?

Comment (Alberth289346) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: Like I know that :p

The "persistable:foo" comment is used by the save system to identify the function that should get the saved data. Also, instantiated classes are saved, so the method functions work too.

In both cases of course, you get the persisted data. New variables of the function won't exist thus.

Comment (ARGAMX) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: > Yeah the button in memory has a call embedded now pointing to a now nonexistent function.

@lewri I have made experiment:

1. Before that change: Run game. Open doctor menu. Made safe.
2. Closed game. Made this change.
3. Run game. Load save.
4. Pressed grab button on menu which was on screen after game load - nothing happened (button don't work).
5. Gamelog empty. Lua not crashed - game run smoothly.
6. Close/open doctor menu. Then button work ok.

Is that results mean that change is safe and no any backward compatibility additions required?

Comment (lewri) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: You're likely still loading the old code. It's pretty trivial just to tell the game to close the window to be safe.

Comment (lewri) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: Actually ignore that comment. The change you made now no longer runs the risk afaik.

Comment (ARGAMX) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: > You're likely still loading the old code.

If still loading the old code when why grab spamming before change is reproducible and after change grab spamming is not reproducible?

Comment (lewri) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: `Warning: No handler for button click` occurs in the console w/debug if you change function name from what it expects, with the window open at save time. (you can load this save in your test environment to check made in 0.67 [pickup.zip](https://github.com/user-attachments/files/17355465/pickup.zip))

As a result of minimising the error please either:
1. Edit the function `UIStaff:placeStaff()` without changing function name. This doesn't need an afterload. ***or***
2. Add an afterload:
```lua
function UIStaff:afterLoad(old, new)
  if old < xxx then
    self:close()
  end
  Window.afterLoad(self, old, new)
end
```

Comment (ARGAMX) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: > 2. Add an afterload:
> 
> ```lua
>   if old < xxx then
> ```

Thanks, now I got it. 👍
What should be posted instead of 'xxx'?

Comment (lewri) [reply CorsixTH/Lua/dialogs/staff_dialog.lua:112]: `195` for now, bumping app.lua too to 195.

Depending on #2639 it may go to `205`.

File: CorsixTH/Lua/dialogs/staff_dialog.lua [hunk 2]
```diff
@@ -30,6 +30,13 @@ class "UIStaff" (Window)
 ---@type UIStaff
 local UIStaff = _G["UIStaff"]
 
+function UIStaff:afterLoad(old, new)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/staff_dialog.lua:33]: I can happily move this for you, but we'll prefer this to float to the bottom of the file.

File: CorsixTH/Lua/dialogs/staff_dialog.lua [hunk 3]
```diff
@@ -30,6 +30,13 @@ class "UIStaff" (Window)
...
+  if old < 196 then
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/staff_dialog.lua:34]: NB: awaiting version number confirm.

**Review by lewri — COMMENTED** [review]
`app.lua` will need `SAVEGAME_VERSION` changing too with comment updated. `196` can remove placeholder for now.

**Comment by TheCycoONE** [comment]
It bothers me very mildly that pickup might accept something other than a PickupAction, Anyone else think it would be cleaner if the method took an optional window instead and created PickupAction itself?

**Comment by lewri** [comment]
> It bothers me very mildly that pickup might accept something other than a PickupAction, Anyone else think it would be cleaner if the method took an optional window instead and created PickupAction itself?

Yeah, letting `Staff:setPickup` create the action would be cleaner. Otherwise you'd have to `assert` that the passed action was a pickup action.

**Comment by ARGAMX** [comment]
> It bothers me very mildly that pickup might accept something other than a PickupAction, Anyone else think it would be cleaner if the method took an optional window instead and created PickupAction itself?

Wisely. 

Improved.

**Review by lewri — COMMENTED** [review]
Code logically fine to me. Your savegame version / old numbers just need to changing to `205` now that we applied the hotfix buffer.

**Comment by ARGAMX** [comment]
> Code logically fine to me. Your savegame version / old numbers just need to changing to `205` now that we applied the hotfix buffer.

`205` is will be the last shift or possible another?
I mean do I need to bump it to `205` or it will be bumpet to required value on merge by merger?

**Comment by ARGAMX** [comment]
Bump to `205` done.

File: CorsixTH/Lua/entities/humanoids/staff.lua [hunk 4]
```diff
@@ -440,6 +439,18 @@ function Staff:goToStaffRoom()
   end
 end
 
+-- Function to set pickup action on staff. Pickup action can be deferred.
+function Staff:setPickup(ui, windowToClose)
+  if not self.pickup then -- check is we already added pickup Action in actions queue
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/staff.lua:444]: Typo in comment. `is` => `if`?

Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoids/staff.lua]: > Typo in comment. `is` => `if`?

Thanks. Fixed.

File: CorsixTH/Lua/entities/humanoids/staff.lua [hunk 5]
```diff
@@ -440,6 +439,18 @@ function Staff:goToStaffRoom()
...
+function Staff:setPickup(ui, windowToClose)
+  if not self.pickup then -- check if we already added pickup Action in actions queue
+    self.pickup = true
+    local pickupAction = PickupAction(ui)
+    if windowToClose then -- if we want to close some window after pickup happened
+      pickupAction = pickupAction:setTodoClose(windowToClose)
+    end
+    self:setNextAction(pickupAction, true)
+  end
+end
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/staff.lua:452]: To summarise a length discord discussion with @Alberth289346 `windowToClose` and `pickupAction` should be converted to snake case instead.
Will also make sure the Wiki is updated to be clearer.

Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoids/staff.lua]: Done  👌
