### PR TITLE
Right click in build mode remove window

### LINKED ISSUE #2682: [Bug] Can't remove doors or windows in build mode
### Describe the issue

In the original TH, you could remove windows and doors when in build mode by right clicking on them. On corsix, you must "cancel" the building and start over.

### Steps to Reproduce

1.  make a room, place a door and a window
2. while still in build mode try to erase them with right click

### Expected Behaviour

Right click should remove windows or doors while in build mode.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: No

### CorsixTH Version

0.68

### Operating System

Windows 10 x64

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
No gamelog generated for me on 0.68
```

### Additional Information

No gamelog generated for me on 0.68

### PR DESCRIPTION
**Pull request by marcassin92**
*Fixes #2682*

**Changes :**
- In "Window" phase, the right click remove the window from the wall and reset to the default transparent wall.
- Move right and left click logic in dedicated method.

Note : 
As the cursor is above a wall in "window" phase, after right click, the window is still there because the `blueprint_window` is still valid and we're in build mode. Move the cursor outside this cell to see the window disappear. 
Should we hide the blueprint/window in this case ?

Wall selection to delete is the same as wall construction (Test: Try delete a window with the cursor in the room corner)

### CODE REVIEW

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 1]
```diff
@@ -1072,32 +1072,93 @@ function UIEditRoom:draw(canvas, ...)
...
+      elseif wall_dir == "east" then
+        wall_x = cellx + 1
+      end
+
+      local anim = self.blueprint_wall_anims[wall_x][wall_y]
+      if anim then
+        -- reset tile to basic floor/wall
+        map:setCell(cellx, celly, 4, 24)
+        anim:setAnimation(self.anims, 120, direction_flag)
+        anim:setTag(nil)
```
Comment (Matroftt) [inline CorsixTH/Lua/dialogs/edit_room.lua]:
```suggestion
        anim:setTag(nil)
        self.ui:playSound("de_build.wav")
```
Dont forget to play sfx

**Review by Matroftt — CHANGES_REQUESTED** [review]

**Comment by lewri** [comment]
> Note :
> As the cursor is above a wall in "window" phase, after right click, the window is still there because the `blueprint_window` is still valid and we're in build mode. Move the cursor outside this cell to see the window disappear.
> Should we hide the blueprint/window in this case ?

I imagine there will be some way to update (or at least give the illusion of) the blueprint wall on click. Though I haven't touched blueprint code really.

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 2]
```diff
@@ -1072,32 +1072,94 @@ function UIEditRoom:draw(canvas, ...)
...
+    end
+  elseif self.phase == "windows" then
+    self:placeWindowBlueprint()
+  end
+end
+
+-- Remove window
+function UIEditRoom:onRightButtonDown(button, x, y)
+  if self.phase == "windows" then
+    local cellx, celly, wall_dir = self:screenToWall(self.x + x, self.y + y)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua]: `cell_x` and `cell_y`

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 3]
```diff
@@ -1072,32 +1072,94 @@ function UIEditRoom:draw(canvas, ...)
...
+    else
+      self.ui:tutorialStep(3, 9, 10)
+    end
+  elseif self.phase == "windows" then
+    self:placeWindowBlueprint()
+  end
+end
+
+-- Remove window
+function UIEditRoom:onRightButtonDown(button, x, y)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua]: Why not call the function what it does? `function UIEditRoom:removeWindow(x, y)` (the button parameter is unused).

Comment (lewri) [reply CorsixTH/Lua/dialogs/edit_room.lua]: In tandem to this, if you moved the phase check inside the onMouseDown function you have a nicely defined function above.

e.g.

```lua
elseif button == "right" then
  if self.phase == "windows" then
    self:removeWindow()
  end
end
```

Ideally a good refactor is also thinking if the left button would benefit from the same treatment. But it is out of scope of this PR it was just simply a code move.

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 4]
```diff
@@ -1072,32 +1072,94 @@ function UIEditRoom:draw(canvas, ...)
...
+
+local window_floor_blueprint_markers = {
+  north = 33,
+  east = 34,
+  south = 35,
+  west = 36,
+}
+
+
+function UIEditRoom:onLeftButtonDown(button, x, y)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua]: Button parameter is unused

**Review by lewri — COMMENTED** [review]
Good stuff

File: CorsixTH/Lua/dialogs/edit_room.lua (hunk 3 above)
Comment (marcassin92) [reply CorsixTH/Lua/dialogs/edit_room.lua]: > Why not call the function what it does

In my first implementation removing the door was possible too so that made sense. Now as it's only for windows, it make sense to put a more describing name.
I choosed something more verbose, as `removeWindow` is already defined in a grand parent `Window` class.

**Comment by ARGAMX** [comment]
> As the cursor is above a wall in "window" phase, after right click, the window is still there because the `blueprint_window` is still valid and we're in build mode. Move the cursor outside this cell to see the window disappear.
> Should we hide the blueprint/window in this case ?

In the original Theme Hospital the window is visually still there after right click.
Based on this, I would recommend to stick the same behavior. 👍
So I think we should not hide the blueprint/window in this case.

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 5]
```diff
@@ -1072,31 +1072,92 @@ function UIEditRoom:draw(canvas, ...)
...
+      self:confirm(true)
+    else
+      self.ui:tutorialStep(3, 9, 10)
+    end
+  elseif self.phase == "windows" then
+    self:placeWindowBlueprint()
+  end
+end
+
+-- Remove window
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua]: Sorry, I should've helped with doc on this one.

```suggestion
--! Attempt to remove a window placed on the room blueprints
--!param x co-ordinate of target tile
--!param y co-ordinate of target tile
```

**Comment by TheCycoONE** [comment]
Thanks @marcassin92
