### PR TITLE
General Diagnosis. Crash fixes on doctor change

### LINKED ISSUE #1328: [Bug] General Diagnosis. Moving doctor during room use led to broken room and patient
#### Describe the issue
I picked up a doctor in general diagnosis while a patient was about to change back into their normal clothes. The patient instead left the room (now dressed normally) and headed to their next room psychiatry. However, the general diagnosis room was not updated, so the patients clothes were also occupying the screen. Once the patient went to their next room, they attempted to change in that room, and froze up. This left the general diagnosis room unusable as it was partially used, and the psychiatry room unused, as there was a patient using it who would not progress further.

Video of the bug occuring:

https://www.twitch.tv/videos/217623614

#### Steps to Reproduce
1. Right click a doctor in a general diagnosis room to pick him up.
2. Move him out of the room as the patient changes back.

#### Save Game

[1328_2 Moving doctor during room use led to broken room and patient.sav.zip](https://github.com/user-attachments/files/19947317/1328_2.Moving.doctor.during.room.use.led.to.broken.room.and.patient.sav.zip)

#### Expected Behavior
Either:

The patient continues to change back and leaves the room with the diagnosis complete

or:

The patient changes back and leaves the room with the diagnosis progress lost.

After this, the patient resumes as normal, and the room is available to use again.

#### System Information
**CorsixTH Version:** *0.61*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt
*For information about where to find gamelog.txt see:
https://github.com/CorsixTH/CorsixTH/wiki/Frequently-Asked-Questions#where-do-i-find-the-configuration-or-the-gamelog-file*
```
Created game with savegame version 122.
Error in timer handler: 
C:\Program Files\CorsixTH\Lua\rooms\general_diag.lua:59: attempt to index a nil value (local 'staff')
stack traceback:
	C:\Program Files\CorsixTH\Lua\rooms\general_diag.lua:59: in local 'after_use'
	...ogram Files\CorsixTH\Lua\humanoid_actions\use_screen.lua:46: in function <...ogram Files\CorsixTH\Lua\humanoid_actions\use_screen.lua:38>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\entity.lua:216: in method 'tick'
	C:\Program Files\CorsixTH\Lua\world.lua:1051: in method 'onTick'
	C:\Program Files\CorsixTH\Lua\app.lua:1008: in function <C:\Program Files\CorsixTH\Lua\app.lua:1005>
	(...tail calls...)
	C:\Program Files\CorsixTH\Lua\app.lua:909: in function <C:\Program Files\CorsixTH\Lua\app.lua:904>

```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

### PR DESCRIPTION
**Pull request by ARGAMX**
*Fixes #1328*

**Describe what the proposed change does**
- Fix. In `general_diag.lua`. Reworked `GeneralDiagRoom:commandEnteringPatient`. The sequence of events in the room has been made more sustainable to attempts to grab the doctor at inappropriate moments or to kick the patient out at inappropriate moments. Added comment to actions.
- Fix. In `humanoid.lua`. Improvements for `uninterruptible` actions logic. (was necessary to this General Diagnosis fix)
- Fix. In `room.lua`. Previously In `onHumanoidEnter` new staff was only able to replace old one only if `not old_staff_in_room.dealing_with_patient`. But `dealing_with_patient` was not really indicating dealing with patient, in fact only indicating that patient in the room. So I changed it to `not old_staff_in_room.dealing_with_patient and staff_in_room:isMeandering()`. Because while the patient is walking towards the screen `dealing_with_patient` is already true, but doctor is not occupied by the patient and can be grabbed. 
- Refactor. In `room.lua`. In `onHumanoidEnter` `humanoid` (as staff) renamed to `staff_entered`, `staff_member` renamed to `staff_in_room`, `humanoid` (as patient) renamed to `patient_entered`.

### CODE REVIEW

File: CorsixTH/Lua/entities/humanoids/staff.lua [hunk 1]
```diff
@@ -509,6 +509,16 @@ function Staff:adviseWrongPersonForThisRoom()
   end
 end
 
+-- Function to decide if staff currently Meander
+function Staff:isMeandering()
+  for _, action in ipairs(self.action_queue) do
+    if action.name == "meander" then
+      return true
```
Comment (ARGAMX) [inline CorsixTH/Lua/entities/humanoids/staff.lua:516]: Honestly seems iterating through whole `action_queue` don't looks like a good solution here. But I didn't found any other working way.

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 2]
```diff
@@ -52,47 +52,81 @@ end
...
-end
+  -- Patient undress for procedure
+  local undress = UseScreenAction(screen):setAfterUse(after_use_screen1)
+  patient:queueAction(undress)
 
-function GeneralDiagRoom:onHumanoidLeave(humanoid)
-  if self.staff_member == humanoid then
-    self.staff_member = nil
-  end
-  Room.onHumanoidLeave(self, humanoid)
```
Comment (ARGAMX) [inline CorsixTH/Lua/rooms/general_diag.lua:95]: This function just do the same as parent function do. So I don't see any meaning in this inheritor function.

File: CorsixTH/Lua/room.lua [hunk 3]
```diff
@@ -356,42 +356,46 @@ function Room:onHumanoidEnter(humanoid)
...
+    if not self:staffFitsInRoom(staff_entered) then
+      if self:getStaffMember() and self:staffMeetsRoomRequirements(staff_entered) then
+        local staff_in_room = self:getStaffMember()
+        self.humanoids[staff_entered] = true
+        if staff_in_room.profile.is_researcher and self.room_info.id == "research" then
+          self.hospital:giveAdvice(researcher_desks)
+        end
+        if staff_in_room.humanoid_class == "Nurse" and self.room_info.id == "ward" then
+          self.hospital:giveAdvice(nurse_desks)
+        end
```
Comment (ARGAMX) [inline CorsixTH/Lua/room.lua:369]: No changes made here. Only indentation fixed.

File: CorsixTH/Lua/entities/humanoid.lua [hunk 4]
```diff
@@ -491,7 +491,8 @@ function Humanoid:startAction()
   -- Call the action start handler
   TheApp.humanoid_actions[action.name](action, self)
 
-  if action == self.action_queue[1] and action.todo_interrupt then
+  if action == self.action_queue[1] and action.todo_interrupt and not action.uninterruptible then
+    -- Interrupt an action because it has been marked as to be interrupted
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/humanoid.lua:495]:
```suggestion
    -- Interrupt the current action.
```
The first action in an action queue is currently being done, so it's "the" action rather than "an (any/some) action".

Inside the `if` the decision is already made, so why it's here isn't relevant anymore. Just state what is going to happen now.

The reason for not stating why it's here: All code is changing all the time, so eventually the "why" explanation becomes incomplete or even incorrect.
In other words, avoid duplicating information.

File: CorsixTH/Lua/room.lua [hunk 5]
```diff
@@ -492,16 +497,16 @@ end
 
 --! When a valid member of staff enters the room this function is called.
 -- Can be extended in derived classes.
---!param humanoid The staff in question
---!param already_initialized If true, this means that the staff has already got order
+--!param staff (object) The staff in question
```
Comment (Alberth289346) [inline CorsixTH/Lua/room.lua:500]:
```suggestion
--!param staff (Staff) The staff in question
```
There is a `Staff` base class.

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 6]
```diff
@@ -52,47 +52,81 @@ end
...
+    local staff = self:getStaffMember()
+    if staff then
+      local trolley, cx, cy = self.world:findObjectNear(patient, "crash_trolley")
+
+      -- Doctor walk to trolley
+      local ox, oy = trolley:getSecondaryUsageTile()
+      local staff_prepare = WalkAction(ox, oy)
+        :setMustHappen(true)
+        :disableTruncate()
+        :setUninterruptable(true)
```
Comment (Alberth289346) [inline CorsixTH/Lua/rooms/general_diag.lua:69]: You may want to double-indent these kind of lines, They are continuations of line 66.

File: CorsixTH/Lua/room.lua (hunk 3 above)
Comment (Alberth289346) [reply CorsixTH/Lua/room.lua:369]: You forgot about the added local rename at line 359 (and another one further down) and the added comments.

Have a look yourself. Open the "Changes" tab, and select "hide white space changes". You'll find almost all lines have changed.

Comment (Alberth289346) [reply CorsixTH/Lua/room.lua:369]: What you probably meant is "no semantical changes". That means "code behaves the same as before".

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 2 above)
Comment (Alberth289346) [reply CorsixTH/Lua/rooms/general_diag.lua:95]: Euhm? The one in `room.lua` is about 80 lines long rather than 5 lines.
Line 576 to 656 in my copy of the room.lua file

Comment (Alberth289346) [reply CorsixTH/Lua/rooms/general_diag.lua:95]: Oh, my bad. It does the same as you said. Sorry for the noise.

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 7]
```diff
@@ -52,47 +52,81 @@ end
...
-    patient:walkTo(cx, cy, true)
-
-    local after_use_trolley = --[[persistable:general_diag_trolley_after_use]] function()
-      if #staff.action_queue == 1 then
+    local after_use_screen2 = function() end
+    local staff = self:getStaffMember()
+    if staff then
+      local trolley, cx, cy = self.world:findObjectNear(patient, "crash_trolley")
+
+      -- Doctor walk to trolley
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:64]: `walks`

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 8]
```diff
@@ -52,47 +52,81 @@ end
 
 function GeneralDiagRoom:commandEnteringPatient(patient)
   local screen, sx, sy = self.world:findObjectNear(patient, "screen")
+  -- Patient walk to screen
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:55]: If you want to leave the singular word form in; then really a single line block comment would be nice here to denote they're action constructors.

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 9]
```diff
@@ -52,47 +52,81 @@ end
...
+
+      -- Doctor walk to trolley
+      local ox, oy = trolley:getSecondaryUsageTile()
+      local staff_prepare = WalkAction(ox, oy)
+        :setMustHappen(true)
+        :disableTruncate()
+        :setUninterruptable(true)
+      staff:setNextAction(staff_prepare)
+
+      -- Doctor wait patient near trolley
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:72]: `waits for`

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 10]
```diff
@@ -52,47 +52,81 @@ end
...
+      local staff_idle = IdleAction()
+        :setMustHappen(true)
+        :disableTruncate()
+        :setUninterruptable(true)
+      staff:queueAction(staff_idle)
+
+      -- Patient walk to trolley
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:79]: `walks`

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 11]
```diff
@@ -52,47 +52,81 @@ end
...
-    end
-
-    patient:queueAction(MultiUseObjectAction(trolley, staff):setMustHappen(false)
-        :setProlongedUsage(false):setAfterUse(after_use_trolley))
-    patient:queueAction(WalkAction(sx, sy):setIsLeaving(true):setMustHappen(false):disableTruncate())
 
-    local after_use_screen2 = --[[persistable:general_diag_screen_after_use2]] function()
-      if #patient.action_queue == 1 then
-        self:dealtWithPatient(patient)
+      -- Patient use trolley
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:91]: The doctor strictly speaking uses the trolley. It's just some silly quirk it gets applied to the patient.

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 12]
```diff
@@ -52,47 +52,81 @@ end
...
+      local use_trolley = MultiUseObjectAction(trolley, staff)
+        :disableTruncate()
+        :setMustHappen(true)
+        :setProlongedUsage(false)
+        :setAfterUse(after_use_trolley)
+      patient:queueAction(use_trolley)
+
+      -- Patient walk back to screen
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:99]: `walks`

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 13]
```diff
@@ -52,47 +52,81 @@ end
...
       end
+    else
+      -- Patient didn't get served
+      self:makeHumanoidLeave(patient)
+      patient:queueAction(SeekRoomAction(self.room_info.id))
     end
 
-    patient:queueAction(UseScreenAction(screen):setIsLeaving(true):setMustHappen(true)
-        :setAfterUse(after_use_screen2))
+    -- Patient dress back to his clothes
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:117]: `their` -- we have more than just male patients in the hospital :)

Also `dresses`

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 14]
```diff
@@ -52,47 +52,81 @@ end
...
+      :setIsLeaving(true)
+      :setMustHappen(true)
+      :setAfterUse(after_use_screen2)
+    patient:queueAction(dress_back)
   end
 
-  patient:queueAction(UseScreenAction(screen):setAfterUse(after_use_screen1))
-  return Room.commandEnteringPatient(self, patient)
-end
+  -- Patient undress for procedure
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:125]: `undresses`

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 15]
```diff
@@ -52,47 +52,81 @@ end
...
+      staff:queueAction(staff_idle)
+
+      -- Patient walk to trolley
+      local go_to_trolley = WalkAction(cx, cy)
+        :setMustHappen(true)
+        :disableTruncate()
+      patient:queueAction(go_to_trolley)
+
+      local after_use_trolley = --[[persistable:general_diag_trolley_after_use]] function()
+        -- Doctor finish wait near trolley
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:86]: ? I think for this one you could just say `-- Doctor and patient ready for begin procedure`

File: CorsixTH/Lua/room.lua [hunk 16]
```diff
@@ -402,22 +406,23 @@ function Room:onHumanoidEnter(humanoid)
     -- An infect patient's disease may have changed so they might have
     -- been sent to an incorrect diagnosis room, they should leave and go
     -- back to the gp for redirection
-    if (humanoid.infected) and not humanoid.diagnosed and
-        not self:isDiagnosisRoomForPatient(humanoid) then
-      humanoid:queueAction(self:createLeaveAction())
-      humanoid.needs_redirecting = true
-      humanoid:queueAction(SeekRoomAction("gp"))
+    local patient_entered = humanoid
+    if (patient_entered.infected) and not patient_entered.diagnosed and
```
Comment (lewri) [inline CorsixTH/Lua/room.lua:410]: Not you, but those brackets can go.

**Review by lewri — COMMENTED** [review]
Most of those grammar comments only apply if you don't do the constructor code comment instead. e.g. `--[[ Construct room usage cycle ]]`

File: CorsixTH/Lua/room.lua (hunk 3 above)
Comment (ARGAMX) [reply CorsixTH/Lua/room.lua:369]: Actually, yes. 
I forgot about it at a certain point.

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 15 above)
Comment (lewri) [reply CorsixTH/Lua/rooms/general_diag.lua:86]: Ahem... *ready to begin

File: CorsixTH/Lua/entities/humanoid.lua (hunk 4 above)
Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoid.lua:495]: > The first action in an action queue is currently being done, so it's "the" action rather than "an (any/some) action".
> 
> Inside the `if` the decision is already made, so why it's here isn't relevant anymore. Just state what is going to happen now.
> 
> The reason for not stating why it's here: All code is changing all the time, so eventually the "why" explanation becomes incomplete or even incorrect. In other words, avoid duplicating information.

I didn't understand and didn't know that `startAction()` would delete actions out of the queue for some reason.
It's not obvious.
It was a bit of a surprise that `startAction()` does this.
This is exactly what I wanted to make more transparent in the code.

Perhaps I shouldn't have written this inside `if`, and it should be outside `if`.
And perhaps it should be written in the description of the function itself.

In general, the point is not only to explain what happens inside `if`.
But to explain why `startAction()` does this.

Perhaps this needs to be refactered. 
But it would be better to at least simply explain why this is so.

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 15 above)
Comment (ARGAMX) [reply CorsixTH/Lua/rooms/general_diag.lua:86]: > ? I think for this one you could just say `-- Doctor and patient ready for begin procedure`

The thing is that this is fires after trolley used (this is why it is called `after_use_trolley`).

For some reason for General Diagnosis `MultiUseObjectAction` in patient action queue, not in staff queue. (why?...)
So to occupy Doctor he is getting `IdleAction()` at line 77.

And here is his `IdleAction()` must finish.
And this is what the commentary is trying to say...

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 6 above)
Comment (ARGAMX) [reply CorsixTH/Lua/rooms/general_diag.lua:69]: > You may want to double-indent these kind of lines, They are continuations of line 66.

If it will not give me any error or warning, I would like.

File: CorsixTH/Lua/entities/humanoids/staff.lua (hunk 1 above)
Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoids/staff.lua:516]: > A quick look at the meander code indicates the meander might be second in the queue once it starts. You could run some observations; the first parameter in the for loop will be the index; so for testing you could do `for idx, action in ipairs(self.action_queue) do` then print the index of the meander.
> 
> If meander always has the same index (or two indexes at most) then you only ever need check those indexes.

Thank you, yes, it helped.
For some reason I checked it before PR (second in the queue) and it didn't work for me.
So I had to go through the whole queue.

But now I have rechecked again and everything worked.
Apparently I made a mistake when I checked the first time

File: CorsixTH/Lua/room.lua [hunk 17]
```diff
@@ -356,42 +356,46 @@ function Room:onHumanoidEnter(humanoid)
...
+      if self:getStaffMember() and self:staffMeetsRoomRequirements(staff_entered) then
+        local staff_in_room = self:getStaffMember()
+        self.humanoids[staff_entered] = true
+        if staff_in_room.profile.is_researcher and self.room_info.id == "research" then
+          self.hospital:giveAdvice(researcher_desks)
+        end
+        if staff_in_room.humanoid_class == "Nurse" and self.room_info.id == "ward" then
+          self.hospital:giveAdvice(nurse_desks)
+        end
+        if (not staff_in_room.dealing_with_patient) or staff_in_room:isMeandering() then
```
[the remark this answers is not in the document]
Comment (ARGAMX) [reply CorsixTH/Lua/room.lua:370]: > I don't believe you really need the bracket; the not only tests against the first condition. But there's also no harm in it here.

I think you don't like brackets in `if`.

As for me, there is nothing really wrong with these brackets.

I had an experience with one language when the absence of brackets in the `if` condition was perceived by the compiler as an error.

That's why I am used to the fact that brackets in the `if` are never unnecessary.

File: CorsixTH/Lua/room.lua [hunk 18]
```diff
@@ -356,42 +356,46 @@ function Room:onHumanoidEnter(humanoid)
...
-          self:commandEnteringStaff(humanoid)
+    local staff_entered = humanoid
+    if not self:staffFitsInRoom(staff_entered) then
+      if self:getStaffMember() and self:staffMeetsRoomRequirements(staff_entered) then
+        local staff_in_room = self:getStaffMember()
+        self.humanoids[staff_entered] = true
+        if staff_in_room.profile.is_researcher and self.room_info.id == "research" then
+          self.hospital:giveAdvice(researcher_desks)
+        end
+        if staff_in_room.humanoid_class == "Nurse" and self.room_info.id == "ward" then
```
Comment (ARGAMX) [inline CorsixTH/Lua/room.lua:367]: Does anybody feel that `staff_in_room` (alias for `room.staff_member`) is an error here?

I have a feeling that it must be `staff_entered`, not `staff_in_room`.

But I didn't dare to change it.

File: CorsixTH/Lua/room.lua (hunk 3 above)
Comment (ARGAMX) [inline CorsixTH/Lua/room.lua:369]: Does anybody feel that staff_in_room (alias for room.staff_member) is an error here?

I have a feeling that it must be staff_entered, not staff_in_room.

But I didn't dare to change it.

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 11 above)
Comment (ARGAMX) [reply CorsixTH/Lua/rooms/general_diag.lua:91]: > The doctor strictly speaking uses the trolley. It's just some silly quirk it gets applied to the patient.

For some strange reason for General Diagnosis `MultiUseObjectAction` in patient action queue, not in staff queue. (why?...)
So technically patient use trolley. It strange.

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 15 above)
Comment (ARGAMX) [reply CorsixTH/Lua/rooms/general_diag.lua]: > The code is likely poorly named, but logically the comment I added is correct.
> 
> If not mine, the comment needs a rephrase a little to better convey the stage. The comment currently makes me wonder what exactly was he waiting for (I and you know from experience what, but to someone else it might not be crystal clear)? Inference of some kind about the patient in context would be nice.

`        -- Release doctor after procedure and finish his IdleAction() near trolley
`

File: CorsixTH/Lua/room.lua (hunk 17 above)
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/room.lua]: It's not so much that I don't like them :p 
In the past I'd overbracket things then would get told to remove them.

I did say I was fine leaving this as though.

File: CorsixTH/Lua/room.lua (hunk 3 above)
Comment (Alberth289346) [reply CorsixTH/Lua/room.lua:369]: It very likely makes no difference. The research room and the ward only have one type of staff members.

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 19]
```diff
@@ -52,47 +52,81 @@ end
...
+
+      -- Doctor walks to trolley
+      local ox, oy = trolley:getSecondaryUsageTile()
+      local staff_prepare = WalkAction(ox, oy)
+          :setMustHappen(true)
+          :disableTruncate()
+          :setUninterruptable(true)
+      staff:setNextAction(staff_prepare)
+
+      -- Doctor waits patient near trolley
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:72]: Sorry, I think I missed the `for` -- Doctor waits for patient near trolley

File: CorsixTH/Lua/rooms/general_diag.lua [hunk 20]
```diff
@@ -52,47 +52,81 @@ end
...
+      staff:queueAction(staff_idle)
+
+      -- Patient walks to trolley
+      local go_to_trolley = WalkAction(cx, cy)
+          :setMustHappen(true)
+          :disableTruncate()
+      patient:queueAction(go_to_trolley)
+
+      local after_use_trolley = --[[persistable:general_diag_trolley_after_use]] function()
+        -- Release doctor after procedure and finish his IdleAction() near trolley
```
Comment (lewri) [inline CorsixTH/Lua/rooms/general_diag.lua:86]: Ah.... I see now. Misleading order.
This is fine.

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 11 above)
Comment (lewri) [reply CorsixTH/Lua/rooms/general_diag.lua:91]: Hmm..  I'd more argue the patient queues the action for the doctor to use the trolley but okay :)
If you're sticking with that then you'll need a `uses`

File: CorsixTH/Lua/entities/humanoids/staff.lua [hunk 21]
```diff
@@ -509,12 +509,12 @@ function Staff:adviseWrongPersonForThisRoom()
...
 
--- Function to decide if staff currently Meander
+--! Check whether staff are meandering
+--!return true if staff currently has a meander action
 function Staff:isMeandering()
-  for _, action in ipairs(self.action_queue) do
-    if action.name == "meander" then
-      return true
-    end
+  if (self.action_queue[1].name == "meander") or
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/staff.lua]: I recall this was discussed in the room, but why does meander have to be in the first two actions to count?

Unintuitive enough to be commented on.

File: CorsixTH/Lua/entities/humanoid.lua (hunk 4 above)
Comment (Alberth289346) [reply CorsixTH/Lua/entities/humanoid.lua:495]: Documenting is fine.

The point I am trying to make is that you your comments should always be about the code *below* it. If you want to say something about the code above, write a comment about that code at a line earlier in the file.

In that way, a reader doesn't have to look up and down the file, trying to find a comment that explains the line of code that gives trouble.

In your change, the "because it has been marked as to be interrupted" part is about the `if` statement above it. It's not about the code below (the code below just aborts blindly without caring why it must do that).  
It's fine that you want to state what the `if` is doing, but write that text above the `if` line.

Here, you could write above line 494 `-- Check whether the first action is interrupted.` (Instead if `first` you could also write `current`.)

Then at 495 you could write a short comment like `-- Abort the action.` or so.

File: CorsixTH/Lua/rooms/general_diag.lua (hunk 11 above)
Comment (ARGAMX) [reply CorsixTH/Lua/rooms/general_diag.lua:91]: > Hmm.. I'd more argue the patient queues the action for the doctor to use the trolley but okay :) If you're sticking with that then you'll need a `uses`

Ok
But nevertheless I don't know what to argue about here... it's not me saying this, it's the code saying this. This is strange for me.

Before I started refactoring General Diagnosis room, I thought the same as you.
In the Operating Theatre room it is the doctors who perform (hold in action queue) `MultiUseObjectAction` and `UseObjectAction`.

But after reading the code regarding the General Diagnosis, I can no longer stay this way.
Because this action not in Doctor queue.
If I remove `IdleAction()` from Doctor queue and replace it with `MeanderAction()` he will just start to walk across the room. I have recorded video for you:

[Screen Recording 2025-05-06 at 10.53.15.webm](https://github.com/user-attachments/assets/bb099877-ec73-46fe-ae1a-dda9dfbac05b)

From this video I see like that technically doctor don't really occupied by the trolley.
He connected with that action, yes.
But not occupied by it.
The patient is really occupied by this action and can't move.
At least from `GeneralDiagRoom:commandEnteringPatient` perspective.

So if you will write that the doctor uses a trolly, then your comment will contradict with this code:
`patient:queueAction(use_trolley)`

And in that case I will have the feeling what there is something wrong here.

I hope this comment will be more transparent:

`-- Patient uses trolley (trolly animation with patient and doctor)`

File: CorsixTH/Lua/entities/humanoids/staff.lua (hunk 21 above)
Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoids/staff.lua]: > I recall this was discussed in the room, but why does meander have to be in the first two actions to count?
> 
> Unintuitive enough to be commented on.

Reasonable, I agree.
I think meander can only be second action. Not first.
So I have change this condition again.

I have added a comment that describes how `action_queue` should looks to be a "meandering" case.

File: CorsixTH/Lua/entities/humanoid.lua (hunk 4 above)
Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoid.lua:495]: > Here, you could write above line 494 `-- Check whether the first action is interrupted.` (Instead if `first` you could also write `current`.)
> 
> Then at 495 you could write a short comment like `-- Abort the action.` or so.

OK, thank you.
