### PR TITLE
Don't assume staff_member_set for all rooms

### LINKED ISSUE #3094: [Bug] Female cycling between door and screen in general diagnosis
### Describe the issue

Female was sent to general diagnosis.
Savegame is just before the visit (doctor and female still need to enter).

After the doctor, the female enters, changes cloths (I think twice), walks out again, turns 180 degrees, knocks at the door, enters, changes cloths ....

### Steps to Reproduce

[p1.zip](https://github.com/user-attachments/files/23141160/p1.zip)

1. *Load save game attached to this ticket*

2. Unpause

3. Watch female

### Expected Behaviour

After changing cloths, visit the crash trolley for an examination.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions (applies to CorsixTH versions < 0.70.0)

### Save Game

Save game attached to report: Yes

### CorsixTH Version

f0cb8fd6 (current master)

### Operating System

Linux

### Theme Hospital Version

CD

### Gamelog.txt

```yaml
Nothing relevant exists in the log.
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #3094*

**Describe what the proposed change does**
- Staff member set was applying to all rooms at once following #2971 
- Reverts this, adds a note to override in derived class instead (we already do)
- Option commit for afterLoad, if we want it

### CODE REVIEW

File: CorsixTH/Lua/room.lua [hunk 1]
```diff
@@ -1075,6 +1075,13 @@ function Room:afterLoad(old, new)
     self.waiting_staff_member = nil
     self.dealt_patient_callback = nil
   end
+  -- Patch the saves post 233 that labelled all rooms as having a staff_member_set
+  if old >= 233 and old < 235 then
```
Comment (lewri) [inline CorsixTH/Lua/room.lua:1080]: I know we generally don't like doing this format of old. If we want the afterload and don't like this it can just be old < 235

Comment (TheCycoONE) [reply CorsixTH/Lua/room.lua:1080]: It's fine

File: CorsixTH/Lua/room.lua [hunk 2]
```diff
@@ -33,7 +33,7 @@ function Room:Room(x, y, w, h, id, room_info, world, hospital, door, door2)
   -- Serving staff in single occupancy rooms (like GD, Pharmacy and etc)
   self.staff_member = nil
   -- Serving staff list in multi-occupancy rooms (like Operating Theatre)
-  self.staff_member_set = {}
+  self.staff_member_set = nil -- Override with {} in derived class
```
Comment (TheCycoONE) [inline CorsixTH/Lua/room.lua:37]: Please explain why this has to be nil here / difference in behaviour so that the next dev doesn't come along and change it back.

Comment (Alberth289346) [reply CorsixTH/Lua/room.lua:37]: Alternatively, eliminate the single staff member case, so we don't have this confusion any more.
