### PR TITLE
Remove .0 from numbers in saved fullscreen windows

### LINKED ISSUE #2038: [Bug] Persistence restores some integers with .0
#### Describe the issue
Persistence has a habit or saving and changing a whole integer (e.g. 5) to a number with decimal (5.0). This isn't such an issue where the numbers aren't visual to the player.

#### Steps to Reproduce
1. Get an annual report and save game on first screen

2. Reload game and observe changes

#### Expected Behavior
Persistence should be restoring values as originally used visually.

#### System Information
**CorsixTH Version:** 0.65

**Operating System:** Windows 10

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*
image
image

### PR DESCRIPTION
**Pull request by lewri**
Suggest #2183 is merged before this one.

*Fixes #2038* except for `progress_report.lua`

**Describe what the proposed change does**
- Fixes integer values on some windows where saving with the open would cause a .0 to appear when loading the game.
- Progress Report can't be fixed using this PR. A fixme was added instead with reasons.

### CODE REVIEW

File: CorsixTH/Lua/dialogs/fullscreen/annual_report.lua [hunk 1]
```diff
@@ -533,7 +534,7 @@ function UIAnnualReport:draw(canvas, x, y)
       end
       self.stone_font:draw(canvas, award_type, x + 220, y + 330, 200, 0)
       -- Amount won/lost
-      self.stone_font:draw(canvas, "+" .. info.amount, x + 220, y + 355, 200, 0)
+      self.stone_font:draw(canvas, "+" .. string.format("%.0f", info.amount), x + 220, y + 355, 200, 0)
```
Comment (TheCycoONE) [inline CorsixTH/Lua/dialogs/fullscreen/annual_report.lua:537]: concatenation is unneeded, there is a format specifier to include sign: https://www.cplusplus.com/reference/cstdio/printf/

File: CorsixTH/Lua/dialogs/fullscreen/annual_report.lua [hunk 2]
```diff
@@ -548,7 +549,7 @@ function UIAnnualReport:draw(canvas, x, y)
       if info.amount > 0 then
         text = "+"
       end
-      self.write_font:draw(canvas, text .. info.amount, x + 220, y + 315, 200, 0)
+      self.write_font:draw(canvas, text .. string.format("%.0f", info.amount), x + 220, y + 315, 200, 0)
```
Comment (TheCycoONE) [inline CorsixTH/Lua/dialogs/fullscreen/annual_report.lua:552]: likewise, we can get rid of the previous several lines and include the sign specifier in the format string https://www.cplusplus.com/reference/cstdio/printf/

File: CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua [hunk 3]
```diff
@@ -258,7 +262,7 @@ function UIBankManager:draw(canvas, x, y)
 
     -- Summary
     font:draw(canvas, _S.bank_manager.statistics_page.current_balance, x + 373, y + 420, 140, 0)
-    font:draw(canvas, "$ " .. hospital.balance, x + 526, y + 421, 70, 0)
+    font:draw(canvas, "$ " .. string.format("%.0f", hospital.balance), x + 526, y + 421, 70, 0)
```
Comment (TheCycoONE) [inline CorsixTH/Lua/dialogs/fullscreen/bank_manager.lua:265]: Put the $ before the % in the format string instead of concat

**Review by TheCycoONE — COMMENTED** [review]
nits on some of the format strings, and extra work that doesn't need to be done now that we're using format. otherwise lgtm

**Comment by lewri** [comment]
I'll take a look. Expression stuff isn't my forte but I'll have a go

**Comment by TheCycoONE** [comment]
`%+.0f` to include the sign

**Comment by lewri** [comment]
Changes done

**Comment by TheCycoONE** [comment]
LGTM. I trust you tested all of this?

**Comment by lewri** [comment]
Yes. Except graph because I couldn't at the time. Will check that one and get back to you
