### PR TITLE
Debug patients properly deregister on autopsy

### LINKED ISSUE #2699: [Bug] Debug patient not properly destroyed via Autopsy machine
### Describe the issue

If you send a debug patient to autopsy parts of them remain in the game. As such, right clicking on the map after autopsy causes an error to be thrown in the pathfinder.

### Steps to Reproduce

1. Spawn a debug patient in from the debug patient window

2. Send them to the research department (left click debug patient, then right click door of room)

3. After autopsy finishes, right click on the map.

### Expected Behaviour

Entity requires proper destruction.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

Save game attached to report: No

### CorsixTH Version

0.68.0 (strictly speaking a build of the speed fix pr but reproducible the same in release)

### Operating System

Windows 10

### Theme Hospital Version

GOG.com

### Gamelog.txt

```yaml
Gamelog generated on 2024-10-27 19:23:46
Compiled with api_version: 2688, arch: x64, audio: true, os: windows, update_check: true
SDL renderer: direct3d
Lua 5.4 run with api version: 2688, game version: Trunk, savegame version: 205
Created game with savegame version 205.
Error in buttonup handler: 
Lua\world.lua:1382: bad argument #2 to 'findPath' (number expected, got nil)
stack traceback:
	[C]: in method 'findPath'
	Lua\world.lua:1382: in method 'getPath'
	Lua\humanoid_actions\walk.lua:400: in field '?'
	Lua\entities\humanoid.lua:476: in method 'startAction'
	Lua\entities\humanoid.lua:552: in method 'setNextAction'
	Lua\entities\humanoid.lua:687: in method 'walkTo'
	Lua\game_ui.lua:656: in function <Lua\game_ui.lua:646>
	(...tail calls...)
	Lua\app.lua:1139: in function <Lua\app.lua:1134>
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2699*

**Describe what the proposed change does**
- Debug patients at autopsy are now properly removed from debug list on death (as well as room explosion)
- Intended to do more refactor, but debug patients must be deregistered out the debug list much earlier than from the hospital patient list
- A little doc

### CODE REVIEW

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 1]
```diff
@@ -509,9 +509,11 @@ function Patient:goHome(reason, disease_id)
 
   hosp:updatePercentages()
 
+  -- Debug patients must be removed from the debug list so they can despawn properly
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/patient.lua:512]: Why do we still have this here? They must be removed from hospital somewhere or else we'd leak patients.

Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/patient.lua:512]: Not removing them here means they can still be commanded by the player. This interrupts their despawn cycle, and remain stuck in the hospital.
