### PR TITLE
Remove duplicate call to open the win fax

### LINKED ISSUE #1675: [Bug] Win level cheat can break
#### Describe the issue
It is possible to break the Win level cheat (why on earth you would?) by activating it a second time after closing the first message

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Activate the 'end of year' cheat so annual report comes up. Then run the 'win level' cheat. Close the win fax (using the x)

3. Run the 'end of year' cheat again, followed by the 'win level' cheat.

#### Save Game

Use save from 1642

#### Expected Behavior
Don't crash and show win cheat.

#### System Information
**CorsixTH Version:** *0.64*

**Operating System:** *Windows 10*

**Theme Hospital Version:** *GOG*

#### Gamelog.txt

```
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
Lua\window.lua:119: Suspected infinite loop
stack traceback:
        [C]: in function 'error'
        Lua\app.lua:1030: in hook '?'
        Lua\window.lua:119: in field 'close'
        Lua\dialogs/fullscreen\fax.lua:284: in method 'close'
        Lua\ui.lua:1028: in method 'addWindow'
        Lua\dialogs\message.lua:122: in method 'openMessage'
        Lua\dialogs\bottom_panel.lua:413: in method 'openLastMessage'
        Lua\world.lua:1456: in method 'winGame'
        Lua\dialogs/resizables\cheats.lua:217: in field 'func'
        Lua\dialogs/resizables\cheats.lua:133: in method 'buttonClicked'
        Lua\dialogs/resizables\cheats.lua:100: in local 'callback'
        Lua\window.lua:691: in method 'handleClick'
        Lua\window.lua:1652: in method 'onMouseUp'
        Lua\window.lua:1636: in field 'onMouseUp'
        Lua\ui.lua:902: in function <Lua\ui.lua:889>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>

Error in buttonup handler:
Lua\window.lua:119: Suspected infinite loop
stack traceback:
        [C]: in function 'error'
        Lua\app.lua:1030: in hook '?'
        Lua\window.lua:119: in field 'close'
        Lua\dialogs/fullscreen\fax.lua:284: in method 'close'
        Lua\ui.lua:1028: in method 'addWindow'
        Lua\dialogs\message.lua:122: in method 'openMessage'
        Lua\dialogs\bottom_panel.lua:413: in method 'openLastMessage'
        Lua\world.lua:1456: in method 'winGame'
        Lua\dialogs/resizables\cheats.lua:217: in field 'func'
        Lua\dialogs/resizables\cheats.lua:133: in method 'buttonClicked'
        Lua\dialogs/resizables\cheats.lua:100: in local 'callback'
        Lua\window.lua:691: in method 'handleClick'
        Lua\window.lua:1652: in method 'onMouseUp'
        Lua\window.lua:1636: in field 'onMouseUp'
        Lua\ui.lua:902: in function <Lua\ui.lua:889>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>
```

### Additional Info
Just to note this isn't caused by the PR work I'm doing right now.

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #1675*

**Describe what the proposed change does**
https://github.com/search?q=repo%3ACorsixTH%2FCorsixTH+bottom_panel%3Aopenlastmessage&type=code

There are two calls to open the same win fax, this removes one of them.

### CODE REVIEW

File: CorsixTH/Lua/dialogs/fullscreen/annual_report.lua [hunk 1]
```diff
@@ -452,7 +452,6 @@ end
 function UIAnnualReport:close()
   if TheApp.world:getLocalPlayerHospital().game_won then
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/fullscreen/annual_report.lua:453]: It seems odd we check for game won before we actually run the function in world for `checkIfGameWon()` but that isn't relevant here.

**Review by lewri — APPROVED** [review]

File: CorsixTH/Lua/dialogs/fullscreen/annual_report.lua (hunk 1 above)
Comment (Alberth289346) [reply CorsixTH/Lua/dialogs/fullscreen/annual_report.lua:453]: I would say, the problem is the distributed control of the blue filter.

But yeah, not relevant for this issue.
