### PR TITLE
Make sprite viewer reopenable

### LINKED ISSUE #1785: [Bug] Sprite Viewer breaks event handlers
#### Describe the issue
When you open the Sprite Viewer from debug menu in 0.64+ all event handlers error out.

#### Steps to Reproduce
1. Open a save/new game

2. Go to debug > Sprite Viewer. Console should output warnings as below and app may momentarily freeze.

3. Browse through spriteviewer then exit. Try to launch spriteviewer again and fails to  re-open.

#### Expected Behavior
Handle the Sprite Viewer properly and not cause event handler issues. 

#### System Information
**CorsixTH Version:** 0.64 (and Trunk 143)

**Operating System:** W10

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Warning: No event handler for motion
Warning: No event handler for active
Warning: No event handler for textediting
Warning: No event handler for textinput
Warning: No event handler for buttondown
Warning: No event handler for buttonup
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

### LINKED ISSUE #2308: UIInformation box is loading pink
Not sure if this relates to #2279 as it's not present in 0.66 but UIInformation when generated at load is pink.
image

Doesn't happen if the save fails to load (error on load)

Does happen if we generate a new UIInformation during gameplay (regardless of very_old_save message or not)
image

Edit: Didn't notice before but the tooltip can also load yellow on that box
image

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #1785*
*Fixes #2308*

**Describe what the proposed change does**
- Make spriteviewer reopenable in the same session. It resumes where you left off (which is I assume what it already did previously anyway, you just couldn't access it).

Please could we get some additional checks this doesn't break saves or to the best of our ability any other part of the game handlers. I've tested myself and seems ok.

### CODE REVIEW

File: CorsixTH/Lua/dialogs/menu.lua [hunk 1]
```diff
@@ -873,7 +873,7 @@ function UIMenuBar:makeGameMenu(app)
         :appendCheckItem(_S.menu_debug_overlay.byte_7,      false, overlay(7, 7, true), "")
         :appendCheckItem(_S.menu_debug_overlay.parcel,      false, overlay("parcel"), "")
       )
-      :appendItem(_S.menu_debug.sprite_viewer, function() corsixth.require("sprite_viewer") end)
+      :appendItem(_S.menu_debug.sprite_viewer, function() corsixth.require("sprite_viewer")() end)
```
Comment (TheCycoONE) [inline CorsixTH/Lua/dialogs/menu.lua:876]: Should be able to simplify this by removing the lambda (wrapping function) and the parenthesis after sprite_viewer.

File: CorsixTH/Lua/sprite_viewer.lua [hunk 2]
```diff
@@ -245,10 +249,23 @@ local function DoTimer()
...
+    frame = DoFrame,
+    keydown = DoKey,
+    keyup = DoKeyUp,
+    timer = DoTimer,
+  }
+
+  need_draw = true
+end
+
+return function()
```
Comment (TheCycoONE) [inline CorsixTH/Lua/sprite_viewer.lua]: Same, you don't need an anonymous function here, you can return SpriteViewer.open (without calling it)

**Comment by TheCycoONE** [comment]
I don't think you need the SpriteViewer object at all, just return the open function?

File: CorsixTH/Lua/sprite_viewer.lua [hunk 3]
```diff
@@ -245,10 +250,24 @@ local function DoTimer()
...
-  keydown = DoKey,
-  keyup = DoKeyUp,
-  timer = DoTimer,
-}
+local function open()
+  if is_open then
+    return
+  end
+  is_open = true
+  gfx.cache.tabled = {}
```
Comment (lewri) [inline CorsixTH/Lua/sprite_viewer.lua]: @TheCycoONE don't feel like this one should be reset every time it's opened? I can move it back...

**Comment by lewri** [comment]
Wrapping function put back as discussed.

File: CorsixTH/Lua/sprite_viewer.lua (hunk 3 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/sprite_viewer.lua]: It actually should reset back to normal on close and to this or a new object on close.

**Review by ARGAMX — APPROVED** [review]
Works good for me
Issue resolved 👍

**Comment by lewri** [comment]
Yep, don't merge yet until I resolve the gfx.cache.tabled thing. (Edit forgot it was on RFC :D )

**Comment by lewri** [comment]
Proper cache swapping added, as a bonus fixes the pink issue.
Ready to review again.

**Review by TheCycoONE — APPROVED** [review]
