### PR TITLE
Setting autosave frequency

### LINKED ISSUE #1426: Question: Any easy way to shorten the autosave period?
Hi,
Is there some relatively easy way of shortening the autosave period?

Why I ask: This would make it easier when trying to reproduce a crash and to generate a save game just before. If possible I would set it to autosave every 1 or 2 minutes.

### LINKED ISSUE #3107: Autosave every game day
----

### What feature or enhancement would you like to add?

Option to make autosave every game day, not just 1 save per month.

Image

----

### How would this feature benefit the gameplay of CorsixTH?

First of all, this function is very useful for debugging. But not only.
The current state of the project still requires a lot of debugging, observation and experimentation.
This feature would be useful not just for developers.

I've been using it for more than half a year.
This allowed me to get a lot of useful saves that allowed me to reproduce the defects.
Some of my discoveries and investigations were only possible thanks to this feature.
From the latest is 3056 issue.

At first, I used this functionality exclusively for myself.
But I gave this code to user Mickman, and during his play he provided a lot of save files with various obscure situations and bugs thanks to this. As example 3051 issue.
That's when I realized that this feature should be available for other developers and players, and not just for me.

So this feature can make players a more effective source of information for reproducing bugs.
It's probably even strange that no one has added this feature before.
Also possibly #2925 can benefit from this.

I didn't notice any significant negative effects from this feature. 
The game didn't run any slower.
The Autosave folder size increased to 500 MB.
This is most likely a consequence of the fact that the game saves are stored in an uncompressed state.

I also considered autosaving with a configurable interval, but that seemed too complicated.
So for now I've settled on two options: saving once a month (like now) and saving once a day.

----

### CorsixTH Version

0.69.1

----

### PR DESCRIPTION
**Pull request by ARGAMX**
*Fixes #3107*
*Fixes #1426*

**Describe what the proposed change does**
- The following approach has been implemented: https://github.com/CorsixTH/CorsixTH/issues/3107#issuecomment-3810384695

Some things that deviated from that course:
- Weekly - Autosave once per week on the 1st, ~~8th, 15th, 22nd, and 29th~~ 7th, 14th, 21nd, and 28th of each month. 
- This setting hosted not in `Settings -> Customise` but in `Settings`.

Screenshot 2026-02-12 at 12 10 50

Screenshot 2026-02-12 at 12 11 04

- The rest is as planned in the message.

### CODE REVIEW

File: CorsixTH/Lua/config_finder.lua [hunk 1]
```diff
@@ -420,7 +421,14 @@ local string_01 = [=[
 -- By default subtitles are not displayed. If you would like the game to
 -- display subtitles for your hospital's announcements, turn this option on.
 --]=] .. '\n' ..
-'enable_announcer_subtitles = ' .. tostring(config_values.enable_announcer_subtitles) .. '\n' .. [=[]=]
+'enable_announcer_subtitles = ' .. tostring(config_values.enable_announcer_subtitles) .. '\n' .. [=[
+
+-------------------------------------------------------------------------------
+-- By default, the game autosaves every in-game month. If you would like to
+-- autosave more ofter, every week or every day, change this setting to 2 or 3.
+-- Set 1 for Monthly, 2 for Weekly, 3 for Daily autosaves.
```
Comment (lewri) [inline CorsixTH/Lua/config_finder.lua:431]: Recommend adding the daily usage size warning in here too.

File: CorsixTH/Lua/languages/english.lua [hunk 2]
```diff
@@ -490,11 +490,24 @@ options_window = {
   scrollspeed = "Scroll Speed",
   shift_scrollspeed = "Shift Scroll Speed",
   zoom_speed = "Zoom Speed",
+  autosave_periodicity = "Autosave Periodicity",
```
Comment (lewri) [inline CorsixTH/Lua/languages/english.lua]: `Autosave Frequency` or `Autosave Period` is probably a bit more universally language friendly?

File: CorsixTH/Lua/languages/english.lua [hunk 3]
```diff
@@ -490,11 +490,24 @@ options_window = {
...
+autosave_periodicity = {
+    monthly = "Monthly",
+    weekly = "Weekly",
+    daily = "Daily",
+}
+
+tooltip.autosave_periodicity = {
+    monthly = "Autosave once per month, on the first day of each month. A total of 12 saves with a depth of 1 year.",
+    weekly = "Autosave once per week on the 1st, 7th, 14th, 21nd, and 28th of each month. A total of 60 saves with a depth of 1 year.",
+    daily = "Autosave once per day at the start of each in-game day. A total of 365 saves with a depth of 1 year. Please note that a typical save can take up to 1 megabyte or even more. This way your autosaves folder can grow to 300-500 MB.",
```
Comment (lewri) [inline CorsixTH/Lua/languages/english.lua:508]: I would've liked its own warning message. Only thing to bear in mind is this tooltip will be long.

File: CorsixTH/Lua/world.lua [hunk 4]
```diff
@@ -1055,6 +1064,17 @@ function World:onEndDay()
       self.spawn_hours[hour] = self.spawn_hours[hour] and self.spawn_hours[hour] + 1 or 1
     end
   end
+
+  -- Autosave
+  if self.app.config.autosave_periodicity == 3 then
+    -- Daily autosave
+    self.autosave_next_tick = true
+  elseif self.app.config.autosave_periodicity == 2 then
+    if day == self.game_date:lastDayOfMonth() or day == 6 or day == 13 or day == 20 or day == 27 then
```
Comment (lewri) [inline CorsixTH/Lua/world.lua:1073]: Double check dates in the summary, last date for month says 25, this says 27?

File: CorsixTH/Lua/world.lua [hunk 5]
```diff
@@ -1055,6 +1064,17 @@ function World:onEndDay()
       self.spawn_hours[hour] = self.spawn_hours[hour] and self.spawn_hours[hour] + 1 or 1
     end
   end
+
+  -- Autosave
+  if self.app.config.autosave_periodicity == 3 then
+    -- Daily autosave
+    self.autosave_next_tick = true
```
Comment (lewri) [inline CorsixTH/Lua/world.lua:1071]: I assume we don't try to fire 2 autosaves on daily for the end of the month?

File: CorsixTH/Lua/languages/english.lua (hunk 2 above)
Comment (MandrakeHorse) [reply CorsixTH/Lua/languages/english.lua]: I personally like "Autosave Frequency"

File: CorsixTH/Lua/languages/english.lua (hunk 3 above)
Comment (MandrakeHorse) [reply CorsixTH/Lua/languages/english.lua:508]: When the user toggles Alien Patients and Fractured Bones in the Custom Settings, a popup appears to warn the user of the effects of changing each setting. Can we add something similar when the user selects Daily?

File: CorsixTH/Lua/world.lua (hunk 5 above)
Comment (ARGAMX) [reply CorsixTH/Lua/world.lua:1071]: > I assume we don't try to fire 2 autosaves on daily for the end of the month?

This shouldn't happen.
At the end of the day or month, the `autosave_next_tick` flag may be set.
Even if this happened twice on the last day of the month, and the flag was set twice, the autosave would still only happen once per tick, after which the flag is reset.
Thanks for your concern about this.

File: CorsixTH/Lua/world.lua (hunk 4 above)
Comment (ARGAMX) [reply CorsixTH/Lua/world.lua:1073]: > Double check dates in the summary, last date for month says 25, this says 27?

Indeed, I made a typo in the summary.
25 is an incorrect value.
On the 27th day end we raise the flag so that an autosave occurs on the 28th day tick.
I corrected the summary.
Thanks for noticing.

File: CorsixTH/Lua/languages/english.lua (hunk 2 above)
Comment (ARGAMX) [reply CorsixTH/Lua/languages/english.lua]: I agree, `Autosave Periodicity` probably doesn't sound nice.
I renamed all feature to `Autosave Frequency`. 👍

File: CorsixTH/Lua/config_finder.lua (hunk 1 above)
Comment (ARGAMX) [reply CorsixTH/Lua/config_finder.lua:431]: > Recommend adding the daily usage size warning in here too.

Sounds reasonable.
Added warning here. 👌

File: CorsixTH/Lua/languages/english.lua (hunk 3 above)
Comment (ARGAMX) [reply CorsixTH/Lua/languages/english.lua:508]: I'd like users to enable this option to save every day, unlike the Alien Patients.
But that window will scare them too much.
Still, 300 MB isn't much in 2026. 
On macOS, CorsixTH takes up that much.

File: CorsixTH/Lua/config_finder.lua [hunk 6]
```diff
@@ -420,7 +421,16 @@ local string_01 = [=[
 -- By default subtitles are not displayed. If you would like the game to
 -- display subtitles for your hospital's announcements, turn this option on.
 --]=] .. '\n' ..
-'enable_announcer_subtitles = ' .. tostring(config_values.enable_announcer_subtitles) .. '\n' .. [=[]=]
+'enable_announcer_subtitles = ' .. tostring(config_values.enable_announcer_subtitles) .. '\n' .. [=[
+
+-------------------------------------------------------------------------------
+-- By default, the game autosaves every in-game month. If you would like to
+-- autosave more ofter, every week or every day, change this setting to 2 or 3.
```
Comment (TheCycoONE) [inline CorsixTH/Lua/config_finder.lua]: Typo: ofter -> often

File: CorsixTH/Lua/world.lua [hunk 7]
```diff
@@ -948,6 +937,26 @@ function World:onTick()
   self.tick_timer = self.tick_timer - 1
 end
 
+--! Creates a save file in the "Autosaves" folder, using the "Autosave-mm-dd.sav" name template for filename.
+-- If the "Autosaves" folder does not exist, folder will be created.
+function World:executeAutosave()
```
Comment (TheCycoONE) [inline CorsixTH/Lua/world.lua]: `_` prefix for private functions. I think this wouldn't be called outside of World.

Comment (ARGAMX) [reply CorsixTH/Lua/world.lua]: > `_` prefix for private functions. I think this wouldn't be called outside of World.

👌

File: CorsixTH/Lua/config_finder.lua (hunk 6 above)
Comment (ARGAMX) [reply CorsixTH/Lua/config_finder.lua]: > Typo: ofter -> often

👌

File: CorsixTH/Lua/world.lua (hunk 5 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/world.lua:1071]: It still might be cleaner to move the remaining case with the other two.

Nothing that blocks merging, just an opinion.

Comment (ARGAMX) [reply CorsixTH/Lua/world.lua:1071]: > It still might be cleaner to move the remaining case with the other two.
> 
> Nothing that blocks merging, just an opinion.

Agree, it's a good idea. For some reason, I didn't think of that.
Moved 👌

**Review by TheCycoONE — APPROVED** [review]
