### PR TITLE
[RDY] Handle errors in confirm dialogs

### LINKED ISSUE #1865: [Bug] Replacing a machine in pause state will unpause
#### Describe the issue
Replacing a machine will unpause the game

#### Steps to Reproduce
1. Build a machine room, eg Inflator
2. Pause
3. Replace the machine

#### Expected Behavior
Game stays paused

#### System Information
0ef7cb0
macOS 10.16.7
CD

### PR DESCRIPTION
**Pull request by lewri**
Alternative to #1867

*Fixes #1865*

**Describe what the proposed change does**
- Adds a parameter to UIConfirmDialog to declare if the window is due to an error or not
- If it is an error, a pause is forced
- Game will not unpause until error is dealt with

### CODE REVIEW

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 1]
```diff
@@ -67,11 +75,17 @@ function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
...
 end
 
--- Confirm dialogs are used for errors and require the game to pause
+-- Confirm dialogs are used for errors, if it is an error then pause the game
 function UIConfirmDialog:mustPause()
-  return true
+  return self.is_error
+end
+
+-- Errors force pausing
```
Comment (Alberth289346) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:86]: How is 'errors' relevant here? There is nothing about errors in the `forcePause` function.

File: CorsixTH/Lua/world.lua [hunk 2]
```diff
@@ -956,16 +959,30 @@ end
...
+--! Sets whether the game should be forcefully paused
+--!param state (bool)
+function World:setSystemPause(state)
+  self.system_pause = state
+end
+
+--! Reports the system pause status
+--!return (bool) true is system pause is active, else false
+function World:isSystemPauseActive()
+  return self.system_pause or false
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/world.lua:979]: Not anymore, thanks :)

File: CorsixTH/Lua/dialogs/confirm_dialog.lua (hunk 1 above)
Comment (lewri) [reply CorsixTH/Lua/dialogs/confirm_dialog.lua:86]: Ah I've mixed up the what and why. I'll change this later

**Comment by TheCycoONE** [comment]
Leaning towards including this in 0.65 (and releasing a beta2 next week at the latest)

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 3]
```diff
@@ -67,11 +75,17 @@ function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
...
 
--- Confirm dialogs are used for errors and require the game to pause
+-- Confirm dialogs are used for errors, if it is an error then pause the game
 function UIConfirmDialog:mustPause()
-  return true
+  return self.is_error
+end
+
+--! Function to tell the game a system pause is needed
+function UIConfirmDialog:forcePause()
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:87]:
```suggestion
function UIConfirmDialog:systemPause()
```

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 4]
```diff
@@ -67,11 +75,17 @@ function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
     :setTooltip(_S.tooltip.window_general.confirm):setSound"YesX.wav"
 
   self:registerKeyHandlers()
+  if self.is_error then self:forcePause() end
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:78]:
```suggestion
  if self.is_error then self:systemPause() end
```

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 5]
```diff
@@ -67,11 +75,17 @@ function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
...
 end
 
--- Confirm dialogs are used for errors and require the game to pause
+-- Confirm dialogs are used for errors, if it is an error then pause the game
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:81]:
```suggestion
-- Confirm dialogs are used for errors, if it is an error then pause the game using the system_pause method
```

File: CorsixTH/Lua/world.lua [hunk 6]
```diff
@@ -111,6 +111,9 @@ function World:World(app)
   -- This is false when the game is paused.
   self.user_actions_allowed = true
 
+  -- Flag to force pausing to deal with recoverable errors
```
Comment (lewri) [inline CorsixTH/Lua/world.lua:114]:
```suggestion
  -- The system pause method is used as an additional layer to pause the game, where the user
  -- needs to deal with recoverable error
```

File: CorsixTH/Lua/world.lua [hunk 7]
```diff
@@ -956,16 +959,30 @@ end
...
 function World:pauseOrUnpause()
+  if self:isSystemPauseActive() then return end -- System pause takes precedence
   if not self:isCurrentSpeed("Pause") then
     self:setSpeed("Pause")
   elseif self.prev_speed then
     self:setSpeed(self.prev_speed)
   end
 end
 
+--! Sets whether the game should be forcefully paused
```
Comment (lewri) [inline CorsixTH/Lua/world.lua:970]:
```suggestion
--! Sets the system_pause parameter
```

**Review by lewri — COMMENTED** [review]
Comment adjustments

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 8]
```diff
@@ -31,7 +32,13 @@ local middle_frame_height = 11
 local bottom_frame = 359
 local text_width = 153
 
-function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
+--! Initialise the Confirmation Dialog
+--!param ui The UI
+--!param is_error (boolean) set whether this dialog is a result of an error (true) or not (false)
```
Comment (TheCycoONE) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:37]: Why are we abstracting the effect from the name here? I think I prefer `must_pause` as that's the real effect not just an implementation detail.

Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:37]:
```suggestion
--!param must_pause (boolean) set whether this dialog should pause the game
```

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 9]
```diff
@@ -31,7 +32,13 @@ local middle_frame_height = 11
...
+--!param text (string) message to show
+--!param callback_ok (function) what to do on yes/ok
+--!param callback_cancel (function) what to do on no/cancel/close
+function UIConfirmDialog:UIConfirmDialog(ui, is_error, text, callback_ok, callback_cancel)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:41]:
```suggestion
function UIConfirmDialog:UIConfirmDialog(ui, must_pause, text, callback_ok, callback_cancel)
```

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 10]
```diff
@@ -47,6 +54,7 @@ function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
   self.text = text
   self.callback_ok = callback_ok  -- Callback function to launch if user chooses ok
   self.callback_cancel = callback_cancel -- Callback function to launch if user chooses cancel
+  self.is_error = is_error
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:57]:
```suggestion
  self.must_pause = must_pause
```

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 11]
```diff
@@ -67,11 +75,17 @@ function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
     :setTooltip(_S.tooltip.window_general.confirm):setSound"YesX.wav"
 
   self:registerKeyHandlers()
+  if self.is_error then self:systemPause() end
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:78]:
```suggestion
  if self.must_pause then self:systemPause() end
```

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 12]
```diff
@@ -67,11 +75,17 @@ function UIConfirmDialog:UIConfirmDialog(ui, text, callback_ok, callback_cancel)
...
 end
 
--- Confirm dialogs are used for errors and require the game to pause
+-- Confirm dialogs are used for errors, if it is an error then pause the game
 function UIConfirmDialog:mustPause()
-  return true
+  return self.is_error
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:83]:
```suggestion
  return self.must_pause
```

File: CorsixTH/Lua/dialogs/confirm_dialog.lua [hunk 13]
```diff
@@ -88,11 +102,12 @@ function UIConfirmDialog:ok()
 end
 
 --! Closes the confirm dialog
---!param ok (boolean or nil) whether to call the confirm callback (true) or cancel callback (false/nil)
-function UIConfirmDialog:close(ok)
+--!param confirmed (boolean or nil) whether to call the confirm callback (true) or cancel callback (false/nil)
+function UIConfirmDialog:close(confirmed)
   -- NB: Window is closed before executing the callback in order to not save the confirmation dialog in a savegame
+  if self.is_error then TheApp.world:setSystemPause(false) end -- Error dealt with
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/confirm_dialog.lua:108]:
```suggestion
  if self.must_pause then TheApp.world:setSystemPause(false) end -- Error dealt with
```
