### PR TITLE
[RDY] Handymen announcements more often

### LINKED ISSUE #1649: "Handyman to repair x" announcements rarely trigger
#### Describe the issue
While testing a lot of earthquakes I noticed that the receptionist wasn't announcing machines that were in need of urgent repair (i.e. Handyman to repair x). It also appeared in some other saves that the task priority wasn't being bumped in the calls dispatcher (some handymen would still action low priority tasks over heightened ones).

This also doesn't seem specific to earthquakes, if regular machine use takes it over the threshold it still fails to announce.

There's only been one save I managed to get the announcements on. And I think that was from 0.60 or something. So maybe something has broke along the way since then?

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Make some earthquakes happen, may need to reduce handymen numbers.

3. Watch machines with smoke not triggering any announcements.

#### Save Game
https://www.dropbox.com/s/5akhnc9azhbaxyf/vipfor138.sav?dl=0

#### Expected Behavior
Receptionist should be announcing machines in disrepair.

#### System Information
**CorsixTH Version:** 0.64

**Operating System:** W10

**Theme Hospital Version:** GOG

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #1649*

**Describe what the proposed change does**
- Handyman repair announcements now trigger if base strength was >6. Originally they only triggered if base strength was <4
- Also ensures earthquakes don't make the announcer get spammed.

I expect some tidying up needed on this. At the moment this was to get it out of my old test environment.

### CODE REVIEW

File: CorsixTH/Lua/entities/machine.lua [hunk 1]
```diff
@@ -156,7 +160,23 @@ function Machine:machineUsed(room)
...
+        if earthquake.active and earthquake.warning_timer == 0 then
+          if not earthquake.machwarn_trigger then
+            self.world.ui:playAnnouncement("machwarn.wav", AnnouncementPriority.Critical)
+            earthquake.machwarn_trigger = true -- resets with each damage phase
+          end
+        else
+          -- Must be same priority
+          self.world.ui:playAnnouncement("machwarn.wav", AnnouncementPriority.Critical)
+          if sound then self.world.ui:playAnnouncement(sound, AnnouncementPriority.Critical) end
+        end
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/machine.lua:177]: This code looks duplicate to the calls dispatcher addition.

Don't clone code. If it contains a bug, or it should be modified in the future, you have practically a guarantee that not all clones will be modified in the same way, thus creating bugs, as the same thing works subtly different depending on the code path taken.

Instead, make a function for it, and call the function from every spot. Less code, no duplication, no missing of cloned code, less bugs

**Comment by lewri** [comment]
Latest commit seems to have broken something in persistence or the dispatcher. Not sure what

File: CorsixTH/Lua/entities/machine.lua [hunk 2]
```diff
@@ -155,8 +177,13 @@ function Machine:machineUsed(room)
     if taskIndex == -1 then
       local call = self.world.dispatcher:callForRepair(self, true, false, true)
       self.hospital:addHandymanTask(self, "repairing", 2, self.tile_x, self.tile_y, call)
+      self:announceRepair(room)
     else -- Otherwise the task is already queued. Increase the priority to above that of machines with at least 4 uses left
-      self.hospital:modifyHandymanTaskPriority(taskIndex, 2, "repairing")
+      local subTable = self.hospital:findHandymanTaskSubtable("repairing")
+      if subTable[taskIndex].priority == 1 then
+        self.hospital:modifyHandymanTaskPriority(taskIndex, 2, "repairing")
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/machine.lua:184]: The machine shouldn't hack the internals of the handyman task administration of the hospital.
Instead, wrap this in a new handymanTask function. In other words, be nice, *ask* the hospital to change the priority for you.

The goal is to keep the amount of code that changes some data structure as local and small as possible, with a well-defined (function) interface. In that way, you can change such a part, or move such code by modifying one or two files, instead of 100 files.

Comment (Alberth289346) [reply CorsixTH/Lua/entities/machine.lua:184]: Somewhat the same is your earthquake queries above.
That is however more of an edge case. I am not sure what part of the data is public and what is internal.

File: CorsixTH/Lua/world.lua [hunk 3]
```diff
@@ -647,6 +647,7 @@ function World:tickEarthquake()
 
       self.next_earthquake.remaining_damage = self.next_earthquake.remaining_damage - 1
       self.next_earthquake.damage_timer = self.next_earthquake.damage_timer + earthquake_damage_time
+      self.next_earthquake.machwarn_trigger = false
```
Comment (Alberth289346) [inline CorsixTH/Lua/world.lua:650]: You added a new variable, its meaning should be documented (see near line 101 in `world.lua`).

File: CorsixTH/Lua/world.lua [hunk 4]
```diff
@@ -99,6 +99,7 @@ function World:World(app)
   -- remaining_damage (integer) The amount of damage this earthquake has yet to inflict.
   -- damage_timer (integer) The number of hours until the earthquake next inflicts damage if active.
   -- warning_timer (integer) The number of hours left until the real damaging earthquake begins.
+  -- machwarn_trigger (boolean) True if a machine has already announced it is breaking during a damage phase (resets each phase)
```
Comment (lewri) [inline CorsixTH/Lua/world.lua:102]:
```suggestion
  -- machwarn_trigger (boolean) True if any machine has already announced it is breaking during a damage phase (resets each phase)
```

File: CorsixTH/Lua/entities/machine.lua (hunk 2 above)
Comment (mugmuggy) [reply CorsixTH/Lua/entities/machine.lua:185]: I have a feeling having just these 2 priorities for repair tasks is a little lacking when the plants have 5. I'm not expecting to address this now, but maybe something to consider later

**Comment by TheCycoONE** [comment]
Not really a fan of this implementation; I don't think earthquakes need to be special cased, and I especially don't like leaking the warning flag into the world earthquake structure - that's not local to the player.

Seems to me the problem of not playing the same announcement too often could be generalized and attached to the announcement queue system.

**Comment by lewri** [comment]
The announcer should be able to handle duplication of machwarn by itself actually. I'll need to look at how the duplication checker works there (even though I wrote it 😛  )
If it's good enough then we don't need to limit machwarns inside machine.
