### PR TITLE
Fix fired dr

### LINKED ISSUE #1924: [Bug] Attempt to getServiceQuality of staff with nil fatigue
#### Describe the issue
Error confirmation dialog popped up while navigating through staff list. See gamelog output.

#### Steps to Reproduce
1. Load the before save (or start a new game)
2. When a patient is in the inflation room, fire the doctor treating the patient
3. When patient is treated, game errors

#### Save Game
After the issue occurred (doctor's appear to be stuck):
[save.zip](https://github.com/CorsixTH/CorsixTH/files/6642550/save.zip)

#### System Information
**CorsixTH Version:** *3a0cd420* (appoximately 0.65 + zoom patch)

**Operating System:** *Arch Linux*

**Theme Hospital Version:** *CD*

#### Gamelog.txt
```
Created game with savegame version 155.
Error in callback handler: 
/home/aimee/CorsixTH/CorsixTH/Lua/audio.lua:577: Could not load music file 'Sound/Midi/DOCTOR.XMI' (Couldn't open /etc/timidity++/freepats.cfg)
stack traceback:
	[C]: in function 'coroutine.yield'
	/home/aimee/CorsixTH/CorsixTH/Lua/app.lua:1031: in function </home/aimee/CorsixTH/CorsixTH/Lua/app.lua:1026>
Warning: Trying to remove nonexistent room build callback (function: 0x55c4d4c0e820) from humanoid (table: 0x55c4d50dfd50).
Warning: Trying to remove nonexistent room remove callback (function: 0x55c4d428edf0) from humanoid (table: 0x55c4d50dfd50).
Warning: Trying to remove nonexistent staff callback (function: 0x55c4d4b9acf0) from humanoid (table: 0x55c4d50dfd50).
Warning: Trying to remove nonexistent room build callback (function: 0x55c4d40f2cd0) from humanoid (table: 0x55c4d26b18f0).
Warning: Trying to remove nonexistent room remove callback (function: 0x55c4d49ac480) from humanoid (table: 0x55c4d26b18f0).
Warning: Trying to remove nonexistent staff callback (function: 0x55c4d4f619b0) from humanoid (table: 0x55c4d26b18f0).
Warning: Trying to remove nonexistent room build callback (function: 0x55c4d3d712f0) from humanoid (table: 0x55c4d4f70c90).
Warning: Trying to remove nonexistent room remove callback (function: 0x55c4d3356a20) from humanoid (table: 0x55c4d4f70c90).
Warning: Trying to remove nonexistent staff callback (function: 0x55c4d3d373e0) from humanoid (table: 0x55c4d4f70c90).
Warning: Trying to remove nonexistent room build callback (function: 0x55c4d4cea740) from humanoid (table: 0x55c4d2b2bc30).
Warning: Trying to remove nonexistent room remove callback (function: 0x55c4d439dfa0) from humanoid (table: 0x55c4d2b2bc30).
Warning: Trying to remove nonexistent staff callback (function: 0x55c4d2e688b0) from humanoid (table: 0x55c4d2b2bc30).
Warning: Trying to remove nonexistent room build callback (function: 0x55c4d447c950) from humanoid (table: 0x55c4d496d100).
Warning: Trying to remove nonexistent room remove callback (function: 0x55c4d41e1f90) from humanoid (table: 0x55c4d496d100).
Warning: Trying to remove nonexistent staff callback (function: 0x55c4d48ce950) from humanoid (table: 0x55c4d496d100).
Warning: Trying to remove nonexistent room build callback (function: 0x55c4d5104e10) from humanoid (table: 0x55c4d4dfefa0).
Warning: Trying to remove nonexistent room remove callback (function: 0x55c4d3b101d0) from humanoid (table: 0x55c4d4dfefa0).
Warning: Trying to remove nonexistent staff callback (function: 0x55c4d3d0e0a0) from humanoid (table: 0x55c4d4dfefa0).
Error in timer handler: 
...aimee/CorsixTH/CorsixTH/Lua/entities/humanoids/staff.lua:683: attempt to perform arithmetic on a nil value (field 'fatigue')
stack traceback:
	...aimee/CorsixTH/CorsixTH/Lua/entities/humanoids/staff.lua:683: in method 'getServiceQuality'
	/home/aimee/CorsixTH/CorsixTH/Lua/room.lua:1043: in method 'getStaffServiceQuality'
	...mee/CorsixTH/CorsixTH/Lua/entities/humanoids/patient.lua:310: in method 'isTreatmentEffective'
	...mee/CorsixTH/CorsixTH/Lua/entities/humanoids/patient.lua:273: in method 'treatDisease'
	/home/aimee/CorsixTH/CorsixTH/Lua/room.lua:194: in method 'dealtWithPatient'
	/home/aimee/CorsixTH/CorsixTH/Lua/rooms/inflation.lua:67: in field 'after_use'
	...sixTH/CorsixTH/Lua/humanoid_actions/multi_use_object.lua:316: in local 'timer_function'
	/home/aimee/CorsixTH/CorsixTH/Lua/entity.lua:216: in method 'tick'
	/home/aimee/CorsixTH/CorsixTH/Lua/world.lua:1081: in method 'onTick'
	/home/aimee/CorsixTH/CorsixTH/Lua/app.lua:1131: in function </home/aimee/CorsixTH/CorsixTH/Lua/app.lua:1128>
	(...tail calls...)
	/home/aimee/CorsixTH/CorsixTH/Lua/app.lua:1031: in function </home/aimee/CorsixTH/CorsixTH/Lua/app.lua:1026>
```

### PR DESCRIPTION
**Pull request by TheCycoONE**
*Fixes #1924*

**Describe what the proposed change does**
Does not nil out the fatigue attribute of doctor's when they are fired. Avoid performing any actions on fired doctors.

### CODE REVIEW

File: CorsixTH/Lua/entities/humanoid.lua [hunk 1]
```diff
@@ -754,7 +754,7 @@ end
 -- feeling of warmth accordingly. Returns whether the calling function should proceed.
 function Humanoid:tickDay()
   -- No use doing anything if we're going home
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoid.lua:756]:
```suggestion
  -- No use doing anything if we're going home/fired (or dead)
```

**Review by lewri — APPROVED** [review]

File: CorsixTH/Lua/entities/humanoids/staff.lua [hunk 2]
```diff
@@ -35,6 +35,9 @@ end
 
 function Staff:tickDay()
   Humanoid.tickDay(self)
+  if self.fired or self.dead then
+    return
+  end
```
Comment (mugmuggy) [inline CorsixTH/Lua/entities/humanoids/staff.lua:40]: The function comment on Humanoid:tickDay states that the result of it (returns boolean) should determine the processing of the caller, ie if not Humanoid.tickDay(self) then return false and same in Doctor with Staff class. Staff:tickDay doesn't return boolean (nor does Doctor but its result is not used anyway).

Patient has that logic, where it does waiting logic then does the Humand.tickDay which allows it to abort out of Patient:tickDay based on that result. As you already added self.fired to Humanoid:tickDay then it could serve the same purpose but Staff:tickDay would then need to return true/false for Doctor class.

**Comment by TheCycoONE** [comment]
Thanks mugmuggy. I'm not really happy about leaking fired. I think I'd prefer to additionally set going_home on the staff. I'll take some more time tonight to look at the bool result too. Otherwise sound? Any ideas on the action bug where Despawn gets lost on multiobject

**Comment by mugmuggy** [comment]
Indeed if we can set going_home as well it would simplify things, VIP etc uses it, so its probaly ok in the greater scheme of things. I also thought the leak was probably not the best and then thought we could move that check into a method we call and override in staff, ie a 'canTickDay' so it doesn't leak.

**Comment by TheCycoONE** [comment]
For now I went with `going_home` and applied mugmuggy's other suggestions.

**Comment by lewri** [comment]
I feel like you should also be checking handymen and nurses. Especially in theory a nurse could crash the game too with the cast remover.

**Review by mugmuggy — APPROVED** [review]
