### PR TITLE
[RDY] VIP Overhaul

### LINKED ISSUE #1616: VIP praise lacks variation
#### Describe the issue
I believe this may be a resurfacing of #498 (was marked fixed) but through my entire playthrough every single VIP that has entered my hospital has given the $2000 reward.

Now either I'm very good at keep my hospital running (unlikely), or there may be a problem with the VIP appraisal variation.

For the purposes of testing this I sacked all my handymen just before the VIP enters, sacked all but one nurse, and 2 doctors to make the hospital horribly understaffed. Then even after all of this the VIP still gives out the $2000 award.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Speed through game until VIP leaves to get the award notice.

#### Save Game
https://www.dropbox.com/s/fsasy79j8gs6m5v/vip_test063.sav?dl=0

#### Expected Behavior
On the uploaded save I would've expected the VIP rating to have gone down sharply. In the original, VIP rating was usually quite senstive to everything.

#### System Information
**CorsixTH Version:** 0.63

**Operating System:** W10

**Theme Hospital Version:** GOG

### Additional Info
I believe the previous issue did mention the lack of rats can take away a level of persuasion on the VIP's rating. But it seems like rats either are grossly outweighed in a VIP rating; or other items are not taking full effect.

### PR DESCRIPTION
**Pull request by lewri**
Will close #1616 
PR will eventually be a completed overhaul of the VIP system. It will make use of the original evaluation criteria as done by mugmuggy as well as a heap of ones currently used. Of course, stuff can be added in still or swapped as needed. However, the more criteria added the harder it becomes to balance (note its not even fully balanced right now).

**Things still to do:**
- ~~Add back in explosion rating, and hit user hard if one happens.~~ Cancelled
-  ~~Make VIP visit a finite number of rooms (may need help with that part). Ideally it needs to get a list of all rooms available, then randomly select an amount for the VIP to go to.~~ DONE
- ~~Add back in cure ratios~~ DONE
- ~~Handle old saves if VIP is leaving~~ DONE
- ~~Balancing of ratings. I am currently looking into real-world factors for this.~~

**Current problems:**
~~*Line 382:  self.vip_rating = self.vip_rating + 4* does not always seem to execute in my tests. I have no idea why, could be a Lua issue?~~ No longer an issue
*VIP:tickday* keeps executing evaluation steps while leaving the hospital. Not a serious issue but may be better to sqaush it while VIP leaves?
~~*VIP announcement* does not happen if there are too many announcements queued for the receptionist (or an announcement happens as the VIP enters) (Mainly seen where game speed is 5)~~ Deemed non-issue

I have made it so the branch can have commits pushed by TheCycoONE if required. 

There are also a lot of comments and debug lines at the moment in vip.lua . These will be eventually removed before coming out of draft. But for now they're just there to help me understand how every evaluation is balanced.

### CODE REVIEW

**Comment by TheCycoONE** [comment]
Explosion rating could be controversial, people already complain that earthquakes/explosions are too harsh for permanently taking up space.

**Comment by TheCycoONE** [comment]
This will (most likely) miss 0.64. I would have put out a release candidate already but I ran into some trouble with vcpkg. That will just give us more reason to ship 0.65 in a timely manner.

**Comment by lewri** [comment]
Pretty sure earthquakes have always been impactful in this game even in the original. Except at least in CorsixTH machines won't right up explode out of nowhere during the earthquake. There appears to be some grace period there.

**Comment by lewri** [comment]
I loaded up the original to see how the VIP moves around the hospital.
It looks like the VIP looks at rooms by plot. Then it works out how many rooms they will visit in the plot. Or they look at how many rooms are within their vicinity and decide which rooms to visit.

I built total 24 rooms, VIP visited 9 across 4 plots.
I then built 10 rooms, VIP visited 4 (or 5 in some reloads) across 1 plot.

There are then three solutions to simulate this:
1. We get rooms inside each plot for the VIP. Then allocate the VIP a random number of rooms to visit each plot.
2. We get rooms on a room by room basis. Then when the VIP goes to get next room, we do a math.random to find out if the VIP will go to that room. If not, we roll for the next room etc.
3. We get the next room by scanning the surrounding tiles the VIP currently is at. (will need an initial room) We then choose a room from that at random and make sure it can't be visited again. Then when there are no rooms in surrounding tiles left, the VIP goes to the next plot.

Personally I would probably go for option two. as it would be the most straightforward. Again, it would need an initial room to ensure we don't just turn up and leave. The amount of rooms the VIP visits seems to be 40-50%, so we should set the chance of visiting a room to that.

**Comment by lewri** [comment]
Option 2 now implemented (Room randomiser).

Random variable now checks if VIP will visit room. 40% chance on first roll, increasing by 10% each failed roll.

First room in hospital is always visited; in the highly unlikely event the randomiser fails for every other room.

**Comment by mugmuggy** [comment]
I mentioned those 2 flags in the issue. I believe they are a is a room flag and a must visit.
Must visit rooms appear to be ward, op theatre and dna fixer and veto the randomiser (its just 50/50 also). The first flag just is the object index to use in the build screen dialog essentially. This is due to the rooms starting at index 7 thats all.

**Comment by lewri** [comment]
I don't think the current room setup carry a must visit marker on them do they? I mean we can simulate it at least. 

When you say veto the randomiser, what alternative did you have it mind? 
I know the drawback of the randomiser is the VIP doesn't gravitate to the next nearest room. But even in CorsixTH right now the VIP does that. I'm not sure how much it matters

**Comment by lewri** [comment]
Flag updated

**Comment by lewri** [comment]
There are two things Travis is complaining about I'm not overly sure how to fix.

```
Checking CorsixTH/Lua/entities/humanoids/vip.lua  1 warning

    CorsixTH/Lua/entities/humanoids/vip.lua:320:10: (W213) unused loop variable staff

Checking CorsixTH/Lua/hospital.lua                1 warning

    CorsixTH/Lua/hospital.lua:1951:25: (W113) accessing undefined variable attributes
```

For the second one, the function works but Travis isn't happy about it...

**Comment by lewri** [comment]
**Handle old saves if VIP is leaving** has been done. Not the best solution but it avoids any unnecessary punishment on the user because they were using an old version.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 1]
```diff
@@ -378,13 +379,14 @@ function Vip:setVIPRating()
...
+  print("num deaths " .. self.hospital.num_deaths .. " enter deaths " .. self.enter_deaths)
   local visitors_diff = self.hospital.num_visitors - self.enter_visitors
-  if death_diff == 0 then
-    if visitors_diff ~= 0 then --if there have been no new patients, no +/- points
-      self.vip_rating = self.vip_rating - 4
-    end
-  else
-    local death_ratio = visitors_diff / death_diff
+  print("num visitors " .. self.hospital.num_visitors .. " enter visitors " .. self.enter_visitors)
+  local death_ratio = visitors_diff / death_diff
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:385]: Yes I agree. I think that's just how the code was written. Then the original coder at the time made it so divide by 0 outputs would give the right rating change.
I'll see what can be done to not do this/handle zero numbers.

[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua]: New checks implemented before the divide by 0. I missed one case but patching now

**Comment by lewri** [comment]
The comments on vip.lua Lines 21-54 will be removed once all reviews are done and people are happy. It is there at the moment just to summarise each VIP rating factor.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 2]
```diff
@@ -202,268 +290,240 @@ function Vip:announce()
...
-end
 
-function Vip:evaluateEmergency(success)
-  -- Make sure that the VIP is still actually in the process of evaluation
-  if not self.going_home then
-    if success then
-      self.vip_rating = self.vip_rating + 10
+--[[-- Group factor 3: Patients--]]
+  -- first check we had patients this visit
+  local visitors_diff = self.hospital.num_visitors + self.enter_patients - self.enter_visitors
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/vip.lua:338]: Not clear why we care about visitor_diff , and I don't think this line gets the visitor diff. Don't we just care that there are patients in the hospital?

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 3]
```diff
@@ -202,268 +290,240 @@ function Vip:announce()
...
+  -- Low room numbers incur a penalty
+  if count_rooms < 1 then
+    self.vip_rating = self.vip_rating + 4
+  else
+    if count_rooms < 3 then
+      self.vip_rating = self.vip_rating + 1
+    end
+    -- Room decor average
+    local avg_room_eval = self.room_eval / self.num_visited_rooms
+    local room_eval_rangemap = {
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/vip.lua:464]: possibly too harsh with the plant tweak above.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 4]
```diff
@@ -202,268 +290,240 @@ function Vip:announce()
...
+    self.rep_reward = rep_change[1]
   else
-    -- custom level, it has no level number. Default back to one.
-    self.cash_reward = math.round(1 * self.vip_rating) * 10
+    self.rep_reward = rep_change[self.vip_rating]
   end
-  if self.cash_reward > 2000 then
-    self.cash_reward = 2000
+  if self.vip_rating <= 1 then
+  self.vip_message = 1
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/vip.lua:521]: indent

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 5]
```diff
@@ -202,268 +290,240 @@ function Vip:announce()
...
+  elseif self.vip_rating <= 1 then
+    self.cash_reward = rewards[1]
+  else
+    self.cash_reward = rewards[self.vip_rating]
   end
-
-  -- set the cash reward value
-  if tonumber(self.world.map.level_number) then
-    self.cash_reward = math.round(self.world.map.level_number * self.vip_rating) * 10
+  if self.vip_rating >= 15 then
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/vip.lua:513]: If you wanted to save code in this block:
```lua
-- bound vip rating
self.vip_rating = self.vip_rating > 15 and 15 or self.vip_rating
self.vip_rating = self.vip_rating < 1 and 1 or self.vip_rating
self.cash_reward = rewards[self.vip_rating] or 0
self.rep_reward = rep_change[self.vip_rating]
self.vip_message = self.vip_rating -- not sure why you want a different value here
```

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 6]
```diff
@@ -482,7 +542,45 @@ function Vip:afterLoad(old, new)
...
+      {upper = 3, value = 2},
+      {upper = 4, value = 3},
+      {upper = 5, value = 4},
+      {value = 5}
+      }
+      self.room_visit_chance = rangeMapLookup(roll_ratio, roll_ratio_rangemap)
+    else
+      self.room_visit_chance = 1
+    end
+    self.enter_patients = #self.hospital.patients - self.hospital.num_visitors + self.enter_visitors
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/vip.lua:562]: Why are you adding enter_visitors here?

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 7]
```diff
@@ -34,25 +70,27 @@ function Vip:Vip(...)
...
   self.enter_visitors = 0
+  self.enter_patients = 0
   self.enter_explosions = 0
-  self.enter_cures = 0
   self.num_vomit_noninducing = 0
   self.num_vomit_inducing = 0
   self.found_vomit = {}
   self.num_visited_rooms = 0
   self.room_eval = 0
+  self.room_visit_chance = 1
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:88]: You're right. This factor is actually set here. 

https://github.com/CorsixTH/CorsixTH/blob/8d93ba7186763c750dbe8e6fd14751774dd30520/CorsixTH/Lua/world.lua#L554-L563

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 8]
```diff
@@ -137,51 +243,33 @@ function Vip:onDestroy()
...
+        {text = _S.fax.vip_visit_result.ordered_remarks[self.vip_message]},
         {text = _S.fax.vip_visit_result.rep_boost},
         {text = _S.fax.vip_visit_result.cash_grant:format(self.cash_reward)},
         choices = {{text = _S.fax.vip_visit_result.close_text, choice = "close"}}
       }
-    end
+  elseif self.vip_rating >=8 and self.vip_rating < 11 then
+    -- dont tell player about any rep change in this range
+    self.last_hospital.reputation = self.last_hospital.reputation + self.rep_reward
+      message = {
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:260]: Will be resolved next revision

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 2 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:338]: The difficulty I noticed with visitors_diff is in its old definition it only counted who entered from when the VIP arrived -- they didn't care about who was already here (and thus usually the people who are cured during the visit). Therefore it would cause a bias on the other factors. 

The variable should be renamed to reflect that it no longer just pulls who entered over the visit. It counts who came + who was already here

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 6 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:562]: This part is trying to account for if we have more patients in the hospital than visitors. An attempt to balance self.enter_patients so the number is more realistic.

File: CorsixTH/Lua/hospital.lua [hunk 9]
```diff
@@ -1730,7 +1723,8 @@ function Hospital:hasStaffOfCategory(category)
       if (category == "Psychiatrist" and staff.profile.is_psychiatrist >= 1.0) or
           (category == "Surgeon" and staff.profile.is_surgeon >= 1.0) or
           (category == "Researcher" and staff.profile.is_researcher >= 1.0) or
-          (category == "Consultant" and staff.profile.is_consultant) then
+          (category == "Consultant" and staff.profile.is_consultant) or
+          (category == "Junior" and staff.profile.is_junior) then
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/hospital.lua:1727]: Can you explain what that is? Or where it is

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 5 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:513]: Added for next revision

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 7 above)
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:88]: An alternative could be to change to this
```lua
if #self.rooms > 79 then
  vip.room_visit_chance = math.floor(#self.rooms / 40 - 0.5) -1
end
```

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 2 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/entities/humanoids/vip.lua:338]: I don't think it does that right now. It counts who is currently there plus who came.

If you only care about the point in time the VIP evaluation happens you don't need to store any counts in the vip.

File: CorsixTH/Lua/hospital.lua (hunk 9 above)
[the remark this answers is not in the document]
Comment (TheCycoONE) [reply CorsixTH/Lua/hospital.lua:1727]: The comments above this function.

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 2 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:338]: The self.enter_patients measures who is in the hospital when the VIP arrives (done in world.lua). Then it adds on the number of visitors who came to the hospital during the visit. It doesn't check who is there at the time of eval.

Comment (TheCycoONE) [reply CorsixTH/Lua/entities/humanoids/vip.lua:338]: Talk on irc later.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 10]
```diff
@@ -18,6 +18,42 @@ LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE. --]]
 
+--[[ Section is my general notes and will be removed eventually.
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:21]: I can do. I'd probably take out the border though. I think that part was for my own benefit.

**Comment by lewri** [comment]
@TheCycoONE have you had a chance to play with these changes yet? Imo I still think it can be a little lenient at times. You still have to kind of majorly screw something up to get the worse ratings.

Also why I've held off changing the calculations for plants.

**Comment by TheCycoONE** [comment]
Curious about travis getting stuck. What sort of scores are you getting - I wouldn't trust myself with balance questions.

**Comment by lewri** [comment]
Every time I play it on my normal saves it comes out at max rewards. That's why I'd like to ask if someone else could play with it. @mugmuggy I know you had a test out a few days ago, what ratings did you get?

**Comment by TheCycoONE** [comment]
I think the research penalty shouldn't be tied up in the room rating where it will be diminished to nothing. Can record that we saw it and tack a fixed amount on the rating at the end.

I also think plants should be nerfed like I said. -3 for good plants feels a bit much. But maybe you can print out your stat list for your hospital and past it here.

**Comment by mugmuggy** [comment]
@lewri, I didn't get through to actually checking the scores. I extracted the scores and I believe the best possible score for vip_rating before applying to the scale is -6 and the highest is 33.
With the vip_rating randomisation the highest scores are -1 to -6 and then the lowest are 28 and 33.

Thus when you clamp it to the 1-15 range. You'll want to quickly check what vip_rating is.

I think when you've since added the other evaulations you didn't bump the vip_rating initialisation value up. I counted 9, -1 scores. Thus you'd want to centre around that. As you are also using random(0,5) thats 6 values you'd want to choose 12 or 13 instead of 8. 12 will bias them more positively, 13 more negatively.

**Comment by lewri** [comment]
Changing the initial constant to 12 is much better varied now. Still haven't tested the plant change yet.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 11]
```diff
@@ -202,268 +288,224 @@ function Vip:announce()
...
-      self.vip_rating = self.vip_rating + 20
+    -- get patient warmth
+    local avg_warmth = self.hospital:getAveragePatientAttribute("warmth", nil)
+    -- punish if too cold/hot
+    if avg_warmth then
+      local patients_warmth_ratio_rangemap = {
+        {upper = 0.21, value = 2},
+        {upper = 0.36, value = -1},
+        {upper = 0.43, value = 1},
+        {value = 2}
```
Comment (mugmuggy) [inline CorsixTH/Lua/entities/humanoids/vip.lua:354]: Do you technically need another lower range value here, ie 0.21 is only 0.5 degress less than the comfort range, but if 3 degrees (0.42) hotter than comfortable, its penalised half as much, or just remove the 0.43 range?

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 12]
```diff
@@ -202,268 +287,222 @@ function Vip:announce()
...
-      break
     end
-
-    if object.strength then
-      if object.strength > (object.object_type.default_strength / 2) then
-        self.room_eval = self.room_eval + 1
-      else
-        self.room_eval = self.room_eval - 3
-      end
+    -- Average all staff tiredness. If above tiredness level award 1, else -1
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/vip.lua:321]: Remove award refs as we have them at the top

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 13]
```diff
@@ -202,268 +287,222 @@ function Vip:announce()
...
-    {upper = 10, value = -12},
-    {upper = 12, value = -16},
-                {value = -20}
-  }
-  self.vip_rating = self.vip_rating + rangeMapLookup(self.num_vomit_inducing, inducing_ratio_rangemap)
 
-  -- if there were explosions, hit the user hard
-  if self.hospital.num_explosions ~= self.enter_explosions then
-    self.vip_rating = self.vip_rating - 70
+    -- check for the average queue length
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/vip.lua:410]: Need to update this comment

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 14]
```diff
@@ -202,268 +287,222 @@ function Vip:announce()
...
 
-  -- give the rating between 1 and 5
-  local rating_ratio_rangemap = {
-    {upper = 25, value = 1},
-    {upper = 45, value = 2},
-    {upper = 65, value = 3},
-    {upper = 85, value = 4},
-                {value = 5}
+--[[--Finalise score--]]
+  --documented rewards.
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/vip.lua:471]: Remove fullstop

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 15]
```diff
@@ -482,7 +521,39 @@ function Vip:afterLoad(old, new)
...
+    self.room_eval = 0
+    self.num_visited_rooms = 0
+    if #self.world.rooms > 79 then
+      self.room_visit_chance = math.floor(#self.world.rooms / 40)
+    else
+      self.room_visit_chance = 1
+    end
+    -- if our hospital has more patients than counted visitors adjust enter_patients
+    self.enter_patients = #self.hospital.patients + self.enter_visitors - self.hospital.num_visitors
+    if self.enter_patients <0 then
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/vip.lua:536]: ``self.enter_patients < 0 then``

File: CorsixTH/Lua/languages/english.lua [hunk 16]
```diff
@@ -874,6 +874,28 @@ map_editor_window = {
   }
 }
 
+fax = {
+vip_visit_result = {
+  ordered_remarks = {
```
Comment (lewri) [inline CorsixTH/Lua/languages/english.lua:879]: @TheCycoONE could this pose a potential copyright risk? Or is this kind of use ok?

Comment (TheCycoONE) [reply CorsixTH/Lua/languages/english.lua:879]: IANAL. We've been tredding carefully to date. I think to make corrections to an insubstantial part of the piece and requiring the purchase of the original puts us in the clear. Better if we wrote our own blurb though.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 17]
```diff
@@ -126,6 +180,55 @@ function Vip:goHome()
...
+      end
+    end
+  end
+  --check whether we had more good or bad plants
+  if room_plant < 0 then
+    self.room_eval = self.room_eval - 1
+  elseif room_plant > 0 then
+    self.room_eval = self.room_eval + 1
+  end
+  self:getNextRoom()
```
Comment (sadger) [inline CorsixTH/Lua/entities/humanoids/vip.lua:228]: Why is getNextRoom now called after evaluating a room? It's also done in tickDay? Do we actually need both?

Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:228]: Called if the VIP is waiting in tickDay. I think the addition here means the VIP isn't waiting around anymore between rooms.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 18]
```diff
@@ -126,6 +180,55 @@ function Vip:goHome()
...
+      self.vip_rating = self.vip_rating + 6
+    end
+  end
+  -- evaluate the room we're currently looking at
+  for object, _ in pairs(room.objects) do
+    if object.object_type.id == "extinguisher" and room_extinguisher == 0 then
+      self.room_eval = self.room_eval + 1
+      -- only count this object type once
+      room_extinguisher = 1
+    elseif object.object_type.id == "plant" then
```
Comment (sadger) [inline CorsixTH/Lua/entities/humanoids/vip.lua:202]: This is the state of the plant.  After talking to @Alberth289346  to make it easier to read and to test consider adding plant:isDying() function or similar.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 19]
```diff
@@ -126,6 +180,55 @@ function Vip:goHome()
...
+      elseif object.days_left <= 3 then
+        room_plant = room_plant - 1
+      end
+    elseif object.object_type.id == "bin" and room_bin == 0 then
+      self.room_eval = self.room_eval + 1
+      -- only count this object type once
+      room_bin = 1
+    end
+
+    if object.strength then
```
Comment (sadger) [inline CorsixTH/Lua/entities/humanoids/vip.lua:214]: Same with the object strength - maybe object:isAlmostBroken() or something?

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 18 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:202]: We have Plant:needsWatering()

```lua
function Plant:needsWatering()
  if self.current_state == 0 then
    if self.days_left < 10 then
      return true
    end
  else
    return true
  end
end
```

Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:202]: Though I think there's an implication the player is unfairly punished because a plan just called for watering and handyman hasn't been given a chance to respond yet

File: CorsixTH/Lua/entities/humanoids/vip.lua (hunk 19 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:214]: This test seems to look at if the machine is getting old rather than technically broken. In other words it's lost 50% of its strength from wear and not been replaced.  Though I didn't write this bit of code originally. 

If we were looking at its health then we could call Machine:getRemainingUses()

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 20]
```diff
@@ -202,268 +283,222 @@ function Vip:announce()
...
-    {upper = 0.80, value = 3},
-                  {value = 5}
-  }
-  self.vip_rating = self.vip_rating + rangeMapLookup(self.attributes["warmth"], heat_ratio_rangemap)
-
-  -- check the seating : standing ratio of waiting patients
-  -- find all the patients who are currently waiting around
-  local sum_sitting, sum_standing = self.hospital:countSittingStanding()
-  if sum_sitting >= sum_standing then
+--[[--Group factor 4: Doctor ratios--]]
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/vip.lua:420]: Needs updating for PR #1684

File: CorsixTH/Lua/hospital.lua [hunk 21]
```diff
@@ -1719,7 +1712,7 @@ end
 --! Checks if the hospital employs staff of a given category.
```
Comment (lewri) [inline CorsixTH/Lua/hospital.lua:1712]: Needs updating for PR #1684

**Comment by TheCycoONE** [comment]
Albert's PR has landed

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 22]
```diff
@@ -1,4 +1,4 @@
---[[ Copyright (c) 2011 John Pirie
+--[[ Copyright (c) 2011-2020 John Pirie, lewri
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/vip.lua:1]: Add a separate copyright line instead. jpirie hasn't been active lately.

File: CorsixTH/Lua/hospital.lua [hunk 23]
```diff
@@ -1948,14 +1942,17 @@ function Hospital:getAverageStaffAttribute(attribute, default_value)
   local sum = 0
   local count = 0
   for _, staff in ipairs(self.staff) do
+    if staff.attributes[attribute] then
     sum = sum + staff.attributes[attribute]
```
Comment (TheCycoONE) [inline CorsixTH/Lua/hospital.lua:1946]: Indentation

File: CorsixTH/Lua/hospital.lua [hunk 24]
```diff
@@ -1948,14 +1942,17 @@ function Hospital:getAverageStaffAttribute(attribute, default_value)
...
     count = count + 1
+    end
   end
 
   if count == 0 then
     return default_value
   else
     return sum / count
+
```
Comment (TheCycoONE) [inline CorsixTH/Lua/hospital.lua:1955]: `return count == 0 and default_value or sum / count`

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 25]
```diff
@@ -0,0 +1,140 @@
+--[[ Copyright (c) 2020 <tbc>
```
Comment (lewri) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:1]: I'll suggest we use your name here @sadger as the spec file is your baby. But happy to help as needed on irc.

**Comment by Alberth289346** [comment]
Why working on the VIP code, could you change the reputation update lines like
``` lua
self.last_hospital.reputation = self.last_hospital.reputation + 20
```
lines to `self.last_hospital.changeReputation("vip_visit", nil, <amount>)` ?

Then everything changes reputation through that function.

The only possible problem with the change is that the function checks whether it is allowed to change reputation (it becomes harder to get very low or very high reputation), but I don't think that's a problem.

**Comment by lewri** [comment]
Thanks for pointing it out. While it would make sense to use this function you're right that the things the function does means our VIP visit could have no reputation effect (even though our fax says our rep changed). So in this case keeping the rep inside the VIP is probably best (rather than recoding changeReputation).

**Comment by lewri** [comment]
Prep coded for #1699 now to wait for it to land.

**Comment by TheCycoONE** [comment]
That PR has been merged

**Comment by TheCycoONE** [comment]
You now have unrelated work in this branch - worse it's an unresolved merge conflict. Suggest resetting to 0e86b

File: .github/ISSUE_TEMPLATE/bug_report.md [hunk 26]
```diff
@@ -1,7 +1,11 @@
 ---
 name: Bug report
 about: Create a report to help us improve
+<<<<<<< HEAD
 title: "[Bug] Give a summary of the problem"
+=======
+title: "[Bug] Summary of problem"
+>>>>>>> Update issue templates
```
Comment (Alberth289346) [inline .github/ISSUE_TEMPLATE/bug_report.md]: A merge conflict hasn't been solved here.

The "=====" line is the divider, the lines up until the "<<<<" line is what existed (ie HEAD), the lines down until ">>>" is new in "Update issue templates"  branch(?)

To you the task of editing the file, deleting all bad lines and the administrative lines (===, <<<, and >>>), and editing the changed lines to what it should be.

Normally you do this before adding a file with a conflict to git staging

File: .github/ISSUE_TEMPLATE/bug_report.md [hunk 27]
```diff
@@ -18,9 +22,15 @@ assignees: ''
...
 You can upload your save by putting it in zip file, then copy/pasting it directly into this text area. You can also click the "Attach files by dragging & dropping, selecting or pasting them" text at the bottom to upload the zip file.
 Alternatively, you can use an external source such as Google Drive, Dropbox, or OneDrive and sharing the public link below to access your save game. The most important thing is to not remove these files after you upload them. -->
+=======
+<!-- It is often useful for us if you have a save game from shortly before the issue occurs that can be used to recreate the problem. Sometimes a save that shows the issue happening may be useful as well. As GitHub currently only supports uploading of images, you will have to upload your your savegames to
+an another source such as Google Drive: https://drive.google.com , Dropbox: https://dropbox.com , or OneDrive: https://onedrive.live.com . Add the link to the file to your issue and make the file(s) public, so we can access your gamelog or savegame. The most important thing is to not remove these files after you uploaded them!
+-->
+>>>>>>> Update issue templates
```
Comment (Alberth289346) [inline .github/ISSUE_TEMPLATE/bug_report.md]: And other missed merge conflict to resolve.

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua (hunk 25 above)
Comment (Alberth289346) [reply CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:1]: Copy from epidemic.lua

Comment (sadger) [reply CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:1]: Fine by me :+1:

**Comment by lewri** [comment]
You're right. The issue templates update keeps creeping back in every time I rebase. I'm not sure why GitHub desktop isn't dealing with the diff even after telling it which one to use.

I don't use git command line. But if sadger does he might be able to fix it as he's in my fork.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 28]
```diff
@@ -126,62 +181,85 @@ function Vip:goHome()
...
+      room_extinguisher = 1
+    elseif object.object_type.id == "plant" then
+      room_plant = object:isDying() and room_plant - 1 or room_plant + 1
+    elseif object.object_type.id == "bin" and room_bin == 0 then
+      self.room_eval = self.room_eval + 1
+      -- only count this object type once
+      room_bin = 1
+    end
+
+    if object.strength then
```
Comment (sadger) [inline CorsixTH/Lua/entities/humanoids/vip.lua:211]: Should we use object.object_type.id == "machine" here instead of checking for a strength attribute considering we've abstracted from this in the evaluation?

Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/vip.lua:211]: In the current code we don't have a flag for an object being a machine except by its "strength". Not sure if we want to tag all machines with an identifier though as a machine.

**Comment by TheCycoONE** [comment]
Yeah, I'm good with this, you'll want to change the savegame version everywhere again.

File: CorsixTH/Lua/world.lua [hunk 29]
```diff
@@ -551,9 +551,10 @@ function World:spawnVIP(name)
   vip.enter_deaths = hospital.num_deaths
   vip.enter_visitors = hospital.num_visitors
   vip.enter_cures = hospital.num_cured
-
-  vip.enter_explosions = hospital.num_explosions
-
+  vip.enter_patients = #hospital.patients
+  if #self.rooms > 79 then
+    vip.room_visit_chance = math.floor(#self.rooms / 40)
```
Comment (TheCycoONE) [inline CorsixTH/Lua/world.lua:556]: 40 is a magic number? document it please

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 30]
```diff
@@ -482,7 +508,39 @@ function Vip:afterLoad(old, new)
   if old < 79 then
     self.name = self.hospital.visitingVIP
   end
+  if old < 142 then
```
Comment (TheCycoONE) [inline CorsixTH/Lua/entities/humanoids/vip.lua:511]: Will need to be bumped

File: CorsixTH/Lua/world.lua [hunk 31]
```diff
@@ -551,9 +551,10 @@ function World:spawnVIP(name)
   vip.enter_deaths = hospital.num_deaths
   vip.enter_visitors = hospital.num_visitors
   vip.enter_cures = hospital.num_cured
-
-  vip.enter_explosions = hospital.num_explosions
-
+  vip.enter_patients = #hospital.patients
+  if #self.rooms > 79 then
```
Comment (TheCycoONE) [inline CorsixTH/Lua/world.lua:555]: A couple magic numbers here, please document them (and/or use local 'constants' with names so they are self documenting)

**Comment by lewri** [comment]
@sadger I will hold off making this ready until you confirm if you wanted to add more luatests.

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 32]
```diff
@@ -516,7 +516,7 @@ function Vip:afterLoad(old, new)
     -- VIP's room visit chance is 50% (1/2) if total rooms in hospital is less than 80, else decided by total rooms / 40 (1/3, 1/4 etc)
     local rooms_threshold = 79
     if #self.world.rooms > rooms_threshold then
-      vip.room_visit_chance = math.floor(#self.world.rooms / 40)
+      self.room_visit_chance = math.floor(#self.world.rooms / 40)
     else
       self.room_visit_chance = 1
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/humanoids/vip.lua:521]: How is `1` equal to `50%`?

BTW: The simpler solution to computing this is `self.room_visit_chance = math.max(1, math.floor(#self.world.rooms / 40))`

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 33]
```diff
@@ -30,8 +30,10 @@ local function getVip()
   return Vip(animation)
 end
 
+
 local function create_room(name, args)
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:35]: No empty line here

File: CorsixTH/Lua/entities/humanoids/vip.lua [hunk 34]
```diff
@@ -374,6 +375,7 @@ function Vip:setVIPRating()
       self.vip_rating = self.vip_rating + rangeMapLookup(death_ratio, death_ratio_rangemap)
     end
 
+
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/humanoids/vip.lua:378]: No double empty lines

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 35]
```diff
@@ -74,6 +76,50 @@ local function create_room(name, args)
...
+end
+
+local function create_hospital(args)
+
+  args = args or {}
+
+  local hospital = {
+    num_vips_ty = 0,
+    staff = {
+
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:98]: no empty line here

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 36]
```diff
@@ -74,6 +76,50 @@ local function create_room(name, args)
...
+    },
+    -- Always return default value for average attribute
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:100]: If you want, before here could be an empty line

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 37]
```diff
@@ -74,6 +76,50 @@ local function create_room(name, args)
...
+    getAveragePatientAttribute = function(_, attribute, default) return default end,
+    countSittingStanding = function(_)
+      sitting = args.sitting_patients or 0
+      standing = args.standing_patients or 0
+      return sitting,standing
+    end,
+    countStaffOfCategory = function(_, category)
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:107]: and before here too

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 38]
```diff
@@ -74,6 +76,50 @@ local function create_room(name, args)
...
+
+  for i=1, args.num_rooms do
+    world.rooms[i] = create_room("room" .. i)
+  end
+
+  return world
+end
+
+local function create_hospital(args)
+
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:92]: no empty line here

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 39]
```diff
@@ -74,6 +76,50 @@ local function create_room(name, args)
...
+    end,
+    countStaffOfCategory = function(_, category)
+      if category == "Doctor" then
+        return args.doctors or 0
+      elseif category == "Consultant" then
+        return args.consultants or 0
+      elseif category == "Junior" then
+        return args.juniors or 0
+      end
+  end
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:115]: somewhere above an indent is broken or a dedent is missing

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 40]
```diff
@@ -74,6 +76,50 @@ local function create_room(name, args)
...
+  }
+
+  return hospital
+
+end
+
+
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:122]: no double empty lines

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 41]
```diff
@@ -137,4 +183,38 @@ describe("Vip", function()
     assert.stub(vip.getNextRoom).was.called(3)
 
   end)
+
+
+  it("Calculate simple VIP rating", function()
+
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:189]: no empty line between code and a header

File: CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua [hunk 42]
```diff
@@ -137,4 +183,38 @@ describe("Vip", function()
...
+    -- Calculate VIP rating
+    vip:setVIPRating()
+
+    -- Check result
+    assert.are.equal(12, vip.vip_rating)
+    assert.are.equal(0,  vip.cash_reward)
+    assert.are.equal(-10, vip.rep_reward)
+    assert.are.equal(12, vip.vip_message)
+    assert.are.equal(base_vips + 1, vip.hospital.num_vips_ty)
+
```
Comment (Alberth289346) [inline CorsixTH/Luatest/spec/entities/humanoids/vip_spec.lua:218]: no empty line at the end
