### PR TITLE
[RDY] Adds tostring on humanoid

### LINKED ISSUE #1353: Error message added in #1336 crashes error handler
#### Describe the issue
In #1336 a nice error message was added to humanoid that should dump the humanoid table if there is no action. However unlike the error handler in Luacheck the error trap in CorsixTH cannot handle table error messages.

#### Steps to Reproduce
1. Change the condition that generates the error to `if true`
2. Open any new or save game

#### Expected Behavior
Should generate the nice error message described in the PR, along with a stack trace, and insert these errors into the game log; with the usual error handler dialog on screen.

#### System Information
**CorsixTH Version:** 408623ef546c42

**Operating System:** ArchLinuxARM aarch64

**Theme Hospital Version:** GOG.com

### Additional Info
```
An error has occurred in CorsixTH:
/home/stephen/github/CorsixTH/CorsixTH/Lua/world.lua:2297: attempt to concatenate a table value (local 'str')
stack traceback:
        /home/stephen/github/CorsixTH/CorsixTH/Lua/world.lua:2297: in method 'dumpGameLog'
        /home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:959: in function </home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:902>
        (...tail calls...)
        [C]: in ?
```

### PR DESCRIPTION
**Pull request by pschoffer**
Fixes #1353

### CODE REVIEW

File: CorsixTH/Lua/entities/humanoid.lua [hunk 1]
```diff
@@ -912,8 +865,69 @@ end
...
-    error({message = "Action queue was empty. This should never happen.", humanoid = self})
+    error("Action queue was empty. This should never happen. " .. tostring(self))
   end
 
   return self.action_queue[1]
 end
+
+-- METAMETHODS
+
+local Humanoid_mt = Humanoid._metatable
```
Comment (pschoffer) [inline CorsixTH/Lua/entities/humanoid.lua]: Figure out how to make metatables inherit form super metattable

File: CorsixTH/Luatest/class_test_base.lua [hunk 2]
```diff
@@ -22,6 +22,13 @@ SOFTWARE. --]]
 -- classes.
 
 require("busted")
+-- local say = require("say")
```
Comment (pschoffer) [inline CorsixTH/Luatest/class_test_base.lua]: Remove this I guess

File: CorsixTH/Luatest/spec/entities/humanoid_spec.lua [hunk 3]
```diff
@@ -23,10 +23,24 @@ require("class_test_base")
 require("entity")
 require("entities.humanoid")
 
+
+-- TODO figure out how to move out of this test
```
Comment (pschoffer) [inline CorsixTH/Luatest/spec/entities/humanoid_spec.lua]: TODO

File: CorsixTH/Luatest/spec/entities/humanoid_spec.lua [hunk 4]
```diff
@@ -23,10 +23,16 @@ require("class_test_base")
 require("entity")
 require("entities.humanoid")
 
+assert:register("assertion", "matches", assertion_matches, "assertion.matches")
```
Comment (pschoffer) [inline CorsixTH/Luatest/spec/entities/humanoid_spec.lua]: This I am still not happy about, but I am not sure how to solve it. It would be best to register the assertion inside the class_test_base, but the assert table isn't defined there (I don't know why:() Any Ideas?

Comment (pschoffer) [reply CorsixTH/Luatest/spec/entities/humanoid_spec.lua]: Awesome it worked! Thanks man. How come i don't need to require luassert inside the test classes? Is it some internal magic?

**Comment by TheCycoONE** [comment]
Mostly good, this is how the resulting error looks to me:
```
Error in timer handler: 
...ephen/github/CorsixTH/CorsixTH/Lua/entities/humanoid.lua:870: Action queue was empty. This should never happen. <LocalisedString> Current value:WHITHAM - class: Doctor
Warmth: 0.212   Happiness: 0.999   Fatigue: 0.000  Thirst: 0.000  Toilet_Need: 0.000   Health: 0.930
Actions: [walk - going to 65:59   must_happen, meander]
Skills: (0.519)  Surgeon (0.000)  Psych (0.000)  Researcher (0.000)
stack traceback:
        [C]: in function 'error'
        ...ephen/github/CorsixTH/CorsixTH/Lua/entities/humanoid.lua:870: in method 'getCurrentAction'
        .../stephen/github/CorsixTH/CorsixTH/Lua/entities/staff.lua:265: in method 'isTiring'
        .../stephen/github/CorsixTH/CorsixTH/Lua/entities/staff.lua:161: in method 'tick'
        /home/stephen/github/CorsixTH/CorsixTH/Lua/world.lua:1036: in method 'onTick'
        /home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:1014: in function </home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:1011>
        (...tail calls...)
        /home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:915: in function </home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:910>
```

I think a newline and a label is warranted in the error, maybe something like:
```
Error in timer handler: 
...ephen/github/CorsixTH/CorsixTH/Lua/entities/humanoid.lua:870: Action queue was empty. This should never happen.
Humanoid:
<LocalisedString> Current value:WHITHAM - class: Doctor
Warmth: 0.212   Happiness: 0.999   Fatigue: 0.000  Thirst: 0.000  Toilet_Need: 0.000   Health: 0.930
Actions: [walk - going to 65:59   must_happen, meander]
Skills: (0.519)  Surgeon (0.000)  Psych (0.000)  Researcher (0.000)
stack traceback:
        [C]: in function 'error'
        ...ephen/github/CorsixTH/CorsixTH/Lua/entities/humanoid.lua:870: in method 'getCurrentAction'
        .../stephen/github/CorsixTH/CorsixTH/Lua/entities/staff.lua:265: in method 'isTiring'
        .../stephen/github/CorsixTH/CorsixTH/Lua/entities/staff.lua:161: in method 'tick'
        /home/stephen/github/CorsixTH/CorsixTH/Lua/world.lua:1036: in method 'onTick'
        /home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:1014: in function </home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:1011>
        (...tail calls...)
        /home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:915: in function </home/stephen/github/CorsixTH/CorsixTH/Lua/app.lua:910>
```
let me know what you think.

**Comment by pschoffer** [comment]
Good point. I added a new line and some more logic to the name of the humanoid. This is the current state. What do you think?
```
A stack trace is included below, and the handler has been disconnected.
./CorsixTH/Lua/entities/humanoid.lua:868: Action queue was empty. This should never happen.
<LocalisedString> Current value:humanoid (MANMOOR) - class: Nurse
Warmth: 0.290   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.000  Toilet_Need: 0.000   Health: 0.970
Actions: [meander]
stack traceback:
	[C]: in function 'error'
	./CorsixTH/Lua/entities/humanoid.lua:868: in function 'getCurrentAction'
	./CorsixTH/Lua/entities/staff.lua:265: in function 'isTiring'
	./CorsixTH/Lua/entities/staff.lua:161: in function 'tick'
	./CorsixTH/Lua/world.lua:1036: in function 'onTick'
	./CorsixTH/Lua/app.lua:1014: in function <./CorsixTH/Lua/app.lua:1011>
	(...tail calls...)
	./CorsixTH/Lua/app.lua:915: in function <./CorsixTH/Lua/app.lua:910>
```

**Comment by TheCycoONE** [comment]
I don't like that `<LocalisedString> Current value:` noise, but I don't know where that is coming from.

**Comment by TheCycoONE** [comment]
Actually it comes from https://github.com/CorsixTH/CorsixTH/blob/6af2a5c575f22ac8921eb08bd1030a44ae180011/CorsixTH/Src/th_lua_strings.cpp#L380 - but why?

**Comment by Alberth289346** [comment]
Perhaps to distinguish from a literal English sentence and an English translation of a sentence.

**Comment by pschoffer** [comment]
With @TheCycoONE we figured out that it comes from the `profile.name` when the code does `"humanoid" .. " (" .. self.profile.name`.. ")"` Where the name is localized string so colling implicit metatable tostring on it generates that extra `<LocalisedString> Current value:`. I still don't fully understand why is it at the beginning of the whole line and if there is a way to suppress that
