### PR TITLE
Sound: add isPlaying, handles, and loops

### LINKED ISSUE #2113: [Bug] Sounds missing from Research Window
#### Describe the issue
In Theme Hospital, the game would play the noise of the rat going round in its wheel. In CorsixTH this is missing.

#### Steps to Reproduce
1. Load a game with a research dept

2. Open research window.

#### Expected Behavior
The sounds should be playing

#### System Information
**CorsixTH Version:** 0.65.1

**Operating System:** Windows 10
**Theme Hospital Version:** GOG

#### Gamelog.txt

```
Paste gamelog.txt output here
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

I did some tinkering first to try getting this working, but it isn't elegant enough because the sound will play its full duration even if the window is closed (e.g. the loop just starts again, you close the window, the sound now has to finish even though the window is gone)
*In `UIResearch:UIResearch(ui)`*
```lua
self.ui = ui
self.playing = false -- for background sound
```
*New function*
```lua
function UIResearch:playBgSound()
  self.ui:playSound("Research.wav", function() self.playing = false end)
  self.playing = true
end
```
*Added to `UIResearch:onTick()`*
```lua
if not self.playing then self:playBgSound() end
```

Potentially, to make this work better, we're missing the ability to stop sounds on the fly (like we can with music).

### PR DESCRIPTION
**Pull request by TheCycoONE**
Rather than directly using channels to reference sound effects use handles. This way sounds are less likely to coincidentally have the same ID which was not suitable for an isPlaying method.

Taking advantage of the new handles, add an isPlaying method.

Convert the research dialog to use this method for checking isPlaying.

In the process I discovered a race condition with the reserved channels which this PR also addresses.

Also adds a loop parameter that can be used for repeated or continuous sounds.

Fixes #2113

### CODE REVIEW

**Comment by lewri** [comment]
Is this enough to close the issue or would we need more? If it's the former, it may want to live in Window instead. I have not yet reviewed though.

**Comment by TheCycoONE** [comment]
I don't understand the question?

**Review by Alberth289346 — APPROVED** [review]

**Comment by lewri** [comment]
> I don't understand the question?

The question was if this closes #2113 or not is all. Or if you'd still like a better permanent solution in the future.

File: CorsixTH/Src/th_sound.cpp [hunk 1]
```diff
@@ -323,25 +331,37 @@ void sound_player::set_sound_effects_enabled(bool bOn) {
...
-  for (; (available_channels_bitmap & (1 << iChannel)) == 0; ++iChannel) {
+  std::unique_lock lock(channel_mutex);
+  for (size_t i = 0; i < channels.size(); ++i) {
+    if (channels[i] == null_handle) {
+      // Don't assign a null handle to a playing track
+      if (next_playing_track_handle == null_handle) {
+        next_playing_track_handle++;
+      }
+      channels[i] = next_playing_track_handle++;
+      return i;
```
Comment (lewri) [inline CorsixTH/Src/th_sound.cpp]: This will permanently warn on every future pr for reference. Can you suppress it?

Comment (TheCycoONE) [reply CorsixTH/Src/th_sound.cpp]: I'll add a cast before merging yes

**Comment by TheCycoONE** [comment]
Yes this can close that I think. I had the idea after that an even better solution is to add a loop option so we don't need to do anything on tick in lua. But there is always room to refactor.

File: CorsixTH/Lua/dialogs/fullscreen/research_policy.lua [hunk 2]
```diff
@@ -51,7 +51,6 @@ function UIResearch:UIResearch(ui)
   -- lewri: This is a stopgap solution to work around sound states not being
   -- implemented. It should be replaced as soon as it is possible to do so.
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/fullscreen/research_policy.lua]: These could now be removed

File: CorsixTH/Lua/dialogs/fullscreen/research_policy.lua [hunk 3]
```diff
@@ -167,17 +166,12 @@ end
 --! Construct and play this window's background sound.
 function UIResearch:_playBgSound()
   -- Note: See UIResearch:UIResearch function for improving this.
-  self.bg_sound = self.ui:playSound("Research.wav",
-    --[[persistable:research_policy_window_reset_bg_sound]] function()
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/fullscreen/research_policy.lua:171]: Risking a failed persistable I think? Though arguably the gap between my pr and your pr is so short it should be acceptable.

File: CorsixTH/Lua/audio.lua [hunk 4]
```diff
@@ -374,11 +374,25 @@ function Audio:stopSound(sound)
...
-  if sound.channel and sound.channel >= 0 then
-    sound_fx:stop(sound.channel, sound.played_callback_id)
+  if sound and sound.handle then
+    sound_fx:stop(sound.handle, sound.played_callback_id)
   end
 end
 
+--! Determine if a given sound is still playing
+--!param sound (table) The `sound` table returned by `Audio:playSound`.
+function Audio:isPlaying(sound)
```
Comment (lewri) [inline CorsixTH/Lua/audio.lua:385]: Could this also have a pass through function in UI like the others?

File: CorsixTH/Lua/dialogs/fullscreen/research_policy.lua [hunk 5]
```diff
@@ -167,17 +166,12 @@ end
 --! Construct and play this window's background sound.
 function UIResearch:_playBgSound()
   -- Note: See UIResearch:UIResearch function for improving this.
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/fullscreen/research_policy.lua]: Also not needed anymore

File: CorsixTH/Lua/dialogs/fullscreen/research_policy.lua [hunk 6]
```diff
@@ -167,17 +166,12 @@ end
 --! Construct and play this window's background sound.
 function UIResearch:_playBgSound()
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/fullscreen/research_policy.lua:168]: From the previous discussed PR; a more robust solution might be better these functions living in the Window class instead. But I'd understand if that would be too consuming to move now.

**Review by lewri — COMMENTED** [review]
This review submitted under the guise that this will close the issue 2113. If it won't, I can make a different review.

Works fine for me too.

**Comment by TheCycoONE** [comment]
Thanks Lewri, I plan to fix everything except moving to window. It doesn't make sense to me if this is the only window that does it. If there are other windows I'd reconsider.

A little surprised how coherent it turned out given it was one rather late evening of coding.

File: CorsixTH/Lua/dialogs/fullscreen/research_policy.lua (hunk 6 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/dialogs/fullscreen/research_policy.lua:168]: I don't want to move this unless there are more use cases for it. Otherwise it's bloating window just for research room.

File: CorsixTH/Lua/audio.lua (hunk 4 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/audio.lua:385]: No longer used, so not for now.

File: CorsixTH/Lua/dialogs/fullscreen/research_policy.lua (hunk 3 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/dialogs/fullscreen/research_policy.lua:171]: Fixed.

File: CorsixTH/Lua/dialogs/fullscreen/research_policy.lua (hunk 2 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/dialogs/fullscreen/research_policy.lua]: Removed.

**Comment by TheCycoONE** [comment]
Uploaded a new version that I'm happy with. It uses loops in SDL_Mixer instead of doing anything with callbacks or playback checks on tick which is cleaner and more efficient.

I expect the two commits to be merged after review.

File: CorsixTH/Lua/audio.lua [hunk 7]
```diff
@@ -314,10 +314,11 @@ local wilcard_cache = permanent "audio_wildcard_cache" {}
 --  finished playing. Can be nil.
 --!param played_callback_delay (integer) An optional delay in milliseconds
 --  before the played_callback is called.
+--!param loops (integer) number of times to play the audio
```
Comment (lewri) [inline CorsixTH/Lua/audio.lua]: Suggest: -1 is continuous/infinite (or some comment thereabouts)
