### PR TITLE
Fix knockdoor action in flight.

### LINKED ISSUE #2142: [Bug] Persisted Knock Door Action breaks on resumption from 0.64 > master
#### Describe the issue
If a patient had a knock action queued when the game was saved in 0.64; and reloaded their save in master; the action crashes on that patient.

Any new knock door actions are not affected.

#### Steps to Reproduce
1. *Load save game attached to this ticket*

2. Wait -- a patient is about to knock on the GP office door.

3.

#### Save Game

[064singlerun.zip](https://github.com/CorsixTH/CorsixTH/files/8556858/064singlerun.zip)

#### Expected Behavior
No crash on resuming a door knock action.

#### System Information
**CorsixTH Version:** Appveyor master build 671

**Operating System:** *Windows 10*

**Theme Hospital Version:** GOG

#### Gamelog.txt

```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\humanoid_actions\knock_door.lua:92: Illegal state nil in KnockDoorAction:update
stack traceback:
        [C]: in function 'error'
        Lua\humanoid_actions\knock_door.lua:92: in method 'update'
        Lua\humanoid_actions\knock_door.lua:56: in local 'timer_function'
        Lua\entity.lua:216: in method 'tick'
        Lua\world.lua:1093: in method 'onTick'
        Lua\app.lua:1125: in function <Lua\app.lua:1122>
        (...tail calls...)
        Lua\app.lua:1025: in function <Lua\app.lua:1020>
```

### Additional Info
*Paste any screen shots or other additional information that might help
illustrate the problem.*

### PR DESCRIPTION
**Pull request by Alberth289346**
*Fixes #2142 

**Describe what the proposed change does**
- When the Knockdoor Action is being animated at the time of save, the state variable is never created and the callback at the end of the animation cannot find the next step to perform.
- Fixed by initializing the state to point to that next step. If the action was not running, the `start` calll will initialize state variable, overwriting the fix value.

### CODE REVIEW

File: CorsixTH/Lua/humanoid_action.lua [hunk 1]
```diff
@@ -110,4 +110,11 @@ function HumanoidAction:afterLoad(old, new)
       self.is_entering = not not self.is_entering
     end
   end
+
+  if old < 167 and new >= 167 and class.type(self) == "KnockDoorAction" then
```
Comment (lewri) [inline CorsixTH/Lua/humanoid_action.lua:114]: Maybe just check old for this one to be on the safer side?

**Review by lewri — COMMENTED** [review]
Will boot up the Appveyor build later today to verify

**Review by lewri — APPROVED** [review]
Yes, works.
Will leave to you to decide about the other comment.

**Comment by TheCycoONE** [comment]
Need to bump the save version and I agree with lewri to just make it old < *version*.
LGTM

**Comment by Alberth289346** [comment]
Rebased and performed the requested changes.
