### PR TITLE
[RDY]Fix regression in #2086

### LINKED ISSUE #2278: [Bug] Demo Level freeze (dead patient enters for treatment)
### Describe the issue

I played with the demo and the demo-level froze at some point, when I had almost 1000 patients cured (I don't remember exactly how many) and a very crowded hospital (see screenshot below)..

Interestingly, the game could still be saved. If you load the sav, you will see my hospital (very crowded) and you can still move the view and click on people to get the info popup for them, but nothing more.

It should be noted, that the game did not go "game over" as I'm still fairly within the green spectrum of reputation.

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. ???

3. Profit

### Expected Behaviour

Don't freeze.

### Save Game

Save game attached to report: Yes
[Autosave8.zip](https://github.com/CorsixTH/CorsixTH/files/9873731/Autosave8.zip)

Wait ~1 min and the game will freeze.

### CorsixTH Version

0.66

### Operating System

Windows 10

### Theme Hospital Version

Demo

### Gamelog.txt

```bash
Compiled with api_version: 2682, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2682, game version: v0.66, savegame version: 170
Created game with savegame version 170.
Audio:playSound - Warning: File not found in sound archive: reqd021.wav
Warning: Trying to remove nonexistent room build callback (function: 0000019A4A866D20) from humanoid (table: 0000019A4F4BF770).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A59164180) from humanoid (table: 0000019A4F4BF770).
Warning: Trying to remove nonexistent staff callback (function: 0000019A4A867F20) from humanoid (table: 0000019A4F4BF770).
Warning: Trying to remove nonexistent room build callback (function: 0000019A520A2A50) from humanoid (table: 0000019A59656550).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A5852A8D0) from humanoid (table: 0000019A59656550).
Warning: Trying to remove nonexistent staff callback (function: 0000019A520A17F0) from humanoid (table: 0000019A59656550).
Warning: Trying to remove nonexistent room build callback (function: 0000019A53124C70) from humanoid (table: 0000019A58CAFDF0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A577C8990) from humanoid (table: 0000019A58CAFDF0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A53124970) from humanoid (table: 0000019A58CAFDF0).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5311C030) from humanoid (table: 0000019A59490720).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A577CE330) from humanoid (table: 0000019A59490720).
Warning: Trying to remove nonexistent staff callback (function: 0000019A53118850) from humanoid (table: 0000019A59490720).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BEB220) from humanoid (table: 0000019A5957F430).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A4E047E30) from humanoid (table: 0000019A5957F430).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BE6A80) from humanoid (table: 0000019A5957F430).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BF6560) from humanoid (table: 0000019A58CAE1B0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53CA4B50) from humanoid (table: 0000019A58CAE1B0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BF4280) from humanoid (table: 0000019A58CAE1B0).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BECCC0) from humanoid (table: 0000019A4F7D0C30).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53DF3340) from humanoid (table: 0000019A4F7D0C30).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BEAD40) from humanoid (table: 0000019A4F7D0C30).
Warning: Trying to remove nonexistent room build callback (function: 0000019A59C06EE0) from humanoid (table: 0000019A59E3CB70).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53DD4B50) from humanoid (table: 0000019A59E3CB70).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59C06E80) from humanoid (table: 0000019A59E3CB70).
Warning: Trying to resolve door deadlock at (50, 72)
Warning: Trying to resolve door deadlock at (58, 74)
Warning: Trying to resolve door deadlock at (58, 74)
Warning: Trying to remove nonexistent room build callback (function: 0000019A59BE8F40) from humanoid (table: 0000019A539C74F0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A5A4A31F0) from humanoid (table: 0000019A539C74F0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A59BE7E00) from humanoid (table: 0000019A539C74F0).
Warning: Trying to resolve door deadlock at (54, 74)
Warning: Trying to resolve door deadlock at (73, 68)
Warning: Trying to resolve door deadlock at (51, 74)
Warning: Trying to resolve door deadlock at (61, 72)
Warning: Trying to resolve door deadlock at (55, 65)
Warning: Trying to resolve door deadlock at (58, 74)
Warning: Trying to resolve door deadlock at (51, 65)
Warning: Trying to resolve door deadlock at (81, 76)
Warning: Trying to resolve door deadlock at (81, 76)
Warning: Trying to resolve door deadlock at (80, 72)
Warning: Trying to resolve door deadlock at (80, 72)
Warning: Trying to resolve door deadlock at (78, 75)
Warning: Trying to remove nonexistent room build callback (function: 0000019A5311E4F0) from humanoid (table: 0000019A5D1B0050).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53E0A1E0) from humanoid (table: 0000019A5D1B0050).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5311C330) from humanoid (table: 0000019A5D1B0050).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5CD7A400) from humanoid (table: 0000019A58A8B690).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A596B1E80) from humanoid (table: 0000019A58A8B690).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5CD79320) from humanoid (table: 0000019A58A8B690).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5CD80A00) from humanoid (table: 0000019A4F4CBAB0).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A4E03B8F0) from humanoid (table: 0000019A4F4CBAB0).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5CD80220) from humanoid (table: 0000019A4F4CBAB0).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5CD7A340) from humanoid (table: 0000019A59468330).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A53E15C10) from humanoid (table: 0000019A59468330).
Warning: Trying to remove nonexistent staff callback (function: 0000019A5CD79E00) from humanoid (table: 0000019A59468330).
Warning: Trying to remove nonexistent room build callback (function: 0000019A5311AAD0) from humanoid (table: 0000019A5C74C520).
Warning: Trying to remove nonexistent room remove callback (function: 0000019A591679C0) from humanoid (table: 0000019A5C74C520).
Warning: Trying to remove nonexistent staff callback (function: 0000019A53116090) from humanoid (table: 0000019A5C74C520).
Warning: Trying to resolve door deadlock at (80, 67)
Warning: Trying to resolve door deadlock at (50, 72)
Warning: Trying to resolve door deadlock at (81, 76)
Error in timer handler: 
Lua\entities\humanoid.lua:472: assertion failed!
stack traceback:
	[C]: in function 'assert'
	Lua\entities\humanoid.lua:472: in method 'startAction'
	Lua\entities\humanoid.lua:577: in method 'finishAction'
	Lua\room.lua:162: in method 'dealtWithPatient'
	Lua\rooms\pharmacy.lua:93: in field 'after_use'
	Lua\humanoid_actions\multi_use_object.lua:316: in local 'timer_function'
	Lua\entity.lua:216: in field 'tick'
	Lua\entities\humanoids\staff.lua:126: in method 'tick'
	Lua\world.lua:1085: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
Recovering from error in timer handler...
Error in timer handler: 
Lua\entities\humanoid.lua:908: Action queue was empty. This should never happen.
humanoid - class: Standard Female Patient
Warmth: 0.328   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.475  Toilet_Need: 0.539   Health: 0.000   Service Quality: 0.000
Actions: []
stack traceback:
	[C]: in function 'error'
	Lua\entities\humanoid.lua:908: in method 'getCurrentAction'
	Lua\hospital.lua:717: in method 'countSittingStanding'
	Lua\hospitals\player_hospital.lua:163: in method 'dailyAdviceChecks'
	Lua\hospitals\player_hospital.lua:457: in method 'onEndDay'
	Lua\world.lua:1046: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
Savegame version is 170 (v0.66), originally it was 170 (v0.66).
Audio:playSound - Warning: File not found in sound archive: sack008.wav
Error in timer handler: 
Lua\entities\humanoid.lua:908: Action queue was empty. This should never happen.
humanoid - class: Standard Female Patient
Warmth: 0.328   Happiness: 1.000   Fatigue: 0.000  Thirst: 0.475  Toilet_Need: 0.539   Health: 0.000   Service Quality: 0.000
Actions: []
stack traceback:
	[C]: in function 'error'
	Lua\entities\humanoid.lua:908: in method 'getCurrentAction'
	Lua\hospital.lua:717: in method 'countSittingStanding'
	Lua\hospitals\player_hospital.lua:163: in method 'dailyAdviceChecks'
	Lua\hospitals\player_hospital.lua:457: in method 'onEndDay'
	Lua\world.lua:1046: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
```

### Additional Information

grafik

### PR DESCRIPTION
**Pull request by mugmuggy**
*Fixes #2278, #2305*

**Describe what the proposed change does**
- Restores settings interrupted walk must_happen from saved_must_happen
- Adds afterLoad to fix instances

### CODE REVIEW

File: CorsixTH/Lua/app.lua [hunk 1]
```diff
@@ -29,7 +29,7 @@ local runDebugger = corsixth.require("run_debugger")
 -- and add compatibility code in afterLoad functions
 -- Recommended: Also replace/Update the summary comment
 
-local SAVEGAME_VERSION = 176 -- Palette fix
+local SAVEGAME_VERSION = 177 -- Palette fix
```
Comment (lewri) [inline CorsixTH/Lua/app.lua:32]:
```suggestion
local SAVEGAME_VERSION = 177 -- Fix requeue action regression
```
?

**Review by lewri — COMMENTED** [review]
I would have liked to have seen a handling for this patient from #2278 
image

I'm not sure if there is a reliable method to do so though. It may need its own PR. With #2037 it will at least trigger the empty action queue popup again though.

**Comment by lewri** [comment]
Bye the way, I can confirm it works here

File: CorsixTH/Lua/app.lua (hunk 1 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/app.lua:32]: Yes, string should change, the point of the comment is to detect conflicts.
