### PR TITLE
[RDY] Switching faxes keeps game paused

### LINKED ISSUE #1625: Switching faxes unpauses game
#### Describe the issue
If you have two faxes, and try to switch between them the game will unpause. Even though a fax is open.

#### Steps to Reproduce
1. Get two faxes popup on the bottom of the game

2. Open one, then go to open the other.

#### Expected Behavior
Game should stay paused when viewing faxes 

#### System Information
**CorsixTH Version:** Latest trunk

**Operating System:** W10

**Theme Hospital Version:** GOG

#### Gamelog.txt
None

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #1625*

**Describe what the proposed change does**
- Game will now stay paused when you switch between faxes
- Game also recognises if a staff_rise window is open (and vice versa) and stays paused then too

The function call `` TheApp.world:setSpeed("Pause") `` had to be moved in message.lua to after the new window was made, which was the reason why the game would unpause.

### CODE REVIEW

File: CorsixTH/Lua/dialogs/fullscreen/fax.lua [hunk 1]
```diff
@@ -282,7 +282,7 @@ function UIFax:close()
   self.icon.fax = nil
   self.icon:adjustToggle()
   UIFullscreen.close(self)
-  if world and world:isCurrentSpeed("Pause") then
+  if world and world:isCurrentSpeed("Pause") and #self.ui:getWindows(UIStaffRise) == 0 then
```
Comment (sadger) [inline CorsixTH/Lua/dialogs/fullscreen/fax.lua:285]: I understand the point of this from our discussions in IRC but only from reading the code it's not clear why this is happening. Could we perhaps create a function to count all other pause dialogs that might be open to use in both cases?

**Comment by TheCycoONE** [comment]
I'd much prefer pausing and unpausing for dialogs was in one spot. Dialogs could have a `should_pause` property, and the open dialogs could be iterated to see if we are in / should be in a paused on dialog state.

Willing to accept this patch for now, but if you could make that refactor happen I'd be happier.

**Comment by lewri** [comment]
@TheCycoONE I did try to unify it into one spot but I wasn't successful. But this solution should be ok for now.

I tried to use world:onTick() which does work but every time you change a window, everyone moves 1 tick.

**Comment by lewri** [comment]
Bear with me... I think I have something better
