### PR TITLE
Fix advice call in boiler repair

### LINKED ISSUE #2173: [Bug] Crash: attempt to index a nil value (field 'hospital')
### Describe the issue

After loading a specific save, the game crashes after a few seconds with the following error:

An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The timer handler.
A stack trace is included below, and the handler has been disconnected.
Lua\hospital.lua:867: attempt to index a nil value (field 'hospital')
stack traceback:
        Lua\hospital.lua:867: in method '_fixBoiler'
        Lua\hospital.lua:937: in field 'onEndDay'
        Lua\hospitals\player_hospital.lua:482: in method 'onEndDay'
        Lua\world.lua:1046: in method 'onTick'
        Lua\app.lua:1130: in function <Lua\app.lua:1127>
        (...tail calls...)
        Lua\app.lua:1030: in function <Lua\app.lua:1025>

Warning: No event handler for timer

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. Wait a few seconds

3. Crash shoud happen

### Expected Behaviour

Game should keep running normally

### Save Game

Save game attached to report: Yes/No
[Autosave11.zip](https://github.com/CorsixTH/CorsixTH/files/8753704/Autosave11.zip)

### CorsixTH Version

v0.66-beta1

### Operating System

Windows 10 21H1

### Theme Hospital Version

Origin

### Gamelog.txt

```bash
Compiled with api_version: 2682, arch: x64, audio: true, os: windows
SDL renderer: direct3d
Lua 5.4 run with api version: 2682, game version: v0.66-beta1, savegame version: 170
Created game with savegame version 170.
Warning: Trying to remove nonexistent room build callback (function: 00000261CB58D100) from humanoid (table: 00000261C94C4DA0).
Warning: Trying to remove nonexistent room remove callback (function: 00000261C4733B80) from humanoid (table: 00000261C94C4DA0).
Warning: Trying to remove nonexistent staff callback (function: 00000261CB58D520) from humanoid (table: 00000261C94C4DA0).
Warning: Trying to remove nonexistent room build callback (function: 00000261C4FEA270) from humanoid (table: 00000261D816C070).
Warning: Trying to remove nonexistent room remove callback (function: 00000261C882B790) from humanoid (table: 00000261D816C070).
Warning: Trying to remove nonexistent staff callback (function: 00000261C4FEA2D0) from humanoid (table: 00000261D816C070).
Warning: Trying to remove nonexistent room build callback (function: 00000261CCA35010) from humanoid (table: 00000261C8A164F0).
Warning: Trying to remove nonexistent room remove callback (function: 00000261CD1EF320) from humanoid (table: 00000261C8A164F0).
Warning: Trying to remove nonexistent staff callback (function: 00000261CCA350D0) from humanoid (table: 00000261C8A164F0).
Warning: Trying to remove nonexistent room build callback (function: 00000261CCA34E30) from humanoid (table: 00000261C52A0EF0).
Warning: Trying to remove nonexistent room remove callback (function: 00000261C4C84A70) from humanoid (table: 00000261C52A0EF0).
Warning: Trying to remove nonexistent staff callback (function: 00000261CCA350D0) from humanoid (table: 00000261C52A0EF0).
Warning: Trying to remove nonexistent room build callback (function: 00000261D81B1990) from humanoid (table: 00000261D81A1FE0).
Warning: Trying to remove nonexistent room remove callback (function: 00000261CD32E370) from humanoid (table: 00000261D81A1FE0).
Warning: Trying to remove nonexistent staff callback (function: 00000261D81B1C90) from humanoid (table: 00000261D81A1FE0).
Warning: Trying to remove nonexistent room build callback (function: 00000261CCA35370) from humanoid (table: 00000261D7D66270).
Warning: Trying to remove nonexistent room remove callback (function: 00000261C566C120) from humanoid (table: 00000261D7D66270).
Warning: Trying to remove nonexistent staff callback (function: 00000261CCA354F0) from humanoid (table: 00000261D7D66270).
Warning: Trying to remove nonexistent room build callback (function: 00000261C915D0D0) from humanoid (table: 00000261CD132920).
Warning: Trying to remove nonexistent room remove callback (function: 00000261CCE2ED20) from humanoid (table: 00000261CD132920).
Warning: Trying to remove nonexistent staff callback (function: 00000261C915D550) from humanoid (table: 00000261CD132920).
Warning: Trying to resolve door deadlock at (49, 72)
Warning: Trying to remove nonexistent room build callback (function: 00000261D80924D0) from humanoid (table: 00000261C553CEA0).
Warning: Trying to remove nonexistent room remove callback (function: 00000261CA566DC0) from humanoid (table: 00000261C553CEA0).
Warning: Trying to remove nonexistent staff callback (function: 00000261D8092DD0) from humanoid (table: 00000261C553CEA0).
Error in timer handler: 
Lua\hospital.lua:867: attempt to index a nil value (field 'hospital')
stack traceback:
	Lua\hospital.lua:867: in method '_fixBoiler'
	Lua\hospital.lua:937: in field 'onEndDay'
	Lua\hospitals\player_hospital.lua:482: in method 'onEndDay'
	Lua\world.lua:1046: in method 'onTick'
	Lua\app.lua:1130: in function <Lua\app.lua:1127>
	(...tail calls...)
	Lua\app.lua:1030: in function <Lua\app.lua:1025>
```

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #2173*

**Describe what the proposed change does**
- Remove the extra ".hospital" from my recent change.

### CODE REVIEW

**Review by lewri — APPROVED** [review]

**Review by lewri — APPROVED** [review]
Still fine with me

**Comment by tobylane** [comment]
I've checked all my advice commits since 0.65 and this should be all of it.

File: CorsixTH/Lua/hospital.lua [hunk 1]
```diff
@@ -864,7 +864,7 @@ function Hospital:_fixBoiler()
     heat_vars.heating_broke = false
     if num_radiators > 0 then
       -- Only tell the player about fix if there is at least one radiator.
-      self.hospital:giveAdvice({ _A.boiler_issue.resolved })
+      self:giveAdvice({ _A.boiler_issue.resolved })
```
Comment (lewri) [inline CorsixTH/Lua/hospital.lua:867]: Niggle, but this one now sits with spaces and others don't.
