### PR TITLE
#2738 stop epidemic timer on epidemic successfully eradicated

### LINKED ISSUE #2738: [Bug] Epidemic. Timer doesn't stop when an epidemic is successfully eradicated
### Describe the issue

In CTH Epidemic clock does not instantly end when an epidemic is successfully eradicated.
In vanilla TH it does.

epidemic

vanilla Theme Hospital footage which demonstrates this behaviour: 
https://youtu.be/_PeCGwKKoZs?t=471

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. Observe how last epidemic patient will be cured in surgery.
3. Observe that epidemic clock doesn't stop.

### Expected Behaviour

Epidemic clock should instantly end when an epidemic is successfully eradicated.

### Save Game

[epidemic_succesfully_eridicated_surgery.sav.zip](https://github.com/user-attachments/files/18102175/epidemic_succesfully_eridicated_surgery.sav.zip)

### CorsixTH Version

0.65.0 (still relevant for 0.68.0)

### Operating System

MacOS Sonoma 14.5

### PR DESCRIPTION
**Pull request by ARGAMX**
*Fixes #2738, #1454*

**Describe what the proposed change does**
- Fixes bug when epidemic Timer doesn't stop when an epidemic is successfully eradicated.
-

### CODE REVIEW

File: CorsixTH/Lua/epidemic.lua [hunk 1]
```diff
@@ -262,13 +262,16 @@ function Epidemic:checkNoInfectedPlayerHasLeft()
...
       self:finishCoverUp()
       return
     end
   end
+
+  local all_infected_cured = self:countInfectedPatients() == 0
+  if all_infected_cured then
+    self:finishCoverUp()
+    return
+  end
```
Comment (lewri) [inline CorsixTH/Lua/epidemic.lua:274]: Function this is inserted in does not fit its current purpose.

The function name either needs updating; or this check could go elsewhere. Judging how the the tick function is set up, you'd make it a function in itself. First option better this time round though.

The name `all_infected_cured` is also potentially not a true reflection of the check you're running. We don't know that every patient got cured, one might have died instead.

Comment (ARGAMX) [reply CorsixTH/Lua/epidemic.lua]: > Function this is inserted in does not fit its current purpose.
> 
> The function name either needs updating; or this check could go elsewhere. Judging how the the tick function is set up, you'd make it a function in itself. First option better this time round though.
> 
> The name `all_infected_cured` is also potentially not a true reflection of the check you're running. We don't know that every patient got cured, one might have died instead.

Yeap, agree.
I have moved new check to separated function.

Also I agree that `all_infected_cured` not reflecting the thing it contains. I have renamed it to `no_any_infected_patients_left`.

Also from my point of view we should rename function `checkNoInfectedPlayerHasLeft` to something more understandable. For example `checkIsAnyInfectedPatientLeftTheHospitalAndRevealedEpidemic`.

What do you think about this?

Comment (Alberth289346) [reply CorsixTH/Lua/epidemic.lua]: > `checkNoInfectedPlayerHasLeft`

Players also get infected?  :O

In general, the name of the function indicates what you can expect to find inside.

The function name here is quite specific. For a larger function this is fine, as you mostly need all space for implementing the functionality. (Eg if you need 300 lines of code for that check, it's unlikely to be a good spot for doing something else as well.)

For a short function (which seems to be the case here), it is often more useful to give a slightly more general name. In that way, you sort-of pave the path for adding more checks or doing more work in that function in the future.
For example, if you use "isEpidemicContained" or "isEpidemicUnderControl" for example, then basically the function name suggests it covers any action that must be done when the epidemic "has finished". It could for example call off all nurses that are doing vaccination patrol in the corridor, etc.

The suggested function name is too narrow in scope for the latter action ("hasAnyPatientLeft" does not intuitively suggest actions wrt nurses), so if nurses need to be called off somewhen in the future development, it must be done elsewhere or the name of the function must be adapted.

File: CorsixTH/Lua/epidemic.lua [hunk 2]
```diff
@@ -261,16 +262,22 @@ function Epidemic:checkNoInfectedPlayerHasLeft()
...
-      if not self.inspector then
-        self:spawnInspector()
-      end
       self:finishCoverUp()
       return
     end
   end
 end
 
+function Epidemic:checkThereAreNoAnyInfectedPatientsLeft()
```
Comment (Alberth289346) [inline CorsixTH/Lua/epidemic.lua:274]:
```suggestion
function Epidemic:checkNoInfectedPatients()
```

Function needs some Lua documentation.

File: CorsixTH/Lua/epidemic.lua [hunk 3]
```diff
@@ -261,16 +262,22 @@ function Epidemic:checkNoInfectedPlayerHasLeft()
...
+  if self.result_determined then return end
+
+  local no_any_infected_patients_left = self:countInfectedPatients() == 0
+  if no_any_infected_patients_left then
```
Comment (Alberth289346) [inline CorsixTH/Lua/epidemic.lua:278]: You could move the `self:countInfectedPatients() == 0` check inside the `if`

Having zero infected patient implies already they don't exist (which is what I read in the variable name).

File: CorsixTH/Lua/epidemic.lua [hunk 4]
```diff
@@ -411,6 +418,10 @@ later (@see applyOutcome) ]]
 function Epidemic:finishCoverUp()
   self.result_determined = true
 
+  if not self.inspector then
+    self:spawnInspector()
+  end
```
Comment (Alberth289346) [inline CorsixTH/Lua/epidemic.lua:425]: I never played an epidemic, but an inspector always arrives, even if no infected uncured patients left the hospital?

If not, this looks like changed behavior

Comment (ARGAMX) [reply CorsixTH/Lua/epidemic.lua:425]: > I never played an epidemic, but an inspector always arrives, even if no infected uncured patients left the hospital?
> 
> If not, this looks like changed behavior

Yeap, he should always arrive after CoverUp happened.
The only scenario when he won’t come is if you confess the epidemic and pay the fine straightaway, instead of doing CoverUp.
Currently, for some reason, the code was written so strangely, as if he could not always arrive after CoverUp.

File: CorsixTH/Lua/epidemic.lua (hunk 2 above)
Comment (ARGAMX) [reply CorsixTH/Lua/epidemic.lua:274]: > Function needs some Lua documentation.

Added as for other functions in this file

File: CorsixTH/Lua/epidemic.lua (hunk 3 above)
Comment (ARGAMX) [reply CorsixTH/Lua/epidemic.lua]: change to `if (self:countInfectedPatients() == 0) then`

File: CorsixTH/Lua/epidemic.lua [hunk 5]
```diff
@@ -261,16 +262,23 @@ function Epidemic:checkNoInfectedPlayerHasLeft()
...
   end
 end
 
+--[[ Check for conditions that no any uncured infected patients
+left in hospital. If so then epidemic must end earlier than the
+length of the timer.]]
+function Epidemic:checkNoInfectedPatients()
+  if self.result_determined then return end
+
+  if (self:countInfectedPatients() == 0) then
```
Comment (lewri) [inline CorsixTH/Lua/epidemic.lua:277]: We can drop the brackets too :)

File: CorsixTH/Lua/epidemic.lua [hunk 6]
```diff
@@ -112,6 +112,7 @@ function Epidemic:tick()
       self:checkNoInfectedPlayerHasLeft()
       self:markedPatientsCallForVaccination()
       self:showAppropriateAdviceMessages()
+      self:checkThereAreNoAnyInfectedPatientsLeft()
```
Comment (lewri) [inline CorsixTH/Lua/epidemic.lua:115]: Function name got a little garbed here, where's it referencing?

File: CorsixTH/Lua/epidemic.lua [hunk 7]
```diff
@@ -261,16 +262,23 @@ function Epidemic:checkNoInfectedPlayerHasLeft()
...
       self:finishCoverUp()
       return
     end
   end
 end
 
+--[[ Check for conditions that no any uncured infected patients
+left in hospital. If so then epidemic must end earlier than the
+length of the timer.]]
+function Epidemic:checkNoInfectedPatients()
```
Comment (lewri) [inline CorsixTH/Lua/epidemic.lua:274]: I'm fine with this, trying to add clarity to this function name any more likely will just make things worse.

File: CorsixTH/Lua/epidemic.lua (hunk 6 above)
Comment (lewri) [inline CorsixTH/Lua/epidemic.lua:115]: Potentially sanity check the order of these, I'm sure it's still fine.

**Review by lewri — COMMENTED** [review]
Good refactor ontop of the fix 👍

File: CorsixTH/Lua/epidemic.lua (hunk 6 above)
Comment (ARGAMX) [reply CorsixTH/Lua/epidemic.lua]: > Potentially sanity check the order of these, I'm sure it's still fine.

I changed the order, but honestly I don't think it matters here. but thanks for the tip.

Comment (ARGAMX) [reply CorsixTH/Lua/epidemic.lua]: > Function name got a little garbed here, where's it referencing?

Oh, true. thanks.

File: CorsixTH/Lua/epidemic.lua (hunk 5 above)
Comment (ARGAMX) [reply CorsixTH/Lua/epidemic.lua]: Dropped 👌

**Review by lewri — COMMENTED** [review]
LGTM
