### PR TITLE
Let staff return to training/research

### LINKED ISSUE #2964: [Bug] Student drops out study and responds to room call
### Describe the issue

When a student goes back to the Training Room from the Staff Room he can answer room calls.
I am unable to check if that 0.69.0 regression or not.

----

https://github.com/user-attachments/assets/a1ae1989-8523-4fa8-8a64-f6aa07d91500

----

### Steps to Reproduce

1. Load attached save game '2964_Student_27_FENBERRY_abandon_study_and_answer_call.sav'.
2. You will see `27 FENBERRY`. He is studying in the Training Room. But currently returning from the Staff Room to the Training Room.
3. Press 3 and soon you will hear the room call to the Scanner.
4. Observe how `27 FENBERRY` abandons his study and heads to the Scanner room.

----

### Expected Behaviour

Students should not pick up room calls while studying, even on returning to the Training Room.

----

### Save Game

[2964_Student_27_FENBERRY_abandon_study_and_answer_call.sav.zip](https://github.com/user-attachments/files/21689363/2964_Student_27_FENBERRY_abandon_study_and_answer_call.sav.zip)

----

### CorsixTH Version

0.69.0

----

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2964*

**Describe what the proposed change does**
- Reworked staff idle check to properly handle returning doctors to research/training.

@ARGAMX please extensively test I've not broken other call states e.g. dropping answers to rooms.

### CODE REVIEW

**Comment by Alberth289346** [comment]
Hmm, `last_room` to send them back eh?

So what happens if the doctor graduates (ie finishes their studies), and is waiting for the next job at hand?

**Comment by lewri** [comment]
> Hmm, `last_room` to send them back eh?
> 
> So what happens if the doctor graduates (ie finishes their studies), and is waiting for the next job at hand?

https://github.com/CorsixTH/CorsixTH/blob/3d2b3b199658155d44355c10cee67d7e85e85672/CorsixTH/Lua/rooms/training.lua#L208-L213
and
https://github.com/CorsixTH/CorsixTH/blob/3d2b3b199658155d44355c10cee67d7e85e85672/CorsixTH/Lua/entities/humanoids/staff/doctor.lua#L171-L177
Will fix those (arguably the first is not related to the q but relates to training)

File: CorsixTH/Lua/entities/humanoids/staff.lua [hunk 1]
```diff
@@ -562,15 +562,13 @@ function Staff:isIdle()
...
-    if x then
-      room = self.world:getRoom(x, y)
-      if room and (room.room_info.id == "training" or room.room_info.id == "research") then
-        return false
-      end
+    -- In the corridor and not on_call (e.g. watering or going to room).
+    -- The staff is free, unless going back to the training/research.
+    room = self.last_room
+    if room then
+      return room.room_info.id ~= "training" and room.room_info.id ~= "research"
```
Comment (ARGAMX) [inline CorsixTH/Lua/entities/humanoids/staff.lua]: Maybe we should leave it as it was?
I didn't understand why this particular check was changed.
It was correct in itself...

If we look at the whole function, its philosophy is to `return true` at the end, but
on the way to this `return true` there are many barriers with `return false`.

This pattern is easy to read and the function's operation becomes more obvious.

And here we 'remove' one of these `return false` barriers.
And now the function as a whole is no longer reads so fluently.

I would leave it as is.
Moreover, it does not fix anything as I understand. Correct?
I changed it back and the fix still works.

```suggestion
    if room and (room.room_info.id == "training" or room.room_info.id == "research") then
      return false
```

But In general, fix works good to me, I tested it. Good job. 👍
I like the rest. 👌

**Comment by ARGAMX** [comment]
> Hmm, `last_room` to send them back eh?
> 
> So what happens if the doctor graduates (ie finishes their studies), and is waiting for the next job at hand?

Very good question.
I thought about it too.
But when I tested it, this freshly graduated student still responded to the call.
So this case works fine.

**Comment by Alberth289346** [comment]
@lewri : Perhaps add a comment to the `nil` assignments why they're there?

**Comment by lewri** [comment]
> @lewri : Perhaps add a comment to the `nil` assignments why they're there?

Sorry, where in the code?

File: CorsixTH/Lua/entities/humanoids/staff.lua (hunk 1 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/staff.lua]: Would it make it worse if I said I actually wanted to do an actual one line statement 🤣 -- this was actually meant to be my compromise.
I can extend it back out if absolutely necessary, though from a coder's perspective I don't think the `false` added anything we couldn't ascertain already.

**Comment by Alberth289346** [comment]
> Sorry, where in the code?

Sorry for not being clear, I should have referred more precisely.

I meant at https://github.com/CorsixTH/CorsixTH/pull/2968#issuecomment-3172853623 , lines 212 respectively 176

File: CorsixTH/Lua/entities/humanoids/staff.lua (hunk 1 above)
Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoids/staff.lua]: > Would it make it worse if I said I actually wanted to do an actual one line statement 🤣 -- this was actually meant to be my compromise. I can extend it back out if absolutely necessary, though from a coder's perspective I don't think the `false` added anything we couldn't ascertain already.

Yes, seems it would be better to return it back to how it was.

Yes, functionally nothing will change. but in previous form it was easier to read.
And in previous form it also was possible to add more conditions after this one.
Because in this new variant it turns out that now it can be only the last one.
Because now it always makes an `return`.
And if we want to add something else after it, then we need to turn it back to the form it was.

So I don't see any benefits in change it from the form it was.

**Comment by TheCycoONE** [comment]
Since you're fiddling with last_room, I don't think we clear it when staff are placed in the hall. Maybe we want to?

**Comment by ARGAMX** [comment]
> Since you're fiddling with last_room, I don't think we clear it when staff are placed in the hall. Maybe we want to?

I think that it actually exists and is cleaned quite well.
I always put docs in the hallway first, and then in the staff room if I want to keep them from going back to their room.
And this trick works good.
So looks like nothing to tweak.

**Review by ARGAMX — APPROVED** [review]
Good work 👍

**Review by Alberth289346 — APPROVED** [review]
LGTM
