### PR TITLE
Freeze patient's treatment cost when agreeing to pay

### LINKED ISSUE #2631: [Bug] 'AgreesToPay' check triggers not in a proper moment.
### Describe the issue

If patient already heading to the cure room you can set treatment charge at max value and patient will agree to pay. There is no any 'AgreesToPay' checks on queue join or room door opening.

Screenshot 2024-09-23 at 18 02 40

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. This is gamesave with 6 'Bloaty Head' Emergency guys in progress. Helicopter landing in progress.
3. While Helicopter not landed yet go to Casebook (F5).
4. Find 'Bloaty Head' in list.
5. Set 'treatment charge' at 200% (Hold Ctlr while to increase 25% at one mouse click).
6. Close Casebook and Wait until Helicopter landed and all 6 Emergency patients will shown on screen.
7. Observe that some patients from the Helicopter will refuse to pay price. (if non of them - repeat from step 1).

Screenshot 2024-09-23 at 18 03 40

8. Next. Check the opposite case. *Load save game attached to this ticket*
9. Wait until Helicopter landed and all 6 Emergency patients will shown on screen.
10. Go to Casebook (F5).
11. Find 'Bloaty Head' in list.
12. Set 'treatment charge' at 200%.
13. Observe that non of patients from the Helicopter will refuse to pay 200% price. (if doubt repeat from step 8).

'treatment charge' 100% - you got $5128 from this Emergency.
'treatment charge' 200% - you got $10253 from this Emergency.

### Expected Behaviour

1. 'AgreesToPay' check should be trigger as later as possible (at room door opening?). 
2. At this last check currently 'treatment charge' value should be binded to this patient cure process in this room. So if a treatment price will changed after he entered room but before patient paid this change should not affect the amount of his payment. After cure patient should pay this 'binded value', not the 'treatment charge' value from Casebook.

### Save Game

[bloaty_head_6_guys.sav.zip](https://github.com/user-attachments/files/17099973/bloaty_head_6_guys.sav.zip)

### CorsixTH Version

0.68.0 Beta 1

### Operating System

MacOS Sonoma 14.5

### PR DESCRIPTION
**Pull request by Matroftt**
* Fixes #2631 

**Describe what the proposed change does**
- Creates new variable `pay_amount` which stores the amount of treatment cost
- hospital:receiveMoneyForTreatment() now checks pay_amount variable instead of price in casebook

### CODE REVIEW

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 1]
```diff
@@ -295,12 +296,20 @@ function Patient:treatDisease()
...
+  self.pay_amount = hosp:getTreatmentPrice(disease_id)
+end
+
 --! Returns true if patient agrees to pay for the given treatment.
 --!param disease_id (string): The id of the disease to test
 function Patient:agreesToPay(disease_id)
   local casebook = self.hospital.disease_casebook[disease_id]
   local price_distortion = self:getPriceDistortion(casebook)
   local is_over_priced = price_distortion > self.hospital.over_priced_threshold
+  self:setTreatmentPrice(disease_id)
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/humanoids/patient.lua:312]: If you provide the price here, you don't need to look up the price through the hospital in 302/303.
That eliminates the casebook there completely.

I also wonder if you should store the disease alongside the amount in the patient, so you can check the patient is requested money for the same disease as was decided here.

File: CorsixTH/Lua/hospital.lua [hunk 2]
```diff
@@ -1399,7 +1399,7 @@ function Hospital:receiveMoneyForTreatment(patient)
     else
       reason = _S.transactions.cure_colon .. " " .. casebook.disease.name
     end
-    local amount = self:getTreatmentPrice(disease_id)
+    local amount = pay_amount or 0
```
Comment (Alberth289346) [inline CorsixTH/Lua/hospital.lua]: If you receive 0, does it make sense to perform payment at all, and create a floating dollarsign `$0` in the code below?

Comment (Alberth289346) [reply CorsixTH/Lua/hospital.lua]: this got changed already, closing.

File: CorsixTH/Lua/entities/humanoids/patient.lua (hunk 1 above)
Comment (Matroftt) [reply CorsixTH/Lua/entities/humanoids/patient.lua:312]: > If you provide the price here, you don't need to look up the price through the hospital in 302/303. That eliminates the casebook there completely.

So setTreatmentPrice() should be removed and code should move to agreesToPay?

File: CorsixTH/Lua/hospital.lua [hunk 3]
```diff
@@ -1388,7 +1388,7 @@ end
 
 !param patient (Patient) The patient that just got treated.
 ]]
-function Hospital:receiveMoneyForTreatment(patient)
+function Hospital:receiveMoneyForTreatment(patient, pay_amount)
   if not self.world.free_build_mode then
     local disease_id = patient:getTreatmentDiseaseId()
     if disease_id == nil then return end
```
Comment (lewri) [inline CorsixTH/Lua/hospital.lua:1394]: The second part of Alberth's comment about checking disease later would likely be referring to around here as an `assert`. Asserts resolve bugs faster at the cost of game recovery (`error` can be more recoverable). This doesn't sound like a priority though to look at.

**Review by lewri — COMMENTED** [review]
Not a refactor per-se, your title would be better as e.g. `Freeze patient's treatment cost when agreeing to pay`

File: CorsixTH/Lua/hospital.lua [hunk 4]
```diff
@@ -1399,7 +1399,7 @@ function Hospital:receiveMoneyForTreatment(patient)
     else
       reason = _S.transactions.cure_colon .. " " .. casebook.disease.name
     end
-    local amount = self:getTreatmentPrice(disease_id)
+    local amount = pay_amount or self:getTreatmentPrice(disease_id)
```
[the remark this answers is not in the document]
Comment (lewri) [reply CorsixTH/Lua/hospital.lua:1402]: You also should clear the patient's `self.pay_amount` after each treatment is paid (further down)

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 5]
```diff
@@ -275,6 +276,7 @@ function Patient:treatDisease()
   local hospital = self.hospital
 
   hospital:receiveMoneyForTreatment(self)
+  self.pay_amount = 0
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/patient.lua:279]: This function is only used for the final treatment. Reset it in `hospital:receiveMoneyForTreatment` instead.

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 6]
```diff
@@ -298,11 +300,15 @@ end
 --! Returns true if patient agrees to pay for the given treatment.
 --!param disease_id (string): The id of the disease to test
 function Patient:agreesToPay(disease_id)
+  local hosp = self.hospital
   local casebook = self.hospital.disease_casebook[disease_id]
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/patient.lua:304]:
```suggestion
  local casebook = hosp.disease_casebook[disease_id]
```

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 7]
```diff
@@ -298,11 +300,15 @@ end
...
   local price_distortion = self:getPriceDistortion(casebook)
   local is_over_priced = price_distortion > self.hospital.over_priced_threshold
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/patient.lua:306]:
```suggestion
  local is_over_priced = price_distortion > hosp.over_priced_threshold
```

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 8]
```diff
@@ -298,11 +300,15 @@ end
...
 
-  return not (is_over_priced and math.random(1, 5) == 1)
+  local agreesToPay = not (is_over_priced and math.random(1, 5) == 1)
+  if agreesToPay then self.pay_amount = hosp:getTreatmentPrice(disease_id) end
+
+  return agreesToPay
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/patient.lua:311]:
```suggestion
  if is_over_priced and math.random(1, 5) == 1 then return false end
  self.pay_amount = hosp:getTreatmentPrice(disease_id)

  return true
```

Does this look better to you? It's probably one of personal preference here. The luadoc at line 300 does already describe what your `return` means; you have just chosen to attach additional meaning with the variable (which isn't always bad).

**Review by lewri — COMMENTED** [review]
Some cleanup and one optional suggestion =]

File: CorsixTH/Lua/entities/humanoids/patient.lua (hunk 8 above)
Comment (Matroftt) [reply CorsixTH/Lua/entities/humanoids/patient.lua:311]: Yes, thanks

File: CorsixTH/Lua/entities/humanoids/patient.lua (hunk 5 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/patient.lua:279]: This one still needs to be resolved

Comment (Matroftt) [reply CorsixTH/Lua/entities/humanoids/patient.lua]: Done

**Review by lewri — APPROVED** [review]

File: CorsixTH/Lua/hospital.lua [hunk 9]
```diff
@@ -1399,7 +1399,7 @@ function Hospital:receiveMoneyForTreatment(patient)
     else
       reason = _S.transactions.cure_colon .. " " .. casebook.disease.name
     end
-    local amount = self:getTreatmentPrice(disease_id)
+    local amount = patient.pay_amount or self:getTreatmentPrice(disease_id)
```
Comment (TheCycoONE) [inline CorsixTH/Lua/hospital.lua:1402]: Note that in lua unlike javascript, 0 is truthy, so this doesn't guard against agreeToPay not being called and paying out 0.

Not blocking; just a question of intention.

Comment (lewri) [reply CorsixTH/Lua/hospital.lua:1402]: The guard to implement wouldn't be as plainly simple as just a ternary operator as far as I can tell. You'd probably need to conduct two separate checks to avoid a lengthy convoluted and/or statement.

Comment (lewri) [reply CorsixTH/Lua/hospital.lua:1402]:
```suggestion
    local amount = patient.pay_amount or 0
    amount = amount > 0 and amount or self:getTreatmentPrice(disease_id)
```
Would that work as a guard?

Comment (TheCycoONE) [reply CorsixTH/Lua/hospital.lua:1402]: Yes, or if patient.pay_amount is always numeric (which isn't yet true, it's set on new patient but missing afterLoad) then just your second line.
