### PR TITLE
[RDY] Enforce dynamic_info text key

### LINKED ISSUE #1410: nil value in drawDynamicInfo
#### Describe the issue

Crash

#### Steps to Reproduce

1. Just appear the crash, i dont know what i did

#### Save Game
[Autosave12.zip](https://github.com/CorsixTH/CorsixTH/files/2038333/Autosave12.zip)

#### System Information
**CorsixTH Version: 0.61 (last)
**Operating System: Windows 7 x64

**Theme Hospital Version: GOG.com

#### Gamelog.txt
```
[gamelog.txt](https://github.com/CorsixTH/CorsixTH/files/2038349/gamelog.txt)
```

### Additional Info
3a8f152463 1

### PR DESCRIPTION
**Pull request by TheCycoONE**
Resolves a crash if setDynamicInfo is given a table with a missing text
key. The source of the problem is now logged to gameLog without a crash.

Additional scaffholding was written to support verifying unit tests.

Fixes #1410

### CODE REVIEW

**Comment by TheCycoONE** [comment]
As for the luacheck errors, I'll fix the stub arguments in the functions. I need to figure out how to make it ignore the globals in describe blocks for busted (or maybe just the whole Luatest folder) because they are specifically handled and cleaned up by busted.

**Comment by TheCycoONE** [comment]
Resolved luacheck errors.

File: CorsixTH/Lua/dialogs/bottom_panel.lua [hunk 1]
```diff
@@ -206,29 +206,59 @@ end
...
+
+  if not (self.dynamic_info and self.dynamic_info["text"]) then
+    return
+  end
+
+  local info = self.dynamic_info
+  local font = self.white_font
+  for i, text in ipairs(info["text"]) do
+    font:drawWrapped(canvas, text, x + 20, y + 10 * i, 240)
+    if i == #info["text"] and info["progress"] then
```
Comment (Alberth289346) [inline CorsixTH/Lua/dialogs/bottom_panel.lua]: Seems a bit weird to special-check the last entry, and not even use either `i` or `text`, unless I am missing something.

File: CorsixTH/Lua/dialogs/bottom_panel.lua [hunk 2]
```diff
@@ -206,29 +206,59 @@ end
...
+--!   text: { "He's not the saviour", "He's very naughty boy" },
+--!   progress: 50,
+--!   dividers: { 25, 50, 75 }
+--! }
 function UIBottomPanel:setDynamicInfo(info)
+  if info and not info["text"] then
+    self.world:gameLog("")
+    self.world:gameLog("Dynamic info is missing text!")
+    self.world:gameLog("Please report this issue including the call stack below.")
+    self.world:gameLog(debug.traceback())
```
Comment (Alberth289346) [inline CorsixTH/Lua/dialogs/bottom_panel.lua]: :+1:

File: CorsixTH/Lua/dialogs/bottom_panel.lua (hunk 1 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/dialogs/bottom_panel.lua]: I didn't refactor that but it could certainly be pulled out of the loop. They are just drawing any progress bar after all text.
