### PR TITLE
[RDY] Queue dialog patient reordering fixes

### LINKED ISSUE #368: 0.40 beta2 - cannot reorder queue when an handyman is repairing a room
It happens also when the handyman is enqueued: when I dragged a patient in the queue the handyman pops in the first place.
Here is a savegame: https://www.dropbox.com/s/j1whztx62cxn2tc/Handyman.sav?dl=0
Look at the queue of the Operating Theater, you can't place the infectious patient at the first place until the handyman leaves the room.

### PR DESCRIPTION
**Pull request by mugmuggy**
#368 indicates some problems with queue reordering. I wasn't able to get an instance of the handyman at the front preventing a move of an epidemic patient, but I did manage to get a queue that happened to have 2 epidemic patients in it, and the order would not change.

I also got the other more easily observed issue of the handyman in room popping into and out of the queue when re-ordering. The changes here, insert re-ordered patients relative to the start of the 'reportedHumanoids' of the queue rather than the entire queue addresses both issues. And this appears to fix both issues.

### CODE REVIEW

File: CorsixTH/Lua/dialogs/queue_dialog.lua [hunk 1]
```diff
@@ -176,16 +176,17 @@ function UIQueue:onMouseUp(button, x, y)
       return
     end
 
+    local queue_reported_humans = queue:size() - num_patients
```
Comment (TheCycoONE) [inline CorsixTH/Lua/dialogs/queue_dialog.lua]: Funny name for this variable - not clear what it represents. (I assume from the context that it's people who need to use the door that are not part of the patient queue, like staff that need to enter the room.)

Comment (mugmuggy) [reply CorsixTH/Lua/dialogs/queue_dialog.lua]: Yeah a little funky, in light of this I've done a refactor and I'll push that out once I tested it, as its a little more readable also. This currently has this changed to first_patient_index

File: CorsixTH/Lua/dialogs/queue_dialog.lua [hunk 2]
```diff
@@ -176,16 +176,17 @@ function UIQueue:onMouseUp(button, x, y)
       return
     end
 
+    local first_patient_index = queue:size() - num_patients + 1
```
Comment (TheCycoONE) [inline CorsixTH/Lua/dialogs/queue_dialog.lua]: Same calculation used in 169. Maybe move this up where num_patients is defined (or into queue)

**Comment by TheCycoONE** [comment]
I'm concerned this breaks with emergencies. Emergency patients are at the front of the queue ahead of newly arriving VIPs etc.

**Comment by TheCycoONE** [comment]
I'm not sure that was original behavior, nor that it makes sense. Maybe take a closer look at queue.lua

**Comment by TheCycoONE** [comment]
Doesn't break with emergencies, as inspectors and VIPs are in the reported size, and staff/anyone leaving are at the front.

Still suggesting to handle this from queue.lua so it's not a leaked implementation detail.

**Comment by mugmuggy** [comment]
Ok, queue:move is only used by the queue dialog already anyway, so I could probably move that detail there or implement the logic in a wrapper around queue:move.

**Comment by TheCycoONE** [comment]
@mugmuggy if you've already started go ahead; otherwise just move the calculation up.

queue isn't quite sure how it wants to present indexes / sizes etc. 😝

**Comment by TheCycoONE** [comment]
I like it. Will need to review the proper LuaDoc style later. In JSDoc it would have been (int|string) with one parameter.
