### PR TITLE
Fix long windows 

### LINKED ISSUE #2070: [Bug] Long windows do not  behave normally when a room is made
image
When you put rooms next to long windows, the windows disappear. If the room is removed, there will be a void.

#### System Information
**CorsixTH Version:** 0.65.1

### PR DESCRIPTION
**Pull request by Matroftt**
* Fixes #2070 

**Describe what the proposed change does**
- Makes long windows no longer dissappear
- Add long windows to the external.lua table

You can use [long_windows.zip](https://github.com/user-attachments/files/16511418/long_windows.zip) or [long_windows_2.zip](https://github.com/user-attachments/files/16562287/long_windows_map_updated.zip) maps that i created to test this PR

The image below shows the behavior of long windows:
image

### CODE REVIEW

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 1]
```diff
@@ -413,6 +413,13 @@ function UIEditRoom:finishRoom()
         end
         map:setCell(x, y, layer, flag + tiles.north)
       end
+	elseif dir == "north_window_long" then
+      if x ~= rect.x then
+	    map:setCell(x, y, layer, flag + tiles.north)
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua:418]:
```suggestion
  	    map:setCell(x, y, layer, flag + tiles.north)
```

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 2]
```diff
@@ -427,6 +434,13 @@ function UIEditRoom:finishRoom()
         end
         map:setCell(x, y, layer, flag + tiles.west)
       end
+	elseif dir == "west_window_long" then
+      if x ~= rect.x then
+		map:setCell(x, y, layer, flag + tiles.west)
+        if map:getCell(x, y + 1, layer) ~= 0 then
+          map:setCell(x, y + 1, layer, flag + tiles.west)
+        end
+      end
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua:443]:
```suggestion
    if x ~= rect.x then
		  map:setCell(x, y, layer, flag + tiles.west)
      if map:getCell(x, y + 1, layer) ~= 0 then
        map:setCell(x, y + 1, layer, flag + tiles.west)
      end
    end
```

**Review by lewri — COMMENTED** [review]
Spacing is incorrect, those corrections should resolve it.

File: CorsixTH/Lua/dialogs/edit_room.lua (hunk 2 above)
Comment (lewri) [reply CorsixTH/Lua/dialogs/edit_room.lua:443]: Conversation view made this suggestion look even worse, but it looks fine on the files tab

**Comment by Matroftt** [comment]
Done

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 3]
```diff
@@ -413,6 +413,13 @@ function UIEditRoom:finishRoom()
         end
         map:setCell(x, y, layer, flag + tiles.north)
       end
+	elseif dir == "north_window_long" then
+      if x ~= rect.x then
+  	    map:setCell(x, y, layer, flag + tiles.north)
+        if map:getCell(x + 1, y, layer) ~= 0 then
+          map:setCell(x + 1, y, layer, flag + tiles.north)
+        end
+      end
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua:422]:
```suggestion
    elseif dir == "north_window_long" then
      if x ~= rect.x then
        map:setCell(x, y, layer, flag + tiles.north)
        if map:getCell(x + 1, y, layer) ~= 0 then
          map:setCell(x + 1, y, layer, flag + tiles.north)
        end
      end
```

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 4]
```diff
@@ -427,6 +434,13 @@ function UIEditRoom:finishRoom()
         end
         map:setCell(x, y, layer, flag + tiles.west)
       end
+	elseif dir == "west_window_long" then
+    if x ~= rect.x then
+		  map:setCell(x, y, layer, flag + tiles.west)
+      if map:getCell(x, y + 1, layer) ~= 0 then
+        map:setCell(x, y + 1, layer, flag + tiles.west)
+      end
+    end
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua:443]:
```suggestion
    elseif dir == "west_window_long" then
      if x ~= rect.x then
        map:setCell(x, y, layer, flag + tiles.west)
        if map:getCell(x, y + 1, layer) ~= 0 then
          map:setCell(x, y + 1, layer, flag + tiles.west)
        end
      end
```

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 5]
```diff
@@ -418,15 +422,43 @@ function UIEditRoom:finishRoom()
...
         end
         map:setCell(x, y, layer, flag + tiles.west)
       end
+    elseif dir == "north_window_long" then
+      if x == rect.x then
+        map:setCell(x, y, layer, flag + tiles.north)
+        if map:getCell(x - 1, y, layer) ~= 0 and map:getCell(x - 1, y, layer) ~= 118 then
+          map:setCell(x - 1, y, layer, flag + tiles.north)
+        end
+      elseif x ~= rect.x then
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua:444]: This can be just `else` as the if above already infers this.

File: CorsixTH/Lua/dialogs/edit_room.lua [hunk 6]
```diff
@@ -418,15 +422,43 @@ function UIEditRoom:finishRoom()
...
+          map:setCell(x + 1, y, layer, flag + tiles.north)
+        end
+      end
+    elseif dir == "west_window_long" then
+      if y == rect.y then
+        map:setCell(x, y, layer, flag + tiles.west)
+        if map:getCell(x, y - 1, layer) ~= 0 and map:getCell(x, y - 1, layer) ~= 119 then
+          map:setCell(x, y - 1, layer, flag + tiles.west)
+        end
+      elseif y ~= rect.y then
```
Comment (lewri) [inline CorsixTH/Lua/dialogs/edit_room.lua:456]: Same as other comment, just `else` if fine here

**Comment by lewri** [comment]
Could you add images to your top post just showing what the change does re long windows? Just helps us document the new behaviour more transparently.

**Comment by lewri** [comment]
@Alberth289346 if you could check over this before merge that would assist. A refactor would be nice but I'm not seeking it out to be done right now.

As far as my testing went the windows behave as the images represent.

**Comment by Alberth289346** [comment]
After a bit of rewriting, it looks like a consistent pattern to me.

I didn't try running the patched version, please do that if you like the patch.
``` diff
diff --git a/CorsixTH/Lua/dialogs/edit_room.lua b/CorsixTH/Lua/dialogs/edit_room.lua
index 0a1b3891..8b4afc71 100644
--- a/CorsixTH/Lua/dialogs/edit_room.lua
+++ b/CorsixTH/Lua/dialogs/edit_room.lua
@@ -393,12 +393,25 @@ function UIEditRoom:finishRoom()
   if self.ui.transparent_walls then
     flag = 1024
   end
+
   local function check_external_window(x, y, layer)
+    -- Test it is a wall, but not spr_num
+    local function is_wall_and_not(x, y, spr_num)
+      return map:getCell(x, y, layer) ~= 0
+          and map:getCell(x, y, layer) ~= spr_num
+    end
+    -- Test that the wall is either spr_num1 or spr_num2.
+    local function is_one_of_wall(x, y, spr_num1, spr_num2)
+      return  map:getCell(x + 2, y, layer) == spr_num1
+          or map:getCell(x + 2, y, layer) == spr_num2
+
     -- If a wall is built which is normal to an external window, then said
     -- window needs to be removed, otherwise it looks odd.
     local block = map:getCell(x, y, layer)
     local dir = world:getWallDirFromBlockId(block)
     local tiles = self.ui.app.walls.external[world:getWallSetFromBlockId(block)]
+
+    -- Dispatch on the wall tiles at (x, y)
     if dir == "north_window_1" then
       if x ~= rect.x then
         map:setCell(x, y, layer, flag + tiles.north)
@@ -406,6 +419,7 @@ function UIEditRoom:finishRoom()
           map:setCell(x + 1, y, layer, flag + tiles.north)
         end
       end
+
     elseif dir == "north_window_2" then
       if x == rect.x then
         if map:getCell(x - 1, y, layer) ~= 0 then
@@ -413,6 +427,7 @@ function UIEditRoom:finishRoom()
         end
         map:setCell(x, y, layer, flag + tiles.north)
       end
+
     elseif dir == "west_window_1" then
       if y == rect.y then
         map:setCell(x, y, layer, flag + tiles.west)
@@ -420,6 +435,7 @@ function UIEditRoom:finishRoom()
           map:setCell(x, y - 1, layer, flag + tiles.west)
         end
       end
+
     elseif dir == "west_window_2" then
       if y ~= rect.y then
         if map:getCell(x, y + 1, layer) ~= 0 then
@@ -427,14 +443,16 @@ function UIEditRoom:finishRoom()
         end
         map:setCell(x, y, layer, flag + tiles.west)
       end
+
     elseif dir == "north_window_long" then
       if x == rect.x then
         map:setCell(x, y, layer, flag + tiles.north_window_1)
         -- Check if the window_long continues.
         -- If yes, replace the window_long with window_n.
         -- if no, replace it with the wall.
-        if map:getCell(x - 1, y, layer) ~= 0 and map:getCell(x - 1, y, layer) ~= 118 then
-          if map:getCell(x - 2, y, layer) == 120 or map:getCell(x - 2, y, layer) == 116 then
+        if is_wall_and_not(x - 1, y, tiles.north_window_2) then
+          if is_one_of_wall(x - 2, y,
+              tiles.north_window_long, tiles.north_window_1) then
             map:setCell(x - 1, y, layer, flag + tiles.north_window_2)
           else
             map:setCell(x - 1, y, layer, flag + tiles.north)
@@ -442,19 +460,22 @@ function UIEditRoom:finishRoom()
         end
       else
         map:setCell(x, y, layer, flag + tiles.north_window_2)
-        if map:getCell(x + 1, y, layer) ~= 0 and map:getCell(x + 1, y, layer) ~= 116 then
-          if map:getCell(x + 2, y, layer) == 120 or map:getCell(x + 2, y, layer) == 118 then
+        if is_wall_and_not(x + 1, y, tiles.north_window_1) then
+          if is_one_of_wall(x + 2, y,
+              tiles.north_window_long, tiles.north_window_2) then
             map:setCell(x + 1, y, layer, flag + tiles.north_window_1)
           else
             map:setCell(x + 1, y, layer, flag + tiles.north)
           end
         end
       end
+
     elseif dir == "west_window_long" then
       if y == rect.y then
         map:setCell(x, y, layer, flag + tiles.west_window_2)
-        if map:getCell(x, y - 1, layer) ~= 0 and map:getCell(x, y - 1, layer) ~= 119 then
-          if map:getCell(x, y - 2, layer) == 121 or map:getCell(x, y - 2, layer) == 117 then
+        if is_wall_and_not(x, y - 1, tiles.west_window_1) then
+          if is_one_of_wall(x, y - 2,
+              tiles.west_window_long, tiles.west_window_2) then
             map:setCell(x, y - 1, layer, flag + tiles.west_window_1)
           else
             map:setCell(x, y - 1, layer, flag + tiles.west)
@@ -462,8 +483,9 @@ function UIEditRoom:finishRoom()
         end
       else
         map:setCell(x, y, layer, flag + tiles.west_window_1)
-        if map:getCell(x, y + 1, layer) ~= 0 and map:getCell(x, y + 1, layer) ~= 117 then
-          if map:getCell(x, y + 2, layer) == 121 or map:getCell(x, y + 2, layer) == 119 then
+        if is_wall_and_not(x, y + 1, tiles.west_window_2) then
+          if is_one_of_wall(x, y + 2,
+              tiles.west_window_long, tiles.west_window_1) then
             map:setCell(x, y + 1, layer, flag + tiles.west_window_2)
           else
             map:setCell(x, y + 1, layer, flag + tiles.west)
@@ -472,6 +494,7 @@ function UIEditRoom:finishRoom()
       end
     end
   end
+
   for x, obj in pairs(self.blueprint_wall_anims) do
     for y, anim in pairs(obj) do
       if x == rect.x and y == rect.y then
```

**Review by Alberth289346 — APPROVED** [review]

**Comment by lewri** [comment]
> After a bit of rewriting, it looks like a consistent pattern to me.
> 
> I didn't try running the patched version, please do that if you like the patch.
> 
> ```diff
> diff --git a/CorsixTH/Lua/dialogs/edit_room.lua b/CorsixTH/Lua/dialogs/edit_room.lua
> index 0a1b3891..8b4afc71 100644
> --- a/CorsixTH/Lua/dialogs/edit_room.lua
> +++ b/CorsixTH/Lua/dialogs/edit_room.lua
> @@ -393,12 +393,25 @@ function UIEditRoom:finishRoom()
>    if self.ui.transparent_walls then
>      flag = 1024
>    end
> +
>    local function check_external_window(x, y, layer)
> +    -- Test it is a wall, but not spr_num
> +    local function is_wall_and_not(x, y, spr_num)
> +      return map:getCell(x, y, layer) ~= 0
> +          and map:getCell(x, y, layer) ~= spr_num
> +    end
> +    -- Test that the wall is either spr_num1 or spr_num2.
> +    local function is_one_of_wall(x, y, spr_num1, spr_num2)
> +      return  map:getCell(x, y, layer) == spr_num1
> +          or map:getCell(x, y, layer) == spr_num2
> +
>      -- If a wall is built which is normal to an external window, then said
>      -- window needs to be removed, otherwise it looks odd.
>      local block = map:getCell(x, y, layer)
>      local dir = world:getWallDirFromBlockId(block)
>      local tiles = self.ui.app.walls.external[world:getWallSetFromBlockId(block)]
> +
> +    -- Dispatch on the wall tiles at (x, y)
>      if dir == "north_window_1" then
>        if x ~= rect.x then
>          map:setCell(x, y, layer, flag + tiles.north)
> @@ -406,6 +419,7 @@ function UIEditRoom:finishRoom()
>            map:setCell(x + 1, y, layer, flag + tiles.north)
>          end
>        end
> +
>      elseif dir == "north_window_2" then
>        if x == rect.x then
>          if map:getCell(x - 1, y, layer) ~= 0 then
> @@ -413,6 +427,7 @@ function UIEditRoom:finishRoom()
>          end
>          map:setCell(x, y, layer, flag + tiles.north)
>        end
> +
>      elseif dir == "west_window_1" then
>        if y == rect.y then
>          map:setCell(x, y, layer, flag + tiles.west)
> @@ -420,6 +435,7 @@ function UIEditRoom:finishRoom()
>            map:setCell(x, y - 1, layer, flag + tiles.west)
>          end
>        end
> +
>      elseif dir == "west_window_2" then
>        if y ~= rect.y then
>          if map:getCell(x, y + 1, layer) ~= 0 then
> @@ -427,14 +443,16 @@ function UIEditRoom:finishRoom()
>          end
>          map:setCell(x, y, layer, flag + tiles.west)
>        end
> +
>      elseif dir == "north_window_long" then
>        if x == rect.x then
>          map:setCell(x, y, layer, flag + tiles.north_window_1)
>          -- Check if the window_long continues.
>          -- If yes, replace the window_long with window_n.
>          -- if no, replace it with the wall.
> -        if map:getCell(x - 1, y, layer) ~= 0 and map:getCell(x - 1, y, layer) ~= 118 then
> -          if map:getCell(x - 2, y, layer) == 120 or map:getCell(x - 2, y, layer) == 116 then
> +        if is_wall_and_not(x - 1, y, tiles.north_window_2) then
> +          if is_one_of_wall(x - 2, y,
> +              tiles.north_window_long, tiles.north_window_1) then
>              map:setCell(x - 1, y, layer, flag + tiles.north_window_2)
>            else
>              map:setCell(x - 1, y, layer, flag + tiles.north)
> @@ -442,19 +460,22 @@ function UIEditRoom:finishRoom()
>          end
>        else
>          map:setCell(x, y, layer, flag + tiles.north_window_2)
> -        if map:getCell(x + 1, y, layer) ~= 0 and map:getCell(x + 1, y, layer) ~= 116 then
> -          if map:getCell(x + 2, y, layer) == 120 or map:getCell(x + 2, y, layer) == 118 then
> +        if is_wall_and_not(x + 1, y, tiles.north_window_1) then
> +          if is_one_of_wall(x + 2, y,
> +              tiles.north_window_long, tiles.north_window_2) then
>              map:setCell(x + 1, y, layer, flag + tiles.north_window_1)
>            else
>              map:setCell(x + 1, y, layer, flag + tiles.north)
>            end
>          end
>        end
> +
>      elseif dir == "west_window_long" then
>        if y == rect.y then
>          map:setCell(x, y, layer, flag + tiles.west_window_2)
> -        if map:getCell(x, y - 1, layer) ~= 0 and map:getCell(x, y - 1, layer) ~= 119 then
> -          if map:getCell(x, y - 2, layer) == 121 or map:getCell(x, y - 2, layer) == 117 then
> +        if is_wall_and_not(x, y - 1, tiles.west_window_1) then
> +          if is_one_of_wall(x, y - 2,
> +              tiles.west_window_long, tiles.west_window_2) then
>              map:setCell(x, y - 1, layer, flag + tiles.west_window_1)
>            else
>              map:setCell(x, y - 1, layer, flag + tiles.west)
> @@ -462,8 +483,9 @@ function UIEditRoom:finishRoom()
>          end
>        else
>          map:setCell(x, y, layer, flag + tiles.west_window_1)
> -        if map:getCell(x, y + 1, layer) ~= 0 and map:getCell(x, y + 1, layer) ~= 117 then
> -          if map:getCell(x, y + 2, layer) == 121 or map:getCell(x, y + 2, layer) == 119 then
> +        if is_wall_and_not(x, y + 1, tiles.west_window_2) then
> +          if is_one_of_wall(x, y + 2,
> +              tiles.west_window_long, tiles.west_window_1) then
>              map:setCell(x, y + 1, layer, flag + tiles.west_window_2)
>            else
>              map:setCell(x, y + 1, layer, flag + tiles.west)
> @@ -472,6 +494,7 @@ function UIEditRoom:finishRoom()
>        end
>      end
>    end
> +
>    for x, obj in pairs(self.blueprint_wall_anims) do
>      for y, anim in pairs(obj) do
>        if x == rect.x and y == rect.y then
> ```
> 
> EDIT: Fixed a bug

Should this be its own commit ontop or a pr following this one?
