### PR TITLE
Move the emergency announcement and advice to the first patient spawn

### LINKED ISSUE #2419: [Bug] Accepting Emergency immediately triggers staff announcement/adviser message
### Describe the issue

There is a minor discrepancy with Emergencies when compared to Theme Hospital:

- In Theme Hospital, after accepting an Emergency, a short period of time will pass. When the emergency helicopter spawns, the Receptionist makes a staff announcement (EMERG0XX - "Staff announcement, incoming patients with [disease]"). When the helicopter lands on the helipad, the Adviser will inform you that the Emergency has started ("There's an emergency! Move! Move! MOVE!")

- In CorsixTH, after accepting an Emergency, the staff announcement and the Adviser's message will trigger _immediately_. A short period of time will then pass before the emergency helicopter spawns.

We should replicate the behaviour of Theme Hospital wherever possible, especially since it would be more useful to inform the player when the emergency patients are arriving.

### Steps to Reproduce

1. Load the save game attached to this ticket (or play CorsixTH until the Emergency notification appears)
2. Click the Emergency notification
3. Accept the Emergency

### Expected Behaviour

- [ ] The Receptionist's staff announcement should be heard when the emergency helicopter spawns, not when the user clicks Accept on the fax screen.
- [ ] The Adviser's "There's an emergency" message should appear when the emergency helicopter touches the helipad, not when the user clicks Accept on the fax screen.

### Save Game

Save game attached to report: Yes
[emergencyStart.zip](https://github.com/CorsixTH/CorsixTH/files/12753070/emergencyStart.zip)

### CorsixTH Version

0.67

### Operating System

Windows 10

### Theme Hospital Version

CD

### Gamelog.txt

_No response_

### Additional Information
The expected behaviour can be seen in this Theme Hospital playthrough on YouTube: https://youtu.be/ghKsxtrFSzY?t=513

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #2419*

**Describe what the proposed change does**
- Move the announcement and advisor message from when the fax is accepted to when the first patient spawns. I looked at a few videos on youtube and this is about the right time, sometimes it appears to be around when the second or third patient spawns.

### CODE REVIEW

**Comment by MandrakeHorse** [comment]
[I found this Theme Hospital playthrough on YouTube](https://youtu.be/ghKsxtrFSzY?t=513) which slightly deviates from the behaviour currently implemented by this pull request:
- When the helicopter spawns, the Staff Announcement is made.
- When the helicopter touches the helipad, the Adviser informs the player. A few seconds later, the emergency patients start spawning.

File: CorsixTH/Lua/objects/helicopter.lua [hunk 1]
```diff
@@ -62,6 +66,12 @@ function Helicopter:tick()
     self:setSpeed(0, 0)
     self.spawned_patients = 0
   elseif phase == 85 then
+    if not self.announced then
+      local ui = TheApp.ui
+      ui:playAnnouncement(ui.hospital.emergency.disease.emergency_sound, AnnouncementPriority.Critical)
+      ui.adviser:say(_A.information.emergency)
+      self.announced = true
+    end
```
Comment (lewri) [inline CorsixTH/Lua/objects/helicopter.lua:74]: While I said I would be fine with tying it to the helicopter, my only query is whether tying it into phase is the correct thing?  Should the helicopter be deciding to trigger these events?
If for some reason in future we used the helicopter for something else then this would trigger the emergency texts.

Comment (tobylane) [reply CorsixTH/Lua/objects/helicopter.lua]: We can define that later, add a helicopter.type when we know what the other use is.

**Comment by tobylane** [comment]
Adjusted to MandrakeHorse's timing.

File: CorsixTH/Lua/objects/helicopter.lua [hunk 2]
```diff
@@ -55,12 +58,15 @@ end
...
   local phase = self.phase
+  local ui = TheApp.ui
   if phase == 0 then
     self.th:makeVisible()
     self:setSpeed(0, 10)
+    ui:playAnnouncement(ui.hospital.emergency.disease.emergency_sound, AnnouncementPriority.Critical)
   elseif phase == 60 then
     self:setSpeed(0, 0)
     self.spawned_patients = 0
+    ui.adviser:say(_A.information.emergency)
```
Comment (lewri) [inline CorsixTH/Lua/objects/helicopter.lua:69]: Query, shouldn't an emergency be an overriding adviser message?

**Review by lewri — APPROVED** [review]
Approving regardless of my note earlier
