### PR TITLE
Adjust mood icons

### LINKED ISSUE #2770: [Bug] Patients. Bad mood icon overlaps death timer icon.
### Describe the issue

If patient have bad mood and near the death, bad mood icon will show above his head instead of death timer icon.

Image

### Steps to Reproduce

1. *Load `death_timer_icon_missing.sav` save game attached to this ticket*
2. Observe that all patients in queue have bad mood icon no one have death timer icon. But you hear and see that some of them in queue periodically die outside of cabinet.
3. *Load `death_timer_icon.sav` save game attached to this ticket*
4. Observe that now patients have better mood and there no much of bad mood icons. And at the same time you can see death timer icons.

### Expected Behaviour

Death timer icon should be higher priority than bad mood icon.

### Save Game

[death_timer_icon_missing.sav.zip](https://github.com/user-attachments/files/18562968/death_timer_icon_missing.sav.zip)

[death_timer_icon.sav.zip](https://github.com/user-attachments/files/18562970/death_timer_icon.sav.zip)

### CorsixTH Version

level started in 0.65.0, played in 0.68.0

### Operating System

MacOS Sonoma 14.5

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2770*

**Describe what the proposed change does**
- Renames `sad7` to `sad2`
- Renames `sad2 - sad6` to `dying1 - dying5`
- Adjusts priority of  new `sad2` to be before `dying` moods
- Adjusts patient wait mood priority to coincide
- Restructures comments
- Updates affected humanoids with old `sad2` and `sad7`. The other sad ones won't matter, as the mood priority order will trump them anyway as they die more / cure / die.

@ARGAMX -- I have a suspicion this PR currently might have changed behaviour of the patient wait icon. However, sad2 is still trumping patient_wait as before so I think I've just imagined it.
If possible, I can adjust it if the original has a specified behaviour so wait has priority over regular sadness.

### CODE REVIEW

File: CorsixTH/Lua/entities/humanoid.lua [hunk 1]
```diff
@@ -341,6 +345,18 @@ function Humanoid:afterLoad(old, new)
   if old < 134 and new >= 134 then
     self.staff_change_callbacks = {}
   end
+  if old < 210 then
+    -- We renamed the old sad7 to sad2; and sad2 to dying1. Make sure we adjust
+    -- sad2 to the new mood
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoid.lua:350]: Should be `sad2 and sad7`

File: CorsixTH/Lua/entities/humanoid.lua [hunk 2]
```diff
@@ -235,35 +235,39 @@ pee_anim("Invisible Patient",          4208)
...
 moods("tired",          3990,      30)
 moods("pay_rise",       4576,      40)
 moods("thirsty",        3986,       4)
 moods("cold",           3994,       0,       true) -- These have no priority since
-moods("hot",            3988,       0,       true) -- they will be shown when hovering
-moods("queue",          4568,      70)             -- no matter what other priorities.
+moods("hot",            3988,       0,       true) -- they will be shown when
+                                                   -- hovering
+moods("queue",          4568,      70)             -- no matter what other
+                                                   -- priorities.
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/humanoid.lua:256]: I'd probably move the `true)` a bit to the left so you have enough room.
Priority numbers could move to the left as well, if desired.

File: CorsixTH/Lua/entities/humanoid.lua [hunk 3]
```diff
@@ -341,6 +345,18 @@ function Humanoid:afterLoad(old, new)
...
+    -- We renamed the old sad7 to sad2; and sad2 to dying1. Make sure we adjust
+    -- sad2 to the new mood
+    if self:isMoodActive("sad2") then
+      self:setMood("sad2", "deactivate")
+      self:setMood("dying1", "activate")
+    end
+    if self:isMoodActive("sad7") then
+      self:setMood("sad7", "deactivate")
+      self:setMood("sad2", "activateW")
+    end
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/humanoid.lua:358]: This is fine. An alternative can be

``` lua
local changed_moods = {{old="sad2", new="dying1"}, {old="sad7", new="sad2"}}
for _, change in ipairs(changed_moods) do
  if self:isMoodActive(change.old) then
    self:setMood(change.old, "deactivate")
    self:setMood(change.new, "activate")
  end
end
```

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 4]
```diff
@@ -601,38 +601,38 @@ function Patient:tickDay()
...
+    self:setMood("dying4", "deactivate")
+    self:setMood("dying5", "activate")
   -- it's not looking good
   elseif health > 0.00 and health < 0.01 then
     self.attributes["health"] = 0.0
   -- is there time to say a prayer
   elseif health == 0.0 then
     if not self:getRoom() and not self:getCurrentAction().is_leaving then
-      self:setMood("sad6", "deactivate")
+      self:setMood("dying5", "deactivate")
```
Comment (Alberth289346) [inline CorsixTH/Lua/entities/humanoids/patient.lua:635]: Not your fault, but the witty remarks aren't useful, and I feel this should be a table of conditions and corresponding moods instead of this if-with-many-alternatives statement.

I can live with not changing it. (Technically it's also out of scope.)

File: CorsixTH/Lua/entities/humanoid.lua (hunk 3 above)
Comment (Alberth289346) [reply CorsixTH/Lua/entities/humanoid.lua:358]: I somewhat wonder if the afterload is worth it, assuming most moods are temporary, but this is fine.

File: CorsixTH/Lua/entities/humanoid.lua (hunk 1 above)
Comment (Alberth289346) [reply CorsixTH/Lua/entities/humanoid.lua:350]: Euhm, sad3 to 7 are no dying1 to 5 as well.

**Comment by ARGAMX** [comment]
> @ARGAMX -- I have a suspicion this PR currently might have changed behaviour of the patient wait icon. However, sad2 is still trumping patient_wait as before so I think I've just imagined it.
> If possible, I can adjust it if the original has a specified behaviour so wait has priority over regular sadness.

In the vanilla TH, the waiting icon has priority over the death icons.

bloaty-head-waiting-icon

But in the original game, the waiting icon accompanied with the fax. In CTH, it can appears in some other rare situations. But I think it is currently unimportant.

Also I tried to get the waiting icon for emergency patients. But the fax for emergency patients does not arrive. So it did not work.

So I recommend to put `patient_wait` icon between `dying5` and `epidemy4`. For example put it at priority `48`.

**Comment by ARGAMX** [comment]
> > @ARGAMX -- I have a suspicion this PR currently might have changed behaviour of the patient wait icon. However, sad2 is still trumping patient_wait as before so I think I've just imagined it.
> > If possible, I can adjust it if the original has a specified behaviour so wait has priority over regular sadness.
> 

Perhaps the icons should be arranged according to this priority order:

sad_money (higher)
emergency
patient_wait 
epidemy1	-- vaccinated (step 4)
epidemy3	-- choosed by nurse (step 3)
epidemy2	-- marked (step 2)
epidemy4	-- infected (step 1)
dying5
dying4
dying3
dying2
dying1
sad2
sad1 (lower)

(move emergency and patient_wait up)

File: CorsixTH/Lua/entities/humanoid.lua (hunk 1 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoid.lua:350]: Oops my bad!

File: CorsixTH/Lua/entities/humanoid.lua [hunk 5]
```diff
@@ -235,35 +235,39 @@ pee_anim("Invisible Patient",          4208)
 pee_anim("Transparent Female Patient", 4852)
 pee_anim("Transparent Male Patient",   4848)
 
+-- Some icons should only appear when the player hovers over the humanoid
+-- Higher priority is more important.
 --   | Available Moods |
 --   | Name            |Icon|Priority|Show Always| Notes
```
Comment (ARGAMX) [inline CorsixTH/Lua/entities/humanoid.lua:241]: Not your, but

I wonder why "show this icon only on hover" (`on_hover`) titled as "Show Always" (`alwaysOn`) ?... 
it's like it's somehow confusing a bit.

If I hadn't known that the temperature icons only show up when you hover (not always actually), I probably wouldn't have been able to understand this correctly.

**Review by ARGAMX — APPROVED** [review]

**Comment by Alberth289346** [comment]
LGTM
