### PR TITLE
Use SDL_RenderCopyF on SDL 2.0.10 and newer for better scaling

### LINKED ISSUE #1953: [Bug] Sometimes 1px of walls slightly clip through intersecting walls
#### Describe the issue

Sometimes at certain zoom levels (with direct_zoom = true) 1px of the west-most edge of a wall facing SE can clip through the intersecting SW facing wall it adjoins.

#### Steps to Reproduce
1. Set `direct_zoom = true` in config.txt
 
2. Load the attached save.

3. Examine the walls connecting to the southwest edge of the hospital as you move the viewport around.

#### Save Game
[test.zip](https://github.com/CorsixTH/CorsixTH/files/6698115/test.zip)

#### Expected Behavior

Expect the interior walls not to show at all through the exterior.

#### System Information
**CorsixTH Version:** *0.6.5*

**Operating System:** *Linux*

**Theme Hospital Version:** *GOG.com*

#### Gamelog.txt
N/a

### Additional Info
wall-clipping

### PR DESCRIPTION
**Pull request by flackr**
*Fixes #1953*

**Describe what the proposed change does**
- When using SDL 2.0.10 or newer, uses SDL_FRect and SDL_RenderCopyF to improve scaling precision.
- When using SDL 2.0.9 or older, uses SDL_Rect and the enclosing integer SDL_Rect for compatibility.

### CODE REVIEW

File: CorsixTH/Src/th_gfx_sdl.cpp [hunk 1]
```diff
@@ -119,6 +119,33 @@ void getEnclosingScaleRect(const SDL_Rect* rect, double scale_factor,
...
+  dst_rect->h = static_cast<float>(rect->h * scale_factor);
+}
+
+#else
+
+// Prior to SDL 2.0.10, fallback to using the enclosing integer SDL_Rect for
+// scaled rendering.
+#define SDL_FRect SDL_Rect
+#define SDL_RenderCopyF SDL_RenderCopy
+#define SDL_RenderCopyExF SDL_RenderCopyEx
```
Comment (flackr) [inline CorsixTH/Src/th_gfx_sdl.cpp:140]: Not sure if you'd prefer we make up names e.g. SDL_SCALED_RECT, SDL_RENDER_COPY_SCALED, SDL_RENDER_COPY_SCALED_EX to avoid the presumption that where you see SDL_FRect you always have a floating point rect rather than it depending on sdl version. Let me know I'm happy to change it.

Comment (TheCycoONE) [reply CorsixTH/Src/th_gfx_sdl.cpp:140]: This is fine. I doubt we'll be doing much more work with older SDL versions.

**Comment by flackr** [comment]
I think it's a bit cleaner to have a single function definition (now documented) and just switch the body out based on the SDL version so I've done that and tested on both sides of the SDL version to make sure everything works correctly.
