### PR TITLE
Pair swing doors instantly

### LINKED ISSUE #2389: [Bug] Game gets stuck after hover over door
### Describe the issue

Game got stuck after hovering over bedroom door. I can't resume it and I can't resume from paused

### Steps to Reproduce

1. *Load save game attached to this ticket*

2. Hover over bedroom door.

How I managed to do this
1. Started game, paused, built the hospital, wanted to hire a nurse, selected a nurse to hire, when selecting where to place her, hover over bedroom door. The mouse got stuck, but I can call menus via keyboard, but not resume the game.

### Expected Behaviour

Not get stuck

### Save Game

Save game attached to report: Yes
[quicksave.zip](https://github.com/CorsixTH/CorsixTH/files/12413238/quicksave.zip)

### CorsixTH Version

0.67 fedora build

### Operating System

Fedora 38

### Theme Hospital Version

CD

### Gamelog.txt

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #2389*

**Describe what the proposed change does**
- Ward and Operating Theatre doors are paired within the same tick, when built or loaded from an old save.

### CODE REVIEW

File: CorsixTH/Lua/objects/doors/swing_door_right.lua [hunk 1]
```diff
@@ -39,18 +39,14 @@ function SwingDoor:SwingDoor(hospital, object_type, x, y, direction, etc)
...
-      self.slave = self.world:getObject(x - 1, y, slave_type) or self.world:getObject(x, y - 1, slave_type) or nil
-      self.slave:setAsSlave(self)
-      self.ticks = false
-    end
-    self:setTimer(1, callback)
-    self.ticks = true
+    local slave_type = "swing_door_left"
+    self.slave = self.world:getObject(x - 1, y, slave_type) or self.world:getObject(x, y - 1, slave_type) or nil
+    self.slave:setAsSlave(self)
+    assert(self.slave.master, "Swing doors are not paired at " .. x .. "," .. y)
```
Comment (lewri) [inline CorsixTH/Lua/objects/doors/swing_door_right.lua:45]: Is this assert for testing or have we thoroughly checked that the left door exists first on creation before the right door (in terms of code order)

Comment (tobylane) [reply CorsixTH/Lua/objects/doors/swing_door_right.lua:45]: They are always built together, regardless of orientation. I can't cause this assert to trigger, so I expect no one ever reaches it.

File: CorsixTH/Lua/objects/doors/swing_door_right.lua [hunk 2]
```diff
@@ -39,18 +39,14 @@ function SwingDoor:SwingDoor(hospital, object_type, x, y, direction, etc)
...
   end
   self.old_anim = self.th:getAnimation()
   self.old_flags = self.th:getFlag()
+  local --[[persistable:swing_door_creation]] function _() end -- Stub from Oct 2023, savegame version 181
```
Comment (lewri) [inline CorsixTH/Lua/objects/doors/swing_door_right.lua:49]: Can you make a wiki note in coding conventions for when we need to use a stub? I appreciate the use of the savegame version as the comment

**Review by lewri — APPROVED** [review]
Could you make a hotfix version of this patch too targeting 0.67 branch/tag (not sure what we used) -- I'm not sure we'll use it but at this point I'd like it in reserve for now until we get a decision. But currently, there's been no reports for several weeks either of this bug.

This PR itself may need an amendment if the hotfix route is taken (or worst case it can be done later).

**Comment by tobylane** [comment]
Done both, here's the hotfix. https://github.com/CorsixTH/CorsixTH/compare/v0.67...tobylane:CorsixTH:hotfix-0.67.1?expand=1 https://github.com/tobylane/CorsixTH/commits/hotfix-0.67.1/
