### PR TITLE
Kill staff returned to crashed rooms

### LINKED ISSUE #2696: [Bug] Crash on cancel grab after room exploded
### Describe the issue

If grab doctor slightly before the room explosion, then he will survive. But if then press Esc doctor will be returned whatever he was grabbed from.
This way he will back to an exploded room. 
But this is not valid state in the game by the moment.

Screenshot 2024-10-21 at 22 43 30

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. Press Esc. Doctor will be returned to the exploded room where it was grabbed from.
3. He goes to exit door and Lua crash.

### Expected Behaviour

Not sure. But it shouldn't crash the game.

### Save Game

[room_crashed_doc_in_grab_scan.sav.zip](https://github.com/user-attachments/files/17475796/room_crashed_doc_in_grab_scan.sav.zip)

[room_crashed_doc_in_grab_surg.sav.zip](https://github.com/user-attachments/files/17475797/room_crashed_doc_in_grab_surg.sav.zip)

### CorsixTH Version

0.68.0

### Operating System

MacOS Sonoma 14.5

### Gamelog.txt

```yaml
Gamelog generated on 2024-10-21 22:38:43
Compiled with api_version: 2687, arch: arm64, audio: true, os: macos, update_check: true
SDL renderer: metal
Lua 5.4 run with api version: 2687, game version: v0.68.0, savegame version: 194
Created game with savegame version 191.


Savegame changed from 191 (v0.68.0) to 194 (v0.68.0). The save was created using 191 (v0.68.0).
Error in buttonup handler: 
...ents/MacOS/../Resources/Lua/entities/humanoids/staff.lua:524: attempt to index a nil value (field 'queue')
stack traceback:
	...ents/MacOS/../Resources/Lua/entities/humanoids/staff.lua:524: in method 'isIdle'
	...ents/MacOS/../Resources/Lua/entities/humanoids/staff.lua:307: in method 'dump'
	...pp/Contents/MacOS/../Resources/Lua/entities/humanoid.lua:358: in field 'onClick'
	...ents/MacOS/../Resources/Lua/entities/humanoids/staff.lua:296: in method 'onClick'
	...s/Corsix.68.0.app/Contents/MacOS/../Resources/Lua/ui.lua:881: in function <...s/Corsix.68.0.app/Contents/MacOS/../Resources/Lua/ui.lua:864>
	(...tail calls...)
	.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1139: in function <.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1134>
Error in timer handler: 
...ontents/MacOS/../Resources/Lua/humanoid_actions/walk.lua:267: attempt to index a nil value (field 'queue')
stack traceback:
	...ontents/MacOS/../Resources/Lua/humanoid_actions/walk.lua:267: in function <...ontents/MacOS/../Resources/Lua/humanoid_actions/walk.lua:249>
	(...tail calls...)
	...ontents/MacOS/../Resources/Lua/humanoid_actions/walk.lua:227: in local 'timer_function'
	...rsix.68.0.app/Contents/MacOS/../Resources/Lua/entity.lua:216: in field 'tick'
	...ents/MacOS/../Resources/Lua/entities/humanoids/staff.lua:112: in field 'tick'
	...cOS/../Resources/Lua/entities/humanoids/staff/doctor.lua:95: in method 'tick'
	...orsix.68.0.app/Contents/MacOS/../Resources/Lua/world.lua:917: in method 'onTick'
	.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1239: in function <.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1236>
	(...tail calls...)
	.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1139: in function <.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1134>
```

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #2696*

**Describe what the proposed change does**
- If a staff member is picked up from a room that then explodes, they can't be returned to the room by closing the pickup 'window', they instead die.

### CODE REVIEW

File: CorsixTH/Lua/humanoid_actions/pickup.lua [hunk 1]
```diff
@@ -47,7 +47,7 @@ local action_pickup_interrupt = permanent"action_pickup_interrupt"( function(act
   end
   humanoid.th:makeVisible()
   local room = humanoid:getRoom()
-  if room then
+  if room and not room.crashed then
```
Comment (TheCycoONE) [inline CorsixTH/Lua/humanoid_actions/pickup.lua:50]: Why would we call onPlaceInCorridor if the room is crashed?

Comment (tobylane) [reply CorsixTH/Lua/humanoid_actions/pickup.lua:50]: In the [operating theatre save](https://github.com/user-attachments/files/17475797/room_crashed_doc_in_grab_surg.sav.zip) from the linked issue, the doctor will go back to the room to change without this.

Comment (lewri) [reply CorsixTH/Lua/humanoid_actions/pickup.lua:50]: Generally the contents of the function called make sense. The weird part is probably that the function name now clashes with the intended result.

Do we have a way to cancel pickup? I don't believe we do yet.

Comment (ARGAMX) [reply CorsixTH/Lua/humanoid_actions/pickup.lua:50]: > In the [operating theatre save](https://github.com/user-attachments/files/17475797/room_crashed_doc_in_grab_surg.sav.zip) from the linked issue, the doctor will go back to the room to change without this.

Toby, do you have video when doctor go back to the room to change?

He shouldn't go back, I think.

And with the latest changes to the operating theatre, the doctor takes off his robe when he lifts up and doesn't have to go back down.

Comment (TheCycoONE) [reply CorsixTH/Lua/humanoid_actions/pickup.lua:50]: I don't like calling onPlaceInCorridor here; which I think I made clear. That function is overwritten by various staff types and can be reasonably expected to be a callback that happens when a staff member is placed in a corridor.

I suggest copying out the functionality you want from that callback and making a new callback. Code duplication will cause fewer problems in the future than overloaded meanings. Potentially resolved with local functions covering the duplicated functionality.

Comment (tobylane) [reply CorsixTH/Lua/humanoid_actions/pickup.lua]: Now it returns early if the room has crashed. It also avoids the finishAction that shouldn't happen.

**Comment by TheCycoONE** [comment]
LGTM
