### PR TITLE
Use date and time in log filenames

### LINKED ISSUE #2665: Make gamelogs unique
### What feature or enhancement would you like to add?

Currently when a game crashes we overwrite the gamelog file, which could destroy error trace data before it is reported back to here.

A suggestion here is to generate a tagged gamelog.txt file with the savegame name and date/time in the name to preserve the error entry.

Additionally, a method would need to exist to remove old logs from within the game.

### How would this feature benefit the gameplay of CorsixTH?

While having a single gamelog file makes it simpler for uses, it is potentially destructive in nature. Multiple will allow it to be pinpointed and preserved.

### Was the feature in the original game?

No

### What version of CorsixTH are you using?

0.68.0

### Does this feature/enhancement relate to a current problem?

No

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by tobylane**
*Fixes #2665*

**Describe what the proposed change does**
- The gamelog is written to a file, in a new logs subfolder, named for the current date, time. At this point, older logs are deleted.

Flaws
- No UI yet

### CODE REVIEW

File: CorsixTH/Lua/app.lua [hunk 1]
```diff
@@ -389,24 +389,38 @@ function App:init()
...
+  local gamelog_path = self:getGamelogPath(save_name)
   local gamelog = io.open(gamelog_path, "r")
   if gamelog then gamelog:close() return end
 
   local fi = self:writeToFileOrTmp(gamelog_path)
   local sysinfo = self:gamelogHeader()
   fi:write(sysinfo)
   fi:close()
+  self:trimLogs()
+end
```
Comment (lewri) [inline CorsixTH/Lua/app.lua:410]: If we're making individual logs we no longer need to init a file imo.
We should still init sysinfo and trim though.

File: CorsixTH/Lua/app.lua [hunk 2]
```diff
@@ -1696,6 +1713,7 @@ function App:load(filepath)
   if self.world then
     self:worldExited()
   end
+  self.save_name = filepath:match(".*" .. pathsep .. "(.+)%.sav$")
```
Comment (lewri) [inline CorsixTH/Lua/app.lua:1716]: When player saves a game, probably useful to refresh self.save_name too.

Does `Continue Game` from Main Menu also check the autosaves folder? ... I don't think it does but if it does it could be an issue.

File: CorsixTH/Lua/app.lua [hunk 3]
```diff
@@ -389,24 +389,38 @@ function App:init()
...
+end
+
+--! Trims the logs folder of old game logs down to ten files.
+function App:trimLogs()
+  local log_rentention, log_table = 11, {}
+  for node in lfs.dir(self.user_log_dir) do
+    local file = self.user_log_dir .. pathsep .. node
+    if lfs.attributes(file, "mode") == "file" then
+      table.insert(log_table, file)
+    end
```
Comment (lewri) [inline CorsixTH/Lua/app.lua:419]: Probably not an issue, but we're deleting any file indiscriminately in this folder > 1mo.

File: CorsixTH/Lua/app.lua [hunk 4]
```diff
@@ -389,24 +389,38 @@ function App:init()
...
---! Works out the intended location of the gamelog file.
+--! Works out the intended location of the gamelog file based on the time and save game name.
 --!return full path gamelog should exist at
-function App:getGamelogPath()
-  local config_path = self.command_line["config-file"] or ""
-  config_path = config_path:match("^(.-)[^" .. pathsep .. "]*$")
-  return config_path .. "gamelog.txt"
+function App:getGamelogPath(save_name)
+  return self.user_log_dir .. pathsep .. os.date("%y-%m-%d--%H-%M-%S--") ..
+      (save_name or 'unknown') .. ".txt"
```
Comment (lewri) [inline CorsixTH/Lua/app.lua:396]: `New Game`?

**Review by lewri — COMMENTED** [review]
Some other thoughts about this are out of scope, which if I remember I'll add them to the issue.

File: CorsixTH/Lua/app.lua (hunk 3 above)
Comment (lewri) [reply CorsixTH/Lua/app.lua:419]: Unless you're trying to establish we just have write permission, toby?

File: CorsixTH/Lua/app.lua (hunk 2 above)
Comment (tobylane) [reply CorsixTH/Lua/app.lua:1716]: It does, so continuing a named save will be logged in files named for the autosave. That is possible to fix for the future, this save_name can be in world, but it could be confusing for existing games. I'm thinking about taking the save name out of the filename, so at least old gamelogs aren't overwritten.

**Comment by TheCycoONE** [comment]
Why don't we just use the date and exclude the save name?

**Comment by TheCycoONE** [comment]
I'm working on a bigger effort here to use spdlog with it's built in rolling log appender, and capturing all our engine errors/messages in the same files.

Maybe close this PR?

**Comment by TheCycoONE** [comment]
Digging deeper, my approach doesn't solve this problem at all. Reopening this PR. Sorry @tobylane

**Comment by tobylane** [comment]
The gamelog path is set at launch. With the time in the filename, it's taken out of the gamelog header. Old gamelogs are only trimmed if the new one was successfully written to the intended path, rather than tmp.

**Comment by lewri** [comment]
That would indicate this is using UTC time, but needs a new blank issue opened for it if it should be targeting local device time.
