### PR TITLE
[RDY] Money Bar non-CJK unicode fix

### LINKED ISSUE #2650: Money Bar - fix for CJK downgrades experience for non-CJK unicode languages
Originally mentioned by @tobylane as part of #2531, and a few users from discord, the changes to the money bar to work properly with CJK languages is less appealing to non-CJK users where they have to use a unicode font (e.g. Russian, Czech etc).

image

image
Images originally by @argamx

It may be better to fine tune the money bar's font usage (bitmap or unicode) by language. The bitmap font was originally intended to only be a stopgap for #1193 though it may be preferred.

### PR DESCRIPTION
**Pull request by ARGAMX**
*Fixes #2650*

**Describe what the proposed change does**
- This algorithm has been implemented (link to comment):
https://github.com/CorsixTH/CorsixTH/issues/2650#issuecomment-2386443272

Feature is working fine.

~~Problem that is no longer relevant:~~

<details>

<summary>problem details</summary>

But during the work on PR I encountered a problem that I unable to solve gracefully.

I had to place `IsArabicNumerals(true)` in the language files in a specific way for this parameter to work - before `Language()` parameter.

461cb5581a

If I place `IsArabicNumerals(true)` under `Language()` then the things works like there is no any `IsArabicNumerals(true)` in language file.

If I move `Language()` lower, so that it is under `IsArabicNumerals(true)`, then all works fine. 

Can anyone explain why this is happening?
Why don't other parameters experience this problem?
How can I make the parameter `IsArabicNumerals(true)` readable anywhere in the file, not just above `Language()`?

Thanks.

</details>

### CODE REVIEW

**Comment by tobylane** [comment]
proof of concept commit: https://github.com/CorsixTH/CorsixTH/commit/57ee908ee6805b8fc26c419bc8abd7a288245e57  
branch rebased on master: https://github.com/tobylane/CorsixTH/tree/refs/heads/unicodenumbers

Of the two `IsArabicNumerals` in strings.lua, it goes in the other one, where the context is language instead of chunk. Just calling it in the language file is enough, the parameters don't matter (but could if you wanted to). This call can go in any of the five positions in your screenshot.

**Comment by ARGAMX** [comment]
> proof of concept commit: [57ee908](https://github.com/CorsixTH/CorsixTH/commit/57ee908ee6805b8fc26c419bc8abd7a288245e57) branch rebased on master: https://github.com/tobylane/CorsixTH/tree/refs/heads/unicodenumbers
> 
> Of the two `IsArabicNumerals` in strings.lua, it goes in the other one, where the context is language instead of chunk. Just calling it in the language file is enough, the parameters don't matter (but could if you wanted to). This call can go in any of the five positions in your screenshot.

Wow, thanks, Toby. 👍 👍 👍

Works great.
(It's still a mystery to me why)

I wasted a several days on this, because the value was in the bottom position and the game never read it there. It was in 2024.

When, after a about 6 months, I decided to return to this task again, I accidentally noticed that in the first position it read ok.

File: CorsixTH/Lua/strings.lua [hunk 1]
```diff
@@ -63,7 +63,9 @@ function Strings:init()
   self.language_to_chunk = {}
   self.chunk_to_font = {}
   self.chunk_to_names = {}
+  self.chunk_to_is_arabic_numerals = {}
```
Comment (tobylane) [inline CorsixTH/Lua/strings.lua:66]:
```suggestion
```

**Review by tobylane — COMMENTED** [review]
With this unused line removed, all good.

**Review by tobylane — APPROVED** [review]
