### PR TITLE
Dynamically Pair Swing Doors

### LINKED ISSUE #2476: [Bug] Game crash while building a ward
### Describe the issue

First level, build large ward, after placing door and no windows, game sometimes crashes on going to the next phase

Screenshot from 2024-01-26 21-28-53

Crash stackdump in the gamelog part of the issue

### Steps to Reproduce

1. Start new level in master 835bb9aa

2.  Select ward room to build, drag a rectangle, place a door (not close to either side may be significant, not sure)

3. Skip placing windows by pressing on 🗸 for the next phase

4. Crash (sometimes), not sure if trying again will ever crash if the first time didn't. I never tried that much though.

### Expected Behaviour

Sane looking walls and door, and being able to place a bed :)

### Save Game

Save game attached to report: No

### CorsixTH Version

master 835bb9aa

### Operating System

Mint - something

### Theme Hospital Version

CD

### Gamelog.txt

```bash
starting game with difficulty full
Created game with savegame version 181.
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
...rth_fork/CorsixTH/Lua/objects/doors/swing_door_right.lua:44: attempt to index a nil value (field 'slave')
stack traceback:
	...rth_fork/CorsixTH/Lua/objects/doors/swing_door_right.lua:44: in local 'constructor'
	...dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/class.lua:74: in field '?'
	...dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/world.lua:1973: in method 'newObject'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:489: in method 'finishRoom'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:230: in method 'confirm'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:342: in method 'clearArea'
	...h/corsix_alberth_fork/CorsixTH/Lua/dialogs/edit_room.lua:226: in local 'callback'
	...ev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/window.lua:699: in method 'handleClick'
	...ev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/window.lua:1658: in field 'onMouseUp'
	...rsix_alberth_fork/CorsixTH/Lua/dialogs/place_objects.lua:452: in function <...rsix_alberth_fork/CorsixTH/Lua/dialogs/place_objects.lua:451>
	(...tail calls...)
	...ev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/window.lua:1642: in field 'onMouseUp'
	...th/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/ui.lua:877: in function <...th/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/ui.lua:864>
	(...tail calls...)
	...h/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/app.lua:1102: in function <...h/dev/corsix-th/corsix_alberth_fork/CorsixTH/Lua/app.lua:1097>
```

### Additional Information

App has version line
``` lua
local SAVEGAME_VERSION = 181 -- Pair swing doors instantly
```

Previous MR: https://github.com/CorsixTH/CorsixTH/pull/2436

Previous BR: https://github.com/CorsixTH/CorsixTH/issues/2389

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2476*

**Describe what the proposed change does**
- Re-uses Edvin's entrance door function to pair doors in Swing Door to allow both doors to be built in either order.

~~This removes Toby's assertion from #2436 currently and it needs to be put back in in a good place.~~ now put back

### CODE REVIEW

File: CorsixTH/Lua/objects/doors/swing_door_right.lua [hunk 1]
```diff
@@ -38,22 +38,35 @@ local SwingDoor = _G["SwingDoor"]
...
+     self.master.slave = self
+   end
+ end
+end
 
-!param swing_door (Door) The master door to mimic.
-]]
 function SwingDoor:setAsSlave(swing_door)
   self.master = swing_door
 end
```
Comment (lewri) [inline CorsixTH/Lua/objects/doors/swing_door_right.lua:72]: This function should be removed. Will remove it later

File: CorsixTH/Lua/objects/doors/swing_door_right.lua [hunk 2]
```diff
@@ -38,22 +38,35 @@ local SwingDoor = _G["SwingDoor"]
...
+     self.slave.master = self
+   end
+ else -- The slave will check for an adjacent master
+   local master_type = "swing_door_right"
+   self.master = self.world:getObject(x + 1, y, master_type) or self.world:getObject(x, y + 1, master_type) or nil
+
+   if self.master then
+     self.master.slave = self
+   end
+ end
```
Comment (tobylane) [inline CorsixTH/Lua/objects/doors/swing_door_right.lua:67]:
```suggestion
    local slave_type = "swing_door_left"
    self.slave = self.world:getObject(x - 1, y, slave_type) or self.world:getObject(x, y - 1, slave_type)

    if self.slave then
      self.slave.master = self
    end
  else -- The slave will check for an adjacent master
    local master_type = "swing_door_right"
    self.master = self.world:getObject(x + 1, y, master_type) or self.world:getObject(x, y + 1, master_type)

    if self.master then
      self.master.slave = self
    end
  end
  assert((self.master and self.master.slave) or (self.slave and self.slave.master),
      "Swing doors did not pair at " .. x .. "," .. y)
```
Added the assert line, took out "or nil", and a minor whitespace fix. This works on the saves I had from before - wards and operating theatres with doors facing all directions

Comment (lewri) [reply CorsixTH/Lua/objects/doors/swing_door_right.lua:67]: What happens on our first run of this? Generally speaking only one half of the door exists so it shouldn't be able to set `self.master.slave` nor `self.slave.master`.

On testing, the assert does crash on building a new room:
```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
Lua\objects/doors\swing_door_right.lua:66: Swing doors did not pair at 60,63
stack traceback:
        [C]: in function 'assert'
        Lua\objects/doors\swing_door_right.lua:66: in method 'pairDoors'
```

Comment (tobylane) [reply CorsixTH/Lua/objects/doors/swing_door_right.lua:67]: Yes, I didn't test well.

File: CorsixTH/Lua/objects/doors/swing_door_right.lua [hunk 3]
```diff
@@ -157,11 +170,12 @@ function SwingDoor:getWalkableTiles()
...
-  if old < 181 and self.is_master and not self.slave then
-    local slave_type, x, y = "swing_door_left", self.tile_x, self.tile_y
-    self.slave = self.world:getObject(x - 1, y, slave_type) or self.world:getObject(x, y - 1, slave_type)
-    self.slave:setAsSlave(self)
-    assert(self.slave.master, "Swing doors are not paired at " .. x .. "," .. y)
+  if old < 184 then
+    if (self.is_master and not self.slave) or (not self.is_master and
+        not self.master) then
+    local x, y =  self.tile_x, self.tile_y
+    self:pairDoors(x, y)
```
Comment (tobylane) [inline CorsixTH/Lua/objects/doors/swing_door_right.lua:177]:
```suggestion
    self:pairDoors(x, y)
    assert((self.master and self.master.slave) or (self.slave and self.slave.master),
        "Swing doors did not pair at " .. x .. "," .. y)
```
Tested on a newly made save from v0.67 and new worlds.

Comment (lewri) [reply CorsixTH/Lua/objects/doors/swing_door_right.lua:177]: That is probably fine for the afterload, though it will still potentially fall over if the save happened during the door creation (incredibly slim). Would suffer the same fate as https://github.com/CorsixTH/CorsixTH/pull/2510/files#r1509644565 in that case.

**Comment by lewri** [comment]
@tobylane would this assert method work? May need tidying.

File: CorsixTH/Lua/objects/doors/swing_door_right.lua [hunk 4]
```diff
@@ -38,24 +38,55 @@ local SwingDoor = _G["SwingDoor"]
...
-]]
-function SwingDoor:setAsSlave(swing_door)
-  self.master = swing_door
+--! Checks to see if the swing doors have paired correctly
+function SwingDoor:checkPaired(x, y)
+  if self.paired then
+    assert((self.master and self.master.slave == self) or
+        (self.slave and self.slave.master == self),
+        "Swing doors did not pair at (" .. x .. ", " .. y .. ")")
+  else -- The other door should not yet exist
```
Comment (tobylane) [inline CorsixTH/Lua/objects/doors/swing_door_right.lua:83]: This is reached when pairDoors is run on a door without its pair? I can't imagine how, but it's worth catching. 👍

**Review by tobylane — APPROVED** [review]

File: CorsixTH/Lua/objects/doors/swing_door_right.lua (hunk 4 above)
Comment (lewri) [reply CorsixTH/Lua/objects/doors/swing_door_right.lua:83]: Yeah... I feel like because of the way this function works we actually have to test for all cases:
- Case A: The doors report themsleves and paired and we should make sure that the correct pairing happened
- Case B: The doors report not paired, and we should make sure that the adjacent door doesn't exist.

**Comment by lewri** [comment]
Ready
