### PR TITLE
[RDY] Add earthquake cheat function

### LINKED ISSUE #1634: Earthquake Cheat broken/not written
#### Describe the issue
Not sure which, but the 'Create Earthquake' cheat button does not work and produces an error

#### Steps to Reproduce
1. Go to the cheats menu and press 'create earthquake'

#### Expected Behavior
An earthquake should trigger.

#### System Information
**CorsixTH Version:** 0.64 rc1 // 0.63 // and trunk (138)

**Operating System:** W10

**Theme Hospital Version:** GOG

#### Gamelog.txt
```
An error has occurred!
Almost anything can be the cause, but the detailed information below can help the developers find the source of the error.
Running: The buttonup handler.
A stack trace is included below, and the handler has been disconnected.
Lua\dialogs/resizables\cheats.lua:197: attempt to call a nil value (method 'createEarthquake')
stack traceback:
        Lua\dialogs/resizables\cheats.lua:197: in field 'func'
        Lua\dialogs/resizables\cheats.lua:133: in method 'buttonClicked'
        Lua\dialogs/resizables\cheats.lua:100: in local 'callback'
        Lua\window.lua:691: in method 'handleClick'
        Lua\window.lua:1652: in method 'onMouseUp'
        Lua\window.lua:1636: in field 'onMouseUp'
        Lua\ui.lua:902: in function <Lua\ui.lua:889>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>

Error in buttonup handler:
Lua\dialogs/resizables\cheats.lua:197: attempt to call a nil value (method 'createEarthquake')
stack traceback:
        Lua\dialogs/resizables\cheats.lua:197: in field 'func'
        Lua\dialogs/resizables\cheats.lua:133: in method 'buttonClicked'
        Lua\dialogs/resizables\cheats.lua:100: in local 'callback'
        Lua\window.lua:691: in method 'handleClick'
        Lua\window.lua:1652: in method 'onMouseUp'
        Lua\window.lua:1636: in field 'onMouseUp'
        Lua\ui.lua:902: in function <Lua\ui.lua:889>
        (...tail calls...)
        Lua\app.lua:1012: in function <Lua\app.lua:1007>
Warning: No event handler for buttonup

```

### Additional Info
I would assume the latter that the code is not currently written for the earthquake cheat. In which case, some kind of handler would be best implemented to prevent game crashes (you can't close the cheats dialogue once you press the button). Or remove the 'create earthquake' button for now from the menu.

### PR DESCRIPTION
**Pull request by lewri**
Fixes #1634 

Function will call the next earthquake in the level file if available, otherwise it will forcefully make one at random.

Previously this cheat would cause the game to partially break because the function didn't exist.
If it's too late to merge this, I can make another PR to remove the menu option for earthquakes instead.

### CODE REVIEW

File: CorsixTH/Lua/world.lua [hunk 1]
```diff
@@ -1340,6 +1340,22 @@ function World:nextEarthquake()
...
+  if not self.next_earthquake.active then
+    self.next_earthquake.start_day = self.game_date:dayOfMonth()
+    self.next_earthquake.start_month = self.game_date:monthOfGame()
+    if self.next_earthquake.size == nil then
+      --forcefully make an earthquake if none left in level file
+      self.next_earthquake.size = math.random(1,6) -- above 6 seems disastrous
+      self.next_earthquake.remaining_damage = self.next_earthquake.size
+      self.next_earthquake.damage_timer = earthquake_damage_time
+      self.next_earthquake.warning_timer = earthquake_warning_period
+      self.current_map_earthquake = self.current_map_earthquake + 1
```
Comment (lewri) [inline CorsixTH/Lua/world.lua:1355]: This line could be potentially unnecessary.
