### PR TITLE
Look for a bundled Noto CJK font

### LINKED ISSUE #823: Automatically select unicode font from system if available
It would be a better experience for our international users if their system default font could be picked up and used as the unicode_font if it's available and a supported type. (e.g. true type). This way their preferred language option would be visible without navigating through the font selection screens.

### LINKED ISSUE #1219: Create Corsix's own unicode font
#### Let's create a font

Any font artists around here maybe? 

I'm trying to use Polish in Corsix, and I managed to use it with some ```.ttf``` fonts, but none of them look good to be honest. Maybe we could try, as community, to create our own unicode font, looking very similar to TH original font (kinda like openTTD did with graphics/sounds)?  Or maybe there is some free font that we could use right now? Arial doesn't work so well.

That would probably fix other issues: https://github.com/CorsixTH/CorsixTH/issues/1213 for example.

I know it's very general idea, but I'm new to this community, and I didn't see anyone mentioning creating own font before.

### LINKED ISSUE #1901: Bundle international fonts and allow users to select all translations available
I read on CorsixTH wiki that Czech translation should be available, but it isn't shown in the game menu. I started dig into the issue, tested Flatpak on Linux and also Windows (same behavior), and ultimately found related issues in #1213, #1219 and #823. When I look into source code, there are 20 different languages supported through translations. However, only 12 of them are available through the game menu. I think this is really unfortunate and harms the project a lot.

I started to experiment with font selection, and found it to be a **terrible** experience, definitely not fit for regular users. First, the file browser starts in `/`, and users have no idea where fonts are stored. I found some known fonts in `/usr/share/fonts`. I tried Dejavu Sans and Liberation Mono, both of which support Czech (and most world languages as well), and Linux distributions use them by default everywhere (including right now when writing this report). Both of them look terrible in CorsixTH, I have no idea why. They are almost unreadable. Dejavu is so broken that e.g. the letter "J" is never rendered, just missing, for some reason.

Furthermore, font experimentation is very tedious, because the font file selection doesn't remember the last selected directory, so you have to traverse the whole structure every time. On top of that, the _Folders_ menu crashes the game when entered (at least in Czech) [1], so you have to constantly switch back to English, change the font, then switch back to your language of choice.

I wonder if all of this is really necessary? How many games offer you to select an arbitrary font (and break the game in the process)? Wouldn't it be better to simply pick two, three open source fonts, which can display most or all world languages when combined, and bundle them into the game? The necessary font would be automatically used for a language that needs it. It would be easy for users, no custom fonts difficulties. It would be easy for developers, a consistent experience instead of random issues arising from random font selection. Power users might still be able to change the font, if you prefer, but just through the config file, the GUI option could be removed. I believe this is much better approach than asking users to deal with font issues, or depending on fonts installed in the system.

I believe this would allow CorsixTH to reach much wider audience. Currently almost half the translations are hidden behind a really difficult and fickle barrier.

Thanks for consideration.

[1]
```
/usr/include/c++/10.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = FT_Vector_; _Alloc = std::allocator<FT_Vector_>; std::vector<_Tp, _Alloc>::reference = FT_Vector_&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__builtin_expect(__n < this->size(), true)' failed.
```

Tested on CorsixTH 0.65-beta1 from Flathub.

### PR DESCRIPTION
**Pull request by tobylane**
**Describe what the proposed change does**
- Look for a bundled Noto CJK font, or a packager chosen bundled font path or a system font path. The official Noto project doesn't release a suitable single file, but there are some third party builds that do. [satbyy](https://github.com/satbyy/go-noto-universal/releases/tag/v7.0) has [GoNotoKurrent-Bold.ttf](https://github.com/satbyy/go-noto-universal/releases/download/v7.0/GoNotoKurrent-Bold.ttf), I chose this because the licence on this project is clearer.
Other font options include [KlokanTechNotoSansCJK-Regular.otf from klokantech](https://github.com/klokantech/klokantech-gl-fonts) or [GoNotoKurrent-Regular.ttf from satbyy](https://github.com/satbyy/go-noto-universal).
- The new priority is user setting > bundled font > system font. Linux users from before this change will have an old user setting by default that is probably worse than Noto for CJK.

Korean preview
Screen 2023-09-04 at 20 56 39

Fixes #1901 fixes #823 fixes #1219

### CODE REVIEW

**Review by lewri — COMMENTED** [review]
For the time being, I don't think we should remove the ability to set font manually. Instead, just let it sit as the default variable.

Also these changes probably break the font dialog.

**Comment by TheCycoONE** [comment]
Prefer not to bundle in the repo without first debating/setting up git lfs. It's sufficient to make it a packaging requirement.

**Comment by tobylane** [comment]
Users's setting > bundled font > OS font. This means if the user has opened CorsixTH on Linux before, the incomplete OS font will be preferred. Line 138 could only choose the setting if it isn't the path two lines above?

I tried to have it pick up the youngest ttf file in the folder, but FileTreeNode isn't available.

**Review by lewri — COMMENTED** [review]
It's worth noting here, ARIALUNI.TTF was a Microsoft Office font (not Windows) and hasn't been included since Office 2016. This would explain why gfx:loadFontFile() never wrote a unicode font to the config.txt since that time.
https://learn.microsoft.com/en-us/typography/font-list/arial-unicode-ms

**Comment by lewri** [comment]
> Users's setting > bundled font > OS font. This means if the user has opened CorsixTH on Linux before, the incomplete OS font will be preferred. Line 138 could only choose the setting if it isn't the path two lines above?
> 
> I tried to have it pick up the youngest ttf file in the folder, but FileTreeNode isn't available.

Why not make it an explicit setting?

**Comment by tobylane** [comment]
I think Arial and Noto are the only pan-CJK fonts. [Google font search](https://fonts.google.com/?preview.text=%EB%B3%91%EC%9B%90%EC%9D%B4%20%EB%AC%B8%EC%9D%84%20%EC%97%B4%EC%97%88%EC%8A%B5%EB%8B%88%EB%8B%A4&preview.text_type=custom&sort=popularity&subset=korean&noto.script=Kore) for the first Korean string in the language file, where after the Noto fonts they are Korean or Korean+European only, not including Chinese and Japanese.

Could we have the non-free Arial package recommended or required by linux packages? Ask the packagers to set the other-os line to the location of the font that their distribution installs Arial to? eg https://packages.debian.org/buster/ttf-mscorefonts-installer

> Why not make it an explicit setting?

Ideally it isn't a user decision at all, depending on how close we can get to an answer for everyone. Strictly free-only (avoiding debian non-free) users who don't like Noto may be left out.

**Comment by lewri** [comment]
We can't rely on Arial Unicode any more in Windows. In Mac, it's still okay (it is in the Font Library). I'd support cyco's suggestion to make it a packaging requirement. Worst case is that if a suitable unicode font is missing unicode languages are just hidden until a font is selected.

**Comment by Alberth289346** [comment]
It should be possible to extract all code points from all strings in a language, and verify that they exist in the font.

When to do that, and what to do if indeed code points are missing are next choices.

**Comment by tobylane** [comment]
Rebased, and put the two new variables at the top of the file for packagers to edit.

**Comment by lewri** [comment]
I think part of the idea is to also change our make files to require the font too as an optional dependency. At the least, we'd need to add more directions to the make instructions say we want to use x specific noto bundle.

>  Remove references/settings about picking a font file. Do we want this option left in?
Did you put this back in now? If we want to encourage Noto you may need to add something perhaps to the config file and/or Wiki we're using Noto as the default, but if your language doesn't show properly for you you can specify another?
Do you know what specific languages we currently support that aren't covered by this bundle?

**Comment by tobylane** [comment]
> Did you put this back in now?

I did, and have updated the title and post.

> If we want to encourage Noto you may need to add something perhaps to the config file and/or Wiki we're using Noto as the default, but if your language doesn't show properly for you you can specify another?

I can draft a wiki page. The config file, and perhaps the folder settings tooltip, could say something like leave empty for a font chosen for you? Should the folder settings run `Graphics:loadFontFile()` when the font setting is cleared to find what it can?

> Do you know what specific languages we currently support that aren't covered by this bundle?

So far as I've seen, all are supported by Noto CJK.

**Review by lewri — APPROVED** [review]
Once merged I would suggest adding to the 'How to Compile' wiki page. We can add (yet another :) ) packaging note on release too.

I appreciate this PR is now only a 'look for', but it definitely is going to need its supporting docs where appropriate.

**Comment by TheCycoONE** [comment]
I feel like we should favour a system noto if that's what we're packaging, over the system arial if available.

This is starting to feel similar to the hospital lookup function.

**Comment by lewri** [comment]
> I feel like we should favour a system noto if that's what we're packaging, over the system arial if available.
> 
> This is starting to feel similar to the hospital lookup function.

Arial unicode is heavily deprecated/removed in Windows. Though that isn't (currently) what this PR is about now.

**Comment by tobylane** [comment]
[Debian](https://packages.debian.org/bookworm/fonts-noto-cjk) follows the official project in not combining the font files. We could have the language file give the suffix (JP, KR, SC, TC from the debian page) for the right file for each non-European language select, but I don't like the sound of that.

**Comment by tobylane** [comment]
Strings are loaded after and depend on Graphics. Strings can load the font file suffix and make the switch later, but that means setting the font twice.

[NotoSansCJK-VF.otf.ttc](https://github.com/notofonts/noto-cjk/tree/main/Sans#variable-otcs) (33mb) is another good option, but [not packaged](https://packages.debian.org/search?searchon=contents&keywords=NotoSansCJK-VF.otf.ttc).

**Comment by lewri** [comment]
@tobylane are #1901 and #823 resolved or partially resolved at all by this PR? If so, could you edit the summary so they point respectively?

**Comment by tobylane** [comment]
Updated, also #1219.

File: CorsixTH/Lua/graphics.lua [hunk 1]
```diff
@@ -18,8 +18,12 @@ LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE. --]]
 
-local TH = require("TH")
+-- The location of a bundled font relative to this file
+local bundled_path = TheApp:getFullPath({"GoNotoKurrent-Bold.ttf"})
+-- The location of a globally installed font
+local installed_path = "/usr/share/fonts/truetype/arphic/uming.ttc"
```
Comment (lewri) [inline CorsixTH/Lua/graphics.lua:24]: Is this global? The path given is likely only *nix global. It seems little odd why you isolated this path though from the other OS paths.

Comment (tobylane) [reply CorsixTH/Lua/graphics.lua:24]: It's for *nix packagers to change, I can make that more clear here or in the wiki. It's likely that *nix packagers will put a font at a global path and Windows packagers will put a font at a local path.

File: CorsixTH/Lua/graphics.lua [hunk 2]
```diff
@@ -18,8 +18,12 @@ LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 SOFTWARE. --]]
 
-local TH = require("TH")
+-- The location of a bundled font relative to this file
+local bundled_path = TheApp:getFullPath({"GoNotoKurrent-Bold.ttf"})
```
Comment (lewri) [inline CorsixTH/Lua/graphics.lua:22]: #2565  -- Regular may be better looking at screenshot comparison

**Comment by TheCycoONE** [comment]
Why are we setting default fonts in two different places, one spot to Arial, and the other to Noto/uming.

**Comment by tobylane** [comment]
The order of preference is user setting > bundled > globally installed. The bundled font, if it exists, should be Noto. The globally installed font is Arial on Windows, which is only supplied by Office; Arial on macOS is always installed; uming or other packager choice on anything else. Is there a better way to find the packagers choice?

[Microsoft Yahei](https://learn.microsoft.com/en-us/typography/font-list/microsoft-yahei) is the CJK font in Windows 11, but it doesn't have the Korean for Korean.

File: CorsixTH/Lua/graphics.lua (hunk 1 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/graphics.lua:24]: This is hard coded, how did you expect packagers to change it?

Comment (tobylane) [reply CorsixTH/Lua/graphics.lua:24]: In a distro specific patch. Debian does it for their game data path, https://salsa.debian.org/games-team/corsix-th/-/tree/debian/master/debian/patches?ref_type=heads

If the Regular weight is chosen, this path should be /usr/share/fonts/opentype/noto/NotoSansCJK-Regular.ttc for Debian and Ubuntu, leaving the different distros like Arch to change it to their path, /usr/share/fonts/noto-cjk/NotoSerifCJK-Regular.ttc.

Comment (tobylane) [reply CorsixTH/Lua/graphics.lua:24]: The distro patch could just edit the default config, and have the packager set path as the initial value. In that case, there's no need for an installed_path variable.

File: CorsixTH/Lua/graphics.lua [hunk 3]
```diff
@@ -131,22 +135,23 @@ function Graphics:loadFontFile()
   elseif self.app.os == "macos" then
     os_path = "/Library/Fonts/Arial Unicode.ttf"
```
Comment (TheCycoONE) [inline CorsixTH/Lua/graphics.lua:136]: No, why would we make it not work on macos? - actually why are we still overriding font in graphics.lua at all?

File: CorsixTH/Lua/graphics.lua (hunk 1 above)
Comment (TheCycoONE) [reply CorsixTH/Lua/graphics.lua:24]: I don't want distros to have to patch our code. A cmake variable would be appropriate.

**Review by TheCycoONE — CHANGES_REQUESTED** [review]

**Comment by tobylane** [comment]
The cmake WITH_FONT option shouldn't be an option, as those are boolean, so it's now a variable. The lua side has been reworked, no change in functionality. Rebased and ready.
