### PR TITLE
Make couches fully passable

### LINKED ISSUE #2211: [Bug] Psychiatric couch tiles are not passable
### Describe the issue

After enabling the debug flag for "Allow blocking off areas" it is possible to build a Psychiatry room like this:
image

The room looks functional, but the game crashes when a patient enters the room because the doctor is unable to path to the comfy chair.
The tile in front of the long couch and the plant combine to make it impossible to reach that chair.

### Steps to Reproduce

1. Load save game attached to this ticket

2. Wait for the patient to enter the Psychiatry room

3. Observe crash when the doctor's pathfinding starts.

To prevent the bug from happening, simply move the plant.

### Expected Behaviour

The game doesn't crash. Instead, the doctor chooses a path that takes him over the tiles in front of the long couch.

### Save Game

Save game attached to report: Yes
[PsychiatryPathing.zip](https://github.com/CorsixTH/CorsixTH/files/9274687/PsychiatryPathing.zip)

### CorsixTH Version

Release 0.66

### Operating System

Windows 10

### Theme Hospital Version

CD

### Gamelog.txt

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2211*

**Describe what the proposed change does**
- Sets both tiles adjacent to couch as passable.
- Previously, the non-passable tile could have a small object put on it. If this is the case, pathfinding will still work as intended after this PR (doctor sees blocked path). However, the player will not be able to place an object on the tile again if they edit the room.

### CODE REVIEW

File: CorsixTH/Lua/objects/couch.lua [hunk 1]
```diff
@@ -54,11 +54,11 @@ object.usage_animations = copy_north_to_south {
 }
 object.orientations = {
   north = {
-    footprint = { {-1, -1, complete_cell = true}, {-1, 0, complete_cell = true}, {0, -1}, {0, 0, only_passable = true} },
+    footprint = { {-1, -1, complete_cell = true}, {-1, 0, complete_cell = true}, {0, -1, only_passable = true}, {0, 0, only_passable = true} },
```
Comment (lewri) [inline CorsixTH/Lua/objects/couch.lua:57]: Just a sidenote: an object may already exist on this now "only_passable" cell. This pr doesn't account for such a case (because nothing breaks with the object there, currently)
