### PR TITLE
[RDY] Fix dynamic info updates during epidemics

### LINKED ISSUE #1173: Dynamic information showing incorrect information
Dynamic information is not always correct.

In this case it should not be showing diagnosis progress it should be something like fed up and going home  
fedup-going home

### PR DESCRIPTION
**Pull request by mugmuggy**
*Fixes #1173/#1606*

**Describe what the proposed change does**
- During epidemics patient info don't update correctly as per #1173
- Prevent patients becoming fed up and leaving when in a room, also mentioned in the same issue
- Added a helper method for setting staff_wait, and wrapped it to prevent some invalid scenarios #1606 - method refers to staff_member and staff_member_set also to only operate on staff, seems a handy shortcut for the class.is Staff and not handyman check.

### CODE REVIEW

File: CorsixTH/Lua/room.lua [hunk 1]
```diff
@@ -493,19 +493,37 @@ function Room:commandEnteringStaff(humanoid, already_initialized)
...
+    state = "activate"
+  end
+
+  if not self.staff_member_set and self.staff_member then
+    self.staff_member:setMood("staff_wait", state)
+    self.staff_member:setDynamicInfoText(dynamic_text)
+  else
+    for staff_member in pairs(self.staff_member_set) do
+      staff_member:setMood("staff_wait", state)
+      staff_member:setDynamicInfoText(dynamic_text)
```
Comment (lewri) [inline CorsixTH/Lua/room.lua:516]: `staff_member:setDynamicInfoText(dynamic_text)` will have a clash with #2125.
Did you want this PR to go first, or to wait for the other PR?

**Review by lewri — COMMENTED** [review]
LGTM. I tripped up trying to find how you handled handymen but saw it in the end.

File: CorsixTH/Lua/room.lua [hunk 2]
```diff
@@ -493,19 +493,37 @@ function Room:commandEnteringStaff(humanoid, already_initialized)
   end
 end
 
+
+
```
Comment (lewri) [inline CorsixTH/Lua/room.lua:497]: Don't think these two newlines are required? But it's not blocking if we left them in imo.

**Review by lewri — APPROVED** [review]
