### PR TITLE
Epidemic. Vaccination cursor does not work fix

### LINKED ISSUE #2736: [Bug] Epidemic. Vaccination cursor does not work
### Describe the issue

After pressing starting Epidemic and pressing "Attempt to cure all infected patients" in Epidemic fax, when pointing cursor on any Epidemic patient cursor becomes a spray can.

By pressing this spray can on Epidemic patient you marking him to be vaccinated by nurse.

In the vanilla TH you don't have to press the spray can button above the timer to do this.

But it CTH if you didn't press spray can button above the timer you can't mark Epidemic patients.

vanilla Theme Hospital footage which demonstrates this behaviour: https://youtu.be/_PeCGwKKoZs?t=480

### Steps to Reproduce

1. *Load save game attached to this ticket*
2. Press on any contagious patient without pressing spray can button above the timer.
3. Observer that patient marking not happened.

### Expected Behaviour

Pressing on any contagious patient without pressing spray can button above the timer should mark patient for vaccination as in vanilla TH.

### Have you enabled any current CorsixTH Experimental Features?

- [ ] Right mouse panning
- [ ] Falling actions

### Save Game

[epidemic_cursor_dont_work.sav.zip](https://github.com/user-attachments/files/18085445/epidemic_cursor_dont_work.sav.zip)

### CorsixTH Version

0.66.0

### Operating System

MacOS Sonoma 14.5

### Theme Hospital Version

GOG.com

### Gamelog.txt

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ARGAMX**
*Fixes #2736*

**Describe what the proposed change does**
- Restores the functionality of the Epidemiology Cursor to the same UX as in the original game.

Test cases:

```
Clicking with vaccination mode off:
   Epidemic not marked patient - mark.
   Epidemic marked patient - open window.
   Regular patient - open window.

Clicking with vaccination mode on:
   Epidemic not marked patient - mark. 
   Epidemic marked patient - do nothing.
   Regular patient - do nothing.
```

### CODE REVIEW

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 1]
```diff
@@ -72,10 +72,13 @@ function Patient:onClick(ui, button)
     else
       local hospital = self.hospital or self.world:getLocalPlayerHospital()
       local epidemic = hospital and hospital.epidemic
-      if epidemic and epidemic.vaccination_mode_active then
+      if not epidemic or
+        (not epidemic.coverup_selected or
+        (not self.infected or self.marked_for_vaccination) and
+        not epidemic.vaccination_mode_active) then
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/patient.lua]: This is the code mostly from before 1620. But hell is it ugly as sin.
For once I think it needs some breakdown, any possible refactor opportunity?

Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/patient.lua]: (Clarity given on discord)

Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoids/patient.lua]: ok, updated 👍

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 2]
```diff
@@ -72,8 +72,16 @@ function Patient:onClick(ui, button)
     else
       local hospital = self.hospital or self.world:getLocalPlayerHospital()
       local epidemic = hospital and hospital.epidemic
-      if epidemic and epidemic.vaccination_mode_active then
-        epidemic:markForVaccination(self)
+
+      local function isValidEpidemicTarget(epidemic)
+        return epidemic and epidemic.coverup_selected and
+          (epidemic.vaccination_mode_active or (self.infected and (not self.marked_for_vaccination)))
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/patient.lua]: Should be 4 space indent but can live with it, line is already long enough.

File: CorsixTH/Lua/entities/humanoids/patient.lua [hunk 3]
```diff
@@ -72,8 +72,16 @@ function Patient:onClick(ui, button)
...
+      end
+
+      if isValidEpidemicTarget(epidemic) then
```
Comment (lewri) [inline CorsixTH/Lua/entities/humanoids/patient.lua:82]: No need to pass in epidemic; you already declared the variable at line 74 above the function =]
(This is why the code test failed)

**Review by lewri — COMMENTED** [review]
Good to me. Just need to fix the test error.

File: CorsixTH/Lua/entities/humanoids/patient.lua (hunk 3 above)
Comment (lewri) [reply CorsixTH/Lua/entities/humanoids/patient.lua:82]: Looks like it was resolved the other way!

File: CorsixTH/Lua/entities/humanoids/patient.lua (hunk 2 above)
Comment (ARGAMX) [reply CorsixTH/Lua/entities/humanoids/patient.lua]: Added 4 space indent.
