### PR TITLE
Remove Serious Radiation epidemics

### LINKED ISSUE #2760: [Bug] Radiated contagious crash the game on `infect_other`
### Describe the issue

Seriously radiated contagious patient crash the game on `infect_other`.

Image

### Steps to Reproduce

1. *Load save game attached to this ticket*.
2. Wait a bit, until seriously radiated patient near reception will try to infect someone.
3. Observe that Lua crash, game freezes.

### Expected Behaviour

Seriously radiated contagious patient should infect successfully.

Bit strange, but In vanilla TH seriously radiated is valid disease for epidemic. (I have proof with TH savegame) 

### Save Game

[radiated_ contagious_crash_game.sav.zip](https://github.com/user-attachments/files/18444160/radiated_.contagious_crash_game.sav.zip)

### CorsixTH Version

0.68.0, 0.67.0, 0.66.0, 0.65.0

### Operating System

MacOS Sonoma 14.5

### Gamelog.txt

```yaml
Error in timer handler: 
...ts/MacOS/../Resources/Lua/entities/humanoids/patient.lua:121: Cannot change a disease to a non-contagious disease
stack traceback:
	[C]: in function 'assert'
	...ts/MacOS/../Resources/Lua/entities/humanoids/patient.lua:121: in method 'changeDisease'
	...ix.68.0.app/Contents/MacOS/../Resources/Lua/epidemic.lua:174: in local 'infect_other'
	...ix.68.0.app/Contents/MacOS/../Resources/Lua/epidemic.lua:201: in method 'infectOtherPatients'
	...ix.68.0.app/Contents/MacOS/../Resources/Lua/epidemic.lua:108: in method 'tick'
	...ix.68.0.app/Contents/MacOS/../Resources/Lua/hospital.lua:1239: in method 'manageEpidemics'
	...ix.68.0.app/Contents/MacOS/../Resources/Lua/hospital.lua:755: in method 'tick'
	...orsix.68.0.app/Contents/MacOS/../Resources/Lua/world.lua:904: in method 'onTick'
	.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1239: in function <.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1236>
	(...tail calls...)
	.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1139: in function <.../Corsix.68.0.app/Contents/MacOS/../Resources/Lua/app.lua:1134>
```

### PR DESCRIPTION
**Pull request by lewri**
*Fixes #2760*

**Describe what the proposed change does**
- Checks the active epidemic and future epidemic pool for any Serious Radiation epidemics and removes them

While writing this I realise borrowing and revising the `cancelEpidemics` code may have been overkill; and possible that a simple copy of code into the afterload may have been wiser and cleaner...

### CODE REVIEW

File: CorsixTH/Lua/hospital.lua [hunk 1]
```diff
@@ -1250,19 +1250,28 @@ function Hospital:manageEpidemics()
...
+  local function cancelEpidemic(epidemic)
+    if disease and disease ~= epidemic.disease then return false end
+    epidemic:cancelEpidemic()
+    return true
+  end
   -- Cancel ongoing epidemic
   if self.epidemic ~= nil then
-    self.epidemic:cancelEpidemic()
+    cancelEpidemic(self.epidemic)
     self.epidemic = nil
```
Comment (lewri) [inline CorsixTH/Lua/hospital.lua:1265]:
```suggestion
    if cancelEpidemic(self.epidemic) then self.epidemic = nil end
```

File: CorsixTH/Lua/hospital.lua [hunk 2]
```diff
@@ -1250,19 +1250,28 @@ function Hospital:manageEpidemics()
   end
 end
 
---[[ For Cheat - Cancel ongoing and future epidemics. ]]
-function Hospital:cancelEpidemics()
+--! Cancel ongoing and future epidemics.
+--!param disease (table) Optional, if specified only epidemics of a certain disease
+-- will be cancelled.
```
Comment (Alberth289346) [inline CorsixTH/Lua/hospital.lua:1255]:
```suggestion
-- will be cancelled.
--!return Whether the epidemic was canceled.
```

Comment (Alberth289346) [reply CorsixTH/Lua/hospital.lua:1255]: Hmm, sorry, that is wrong I think now.

File: CorsixTH/Lua/hospitals/player_hospital.lua [hunk 3]
```diff
@@ -837,6 +837,16 @@ function PlayerHospital:afterLoad(old, new)
   if old < 159 then
     self.adviser_data.reception_advice = self.adviser_data.reception_advice or self.receptionist_msg
   end
+  if old < 210 then
+    -- Serious Radiation epidemics could exist in old saves and cause a crash
+    local serious_radiation = TheApp.diseases["serious_radiation"]
+    if self.epidemic and self.epidemic.disease == serious_radiation then
+      -- Tell the player somehow we ended the epidemic, EPI0008 is most fitting
+      self.world.ui:playAnnouncement("EPID008.wav", AnnouncementPriority.Critical)
+      self.world:gameLog("Notice: Removing active epidemic for Serious Radiation. See issue 2760.")
```
Comment (Alberth289346) [inline CorsixTH/Lua/hospitals/player_hospital.lua:846]:
```suggestion
      self.world:gameLog("Notice: Removing active epidemic for Serious Radiation as it may crash the game due to a bug.")
```

Comment (Alberth289346) [reply CorsixTH/Lua/hospitals/player_hospital.lua:846]: Users probably don't even know what issue 2760 is.

Comment (lewri) [reply CorsixTH/Lua/hospitals/player_hospital.lua:846]: This is probably more useful for the spd_log draft concept I agree. Though gamelog *is useful to us*.
Nevertheless I'll drop it.

Comment (Alberth289346) [reply CorsixTH/Lua/hospitals/player_hospital.lua]: You could mention the issue as a side-remark, it just shouldn't be the explanation itself.

For us, the usual way in is to search that phrase in git and from the revision with the change you can then find what was done and what issues were involved.

Another option is to add the issue number as comment to the code there.  
The problem of that is aging.

**Comment by TheCycoONE** [comment]
We won't be able to restore these when we fix the issue 😦

**Comment by lewri** [comment]
> We won't be able to restore these when we fix the issue 😦 I think we can do something less invasive and not save-impacting if we swap out the disease when it activates?

We could, but Serious Radiation has visual characteristics. Our code can't handle a change to visuals right now -- serious radiation epidemics infected others but didn't start making them glow green. In reverse, the effect appears to not be possible to take away either (though afaik in the original Serious Radiation couldn't have its disease changed; it could only infect others?).

**Review by ARGAMX — APPROVED** [review]
LGTM

**Comment by lewri** [comment]
> We won't be able to restore these when we fix the issue 😦 I think we can do something less invasive and not save-impacting if we swap out the disease when it activates?

Another option is doing a `if old < x and new < y` when we fix properly. In fact, you could also remove the afterload completely if it's fixed again.
